//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AccountBookVo, DataSuiteVo, NSArray, NSDate, NSDictionary, NSNumber, NSString, UIImage;

@protocol AccountBookService <NSObject>
- (NSDate *)lastTimeUserEnterPasswordWhenDeletingAccountBook;
- (void)setTimeUserEnterPasswordWhenDeletingAccountBook;
- (_Bool)needUserEnterPasswordWhenDeletingAccountBook;
- (void)setUserDoNotNeedEnterPasswordWhenDeletingAccountBook:(_Bool)arg1;
- (_Bool)removeAccountBookCoverName:(AccountBookVo *)arg1;
- (_Bool)updateAccountBook:(AccountBookVo *)arg1 coverName:(NSString *)arg2;
- (AccountBookVo *)accountBookVoFromDict:(NSDictionary *)arg1;
- (unsigned long long)validateName:(NSString *)arg1;
- (NSDictionary *)remoteAccountBookDictionary;
- (void)uploadShareImage:(UIImage *)arg1 withAccountBookId:(NSString *)arg2 completion:(void (^)(_Bool, NSURL *, NSString *))arg3;
- (_Bool)updateRemoteAccountBook:(AccountBookVo *)arg1 withEverSharedToSubsriber:(_Bool)arg2;
- (_Bool)updateNeedAddMemberWithSharedAccountBook:(AccountBookVo *)arg1;
- (_Bool)updateRemoteAccountBook:(AccountBookVo *)arg1 withHasParticipant:(_Bool)arg2;
- (_Bool)mergeAndDeleteLocalAccountBook:(AccountBookVo *)arg1 occurredError:(id *)arg2;
- (AccountBookVo *)mergeDefaultAccountBookFromLocal:(AccountBookVo *)arg1 toAccount:(NSString *)arg2 occurredError:(id *)arg3;
- (_Bool)validateQuitShareAccountBook:(AccountBookVo *)arg1 occurredError:(id *)arg2;
- (_Bool)validateDeleteRemoteAccountBook:(AccountBookVo *)arg1 occurredError:(id *)arg2;
- (_Bool)deleteRemoteAccountBook:(AccountBookVo *)arg1 occurredError:(id *)arg2;
- (AccountBookVo *)upgradeLocalAccountBook:(AccountBookVo *)arg1 toAccount:(NSString *)arg2 syncId:(long long)arg3 occuredError:(id *)arg4;
- (void)signOut;
- (_Bool)isSignedIn;
- (NSNumber *)homeAccountScrollHeaderIndexForCurrentAccountBook;
- (_Bool)updateHomeAccountScrollHeaderIndexForCurrentAccountBook:(long long)arg1;
- (void)setBindAccountListForCurrentUser:(NSArray *)arg1;
- (void)setPasswordBindForCurrentUser:(_Bool)arg1;
- (NSArray *)bindAccountListForCurrentUser;
- (_Bool)isPasswordBindForCurrentUser;
- (NSString *)currentSignInAccountId;
- (_Bool)isValidPassword:(NSString *)arg1;
- (NSString *)currentSignInPasswordWithPermanentStorageIfNoPList;
- (NSString *)currentSignInPassword;
- (NSString *)currentSignInAccountWithPermanentStorageIfNoPList;
- (NSString *)currentFinanceMarketUserID;
- (NSString *)currentSignInAccount;
- (NSString *)lastSignInEmailOrMobile;
- (unsigned long long)accountSignInType;
- (NSString *)currentSignInMobileOrEmail;
- (NSString *)currentSignInMobileEmailOrAccount;
- (NSString *)currentSignInMobile;
- (NSString *)currentSignInEmail;
- (void)removeLastSignInEmailOrMobile;
- (void)setCurrentSignInAccountId:(NSString *)arg1;
- (void)setLastSignInEmailOrMobile:(NSString *)arg1;
- (void)setAccountSignInType:(unsigned long long)arg1;
- (void)setCurrentFinanceMarketUserID:(NSString *)arg1;
- (void)setCurrentSignInMobile:(NSString *)arg1;
- (void)setCurrentSignInEmail:(NSString *)arg1;
- (void)signInAccount:(NSString *)arg1 password:(NSString *)arg2 email:(NSString *)arg3 mobile:(NSString *)arg4;
- (void)signInAccount:(NSString *)arg1 password:(NSString *)arg2;
- (void)signInAccount:(NSString *)arg1;
- (void)setUserDefaultsCurrentAccountVo:(AccountBookVo *)arg1;
- (AccountBookVo *)createAccountBookConfigForAccountBook:(AccountBookVo *)arg1 inDataSuite:(DataSuiteVo *)arg2;
- (AccountBookVo *)createAccountBookConfigForDataSuite:(DataSuiteVo *)arg1 withName:(NSString *)arg2;
- (void)upgradeAccountBookConfigFiles;
- (NSArray *)createAccountBookConfigFilesIfNeeded;
- (_Bool)setCurrentAccountBook:(AccountBookVo *)arg1 occurredError:(id *)arg2;
- (AccountBookVo *)findBookWithSyncId:(NSString *)arg1 InDataSuite:(DataSuiteVo *)arg2;
- (AccountBookVo *)defaultAccountBookWithAccountName:(NSString *)arg1;
- (AccountBookVo *)defaultAccountBookInDataSuite:(DataSuiteVo *)arg1;
- (AccountBookVo *)firstRemoteAccountBookVo;
- (AccountBookVo *)firstLocalAccountBookVo;
- (AccountBookVo *)remoteDefaultAccountBookVoIfExist;
- (AccountBookVo *)localDefaultAccountBookVoIfShowed;
- (AccountBookVo *)currentAccountBook;
- (NSString *)currentAccountBookKey;
- (NSString *)homePathForAccount:(NSString *)arg1;
- (NSString *)pathForCurrentAccountBook;
- (_Bool)updateRemoteAccountBook:(AccountBookVo *)arg1;
- (_Bool)changeDatabaseInAccountBookName:(NSString *)arg1 cover:(unsigned long long)arg2;
- (_Bool)updateAccountBook:(AccountBookVo *)arg1 newShareCode:(NSString *)arg2;
- (_Bool)changeCurrentAccountBookName:(NSString *)arg1 oldCoverType:(unsigned long long)arg2;
- (_Bool)changeCurrentAccountBookName:(NSString *)arg1 cover:(unsigned long long)arg2;
- (_Bool)renameAccountBook:(AccountBookVo *)arg1 toName:(NSString *)arg2 occurredError:(id *)arg3;
- (_Bool)deleteRemoteDefaultAccountBookOccurError:(id *)arg1;
- (_Bool)deleteLocalDefaultAccountBookOccurError:(id *)arg1;
- (_Bool)deleteAccountBook:(AccountBookVo *)arg1 occurredError:(id *)arg2;
- (_Bool)copyRemoteAccountBookResourcesFrom:(AccountBookVo *)arg1 to:(AccountBookVo *)arg2;
- (_Bool)addRemoteAccountBook:(AccountBookVo *)arg1 toDataSuite:(DataSuiteVo *)arg2 occurredError:(id *)arg3;
- (_Bool)addRemoteAccountBook:(AccountBookVo *)arg1 occurredError:(id *)arg2;
- (_Bool)isExistAccountBookName:(NSString *)arg1;
- (NSString *)renameExistAccountBookNameWithName:(NSString *)arg1 isRemoteAccountBook:(_Bool)arg2;
- (_Bool)isExistRemoteAccountBookName:(NSString *)arg1;
- (_Bool)isExistLocalAccountBookName:(NSString *)arg1;
- (void)writeLocalAccountBookEntry:(NSDictionary *)arg1 forKey:(NSString *)arg2 onPath:(NSString *)arg3;
- (void)writeLocalAccountBookEntry:(NSDictionary *)arg1 forKey:(NSString *)arg2;
- (_Bool)addLocalAccountBook:(AccountBookVo *)arg1 occurredError:(id *)arg2 dbCallback:(void (^)(id))arg3;
- (_Bool)addLocalAccountBook:(AccountBookVo *)arg1 occurredError:(id *)arg2;
- (NSArray *)allLocalAccountBooksIncludeDefaultAccountBook:(_Bool)arg1;
- (NSArray *)allLocalAccountBooks;
- (void)setLocalDefaultAccountBookHidden:(_Bool)arg1;
- (_Bool)shouldHiddenLocalDefaultAccountBook;
- (NSArray *)excludeRemoteAccountBooksFromBooks:(NSArray *)arg1;
- (void)deleteRemoteAccountBookEntryWithKey:(NSString *)arg1;
- (void)deleteLocalAccountBookEntry:(AccountBookVo *)arg1;
- (AccountBookVo *)nextAccountBookIfNeedToDeleteAccountBook:(AccountBookVo *)arg1;
- (AccountBookVo *)anyAccountBook;
- (NSArray *)allRemoteAccountBooksIcludeJoinedShareAccountBook:(_Bool)arg1;
- (NSArray *)allRemoteAccountBooks;
@end

