//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

@class NSMutableArray, UIButton;

@interface AccountBookCardView : UIScrollView
{
    NSMutableArray *_cells;
    NSMutableArray *_sectionHeaders;
    UIButton *_cancelSelectingButton;
    _Bool _editing;
    id <AccountBookCardViewDataSource> _dataSourceDelegate;
    id <AccountBookCardViewDelegate> _actionDelegate;
}

@property(retain, nonatomic) UIButton *cancelSelectingButton; // @synthesize cancelSelectingButton=_cancelSelectingButton;
@property(retain, nonatomic) NSMutableArray *sectionHeaders; // @synthesize sectionHeaders=_sectionHeaders;
@property(retain, nonatomic) NSMutableArray *cells; // @synthesize cells=_cells;
@property _Bool editing; // @synthesize editing=_editing;
@property(nonatomic) __weak id <AccountBookCardViewDelegate> actionDelegate; // @synthesize actionDelegate=_actionDelegate;
@property(nonatomic) __weak id <AccountBookCardViewDataSource> dataSourceDelegate; // @synthesize dataSourceDelegate=_dataSourceDelegate;
- (void).cxx_destruct;
- (void)clickCellContentAction:(id)arg1;
- (void)cancelSelectAction;
- (id)indexPathWithButton:(id)arg1;
- (void)upgradeAction:(id)arg1;
- (void)editAction:(id)arg1;
- (void)confirmDeleteAction:(id)arg1;
- (void)addAtIndexPath:(id)arg1;
- (void)animationDidStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)deleteAtIndexPath:(id)arg1;
- (void)setCardInEditingWithoutDiseditOthersAtIndexPath:(id)arg1 isEditing:(_Bool)arg2 showDeleteButton:(_Bool)arg3 upgradeButton:(_Bool)arg4 editButton:(_Bool)arg5;
- (void)setCardInEditingAtIndexPath:(id)arg1 isEditing:(_Bool)arg2 showDeleteButton:(_Bool)arg3 upgradeButton:(_Bool)arg4 editButton:(_Bool)arg5;
- (void)setCardInUsingAtIndexPath:(id)arg1;
- (void)removeCancelSelectingButton;
- (void)removeOldSectionHeaders;
- (void)removeOldCells;
- (void)cleanAffairs;
- (void)addCancelSelectingButton;
- (void)reloadData;
- (double)coverHeightForCurrentDevice;
- (double)coverWidthForCurrentDevice;
- (double)padding;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

