//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AccountGroupSelctionSectionHeaderView, NSMutableArray;

@interface AccountGroupSectionInfo : NSObject
{
    _Bool _open;
    AccountGroupSelctionSectionHeaderView *_headerView;
    NSMutableArray *_rowHeights;
}

@property(retain, nonatomic) NSMutableArray *rowHeights; // @synthesize rowHeights=_rowHeights;
@property(retain, nonatomic) AccountGroupSelctionSectionHeaderView *headerView; // @synthesize headerView=_headerView;
@property(getter=isOpen) _Bool open; // @synthesize open=_open;
- (void).cxx_destruct;
- (void)replaceRowHeightsAtIndexes:(id)arg1 withRowHeights:(id)arg2;
- (void)replaceObjectInRowHeightsAtIndex:(unsigned long long)arg1 withObject:(id)arg2;
- (void)removeRowHeightsAtIndexes:(id)arg1;
- (void)removeObjectFromRowHeightsAtIndex:(unsigned long long)arg1;
- (void)insertRowHeights:(id)arg1 atIndexes:(id)arg2;
- (void)insertObject:(id)arg1 inRowHeightsAtIndex:(unsigned long long)arg2;
- (id)objectInRowHeightsAtIndex:(unsigned long long)arg1;
- (unsigned long long)countOfRowHeights;
- (id)init;

@end

