//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView, UILabel;

@interface AccountBookCarryForwardStepView : UIView
{
    UIImageView *firstStepImageView;
    UIImageView *secondStepImageView;
    UIImageView *thirdStepImageView;
    UIImageView *forthStepImageView;
    UILabel *firstStepLabel;
    UILabel *secondStepLabel;
    UILabel *thirdStepLabel;
    UILabel *forthStepLabel;
    _Bool _needToStopSteping;
    int _currentStep;
}

@property(nonatomic) _Bool needToStopSteping; // @synthesize needToStopSteping=_needToStopSteping;
@property(nonatomic) int currentStep; // @synthesize currentStep=_currentStep;
- (void).cxx_destruct;
- (id)setFinishedImage;
- (id)setProcessImage;
- (id)setStartImage;
- (void)stepOfDescription:(int)arg1;
- (void)showFinishStep;
- (void)showStepsToLast;
- (void)showNextStep;
- (void)showIntialStep;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

