//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AccountBookTemplate, NSDictionary, NSString, UIImage;

@interface AccountBookMarketCellModel : NSObject
{
    NSString *_templateID;
    NSDictionary *_dict;
    AccountBookTemplate *_template;
    UIImage *_coverImage;
    NSString *_name;
    NSString *_simpleMemo;
    NSString *_usedCount;
    unsigned long long _status;
    double _downloadProgress;
    CDUnknownBlockType _modelDidUpdateBlock;
}

+ (id)filteServerDict:(id)arg1;
+ (id)cellModelWithResponceDict:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType modelDidUpdateBlock; // @synthesize modelDidUpdateBlock=_modelDidUpdateBlock;
@property(nonatomic) double downloadProgress; // @synthesize downloadProgress=_downloadProgress;
@property(nonatomic) unsigned long long status; // @synthesize status=_status;
@property(retain, nonatomic) NSString *usedCount; // @synthesize usedCount=_usedCount;
@property(retain, nonatomic) NSString *simpleMemo; // @synthesize simpleMemo=_simpleMemo;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) UIImage *coverImage; // @synthesize coverImage=_coverImage;
@property(retain, nonatomic) AccountBookTemplate *template; // @synthesize template=_template;
@property(retain, nonatomic) NSDictionary *dict; // @synthesize dict=_dict;
@property(retain, nonatomic) NSString *templateID; // @synthesize templateID=_templateID;
- (void).cxx_destruct;
- (void)removeObserver;
- (unsigned long long)statusFromTemplateModel:(id)arg1;
- (double)progressFromTemplateModel:(id)arg1;
- (void)dealloc;
- (id)init;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)matchAndBindExistTemplate;
- (void)bindTemplate:(id)arg1;

@end

