//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface AccountBookMarketDownloadObserver : NSObject
{
    NSMutableArray *_registerObjects;
}

+ (id)sharedObserver;
@property(retain, nonatomic) NSMutableArray *registerObjects; // @synthesize registerObjects=_registerObjects;
- (void).cxx_destruct;
- (id)registerObjectsForTemplateID:(id)arg1;
- (void)templateDidChangedNotification:(id)arg1;
- (void)removeRegisterObject:(id)arg1;
- (void)registerObject:(id)arg1;
- (void)dealloc;
- (id)init;

@end

