//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class FDDownloadView, NSLayoutConstraint, UIImageView, UILabel, UIView;

@interface AccountBookMarketTableViewCell : UITableViewCell
{
    _Bool _lastCell;
    UIImageView *_coverImageView;
    UILabel *_titleLabel;
    UILabel *_tagLabel;
    UILabel *_numberLabel;
    FDDownloadView *_downloadView;
    CDUnknownBlockType _buttonDidClick;
    UIView *_separatorView;
    NSLayoutConstraint *_separatorViewHeightConstraint;
    NSLayoutConstraint *_separatorViewLeadingConstraint;
    NSLayoutConstraint *_numberLabelTopConstraint;
}

+ (id)reusedIdentifier;
+ (void)registerTableViewCell:(id)arg1;
@property(nonatomic) __weak NSLayoutConstraint *numberLabelTopConstraint; // @synthesize numberLabelTopConstraint=_numberLabelTopConstraint;
@property(nonatomic) __weak NSLayoutConstraint *separatorViewLeadingConstraint; // @synthesize separatorViewLeadingConstraint=_separatorViewLeadingConstraint;
@property(nonatomic) __weak NSLayoutConstraint *separatorViewHeightConstraint; // @synthesize separatorViewHeightConstraint=_separatorViewHeightConstraint;
@property(nonatomic) __weak UIView *separatorView; // @synthesize separatorView=_separatorView;
@property(nonatomic) _Bool lastCell; // @synthesize lastCell=_lastCell;
@property(nonatomic) __weak CDUnknownBlockType buttonDidClick; // @synthesize buttonDidClick=_buttonDidClick;
@property(nonatomic) __weak FDDownloadView *downloadView; // @synthesize downloadView=_downloadView;
@property(nonatomic) __weak UILabel *numberLabel; // @synthesize numberLabel=_numberLabel;
@property(nonatomic) __weak UILabel *tagLabel; // @synthesize tagLabel=_tagLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak UIImageView *coverImageView; // @synthesize coverImageView=_coverImageView;
- (void).cxx_destruct;
- (void)setupSeparatorView;
- (void)setupView;
- (void)setupNumberLabel;
- (void)setupTagLabel;
- (void)setupTitleLabel;
- (void)updateConstraints;
- (void)awakeFromNib;
- (void)configureWithCellModel:(id)arg1;

@end

