//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class UIImageView;

@interface AccountBookCoverSelectCollectionViewCell : UICollectionViewCell
{
    _Bool _checked;
    UIImageView *_coverImageView;
    UIImageView *_checkedBackgroundView;
}

+ (id)buttonBackgroundImageWithSize:(struct CGSize)arg1;
@property(nonatomic) __weak UIImageView *checkedBackgroundView; // @synthesize checkedBackgroundView=_checkedBackgroundView;
@property(nonatomic) _Bool checked; // @synthesize checked=_checked;
@property(nonatomic) __weak UIImageView *coverImageView; // @synthesize coverImageView=_coverImageView;
- (void).cxx_destruct;
- (id)checkedBackgroundImage;
- (void)awakeFromNib;

@end

