//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView, UILabel;

@interface AccountBookMarketHistoryNoDataView : UIView
{
    UIImageView *_imageView;
    UILabel *_promptLabel;
    UILabel *_detailPromptLabel;
    UIView *_placeHolderView;
}

+ (_Bool)requiresConstraintBasedLayout;
@property(retain, nonatomic) UIView *placeHolderView; // @synthesize placeHolderView=_placeHolderView;
@property(retain, nonatomic) UILabel *detailPromptLabel; // @synthesize detailPromptLabel=_detailPromptLabel;
@property(retain, nonatomic) UILabel *promptLabel; // @synthesize promptLabel=_promptLabel;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)commonInit;
- (void)updateConstraints;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

