//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AccountBookCardView, AccountBookVo, NSIndexPath;

@protocol AccountBookCardViewDataSource <NSObject>
- (long long)cardView:(AccountBookCardView *)arg1 numberOfCardsInSection:(long long)arg2;
- (AccountBookVo *)cardView:(AccountBookCardView *)arg1 modelAtIndexPath:(NSIndexPath *)arg2;

@optional
- (_Bool)cardView:(AccountBookCardView *)arg1 needShowRedDotAtIndexPath:(NSIndexPath *)arg2;
- (int)cardView:(AccountBookCardView *)arg1 buttonStatusOnCoverAtIndexPath:(NSIndexPath *)arg2;
- (_Bool)cardView:(AccountBookCardView *)arg1 needAdditionalCellInSection:(long long)arg2;
- (long long)numberOfSectionsInCardView:(AccountBookCardView *)arg1;
@end

