//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "FDTencentOpenAPIAuthManagerDelegate.h"
#import "FDWeChatAPIManagerDelegate.h"
#import "FDWeiboAuthManagerDelegate.h"
#import "MFMessageComposeViewControllerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WriteNewPostControllerDelegate.h"

@class AccountBookVo, NSArray, NSDecimalNumber, NSDictionary, NSString, RemoteAccountService, SyncCenterUI, UIImage, UIScrollView, UITableView;

@interface AccountBookSharingViewController : UIViewController <MFMessageComposeViewControllerDelegate, FDWeChatAPIManagerDelegate, FDTencentOpenAPIAuthManagerDelegate, FDWeiboAuthManagerDelegate, UITableViewDataSource, UITableViewDelegate, WriteNewPostControllerDelegate>
{
    _Bool _disableSyncCheck;
    _Bool _hasFinishSync;
    _Bool _hasShared;
    NSString *_filterType;
    NSDictionary *_filters;
    double _presentingInfoStartTime;
    double _presentingInfoEndTime;
    NSString *_customShareTitle;
    NSString *_customShareDescription;
    AccountBookVo *_currentAccountBookVo;
    AccountBookVo *_sharingAccountBookVo;
    RemoteAccountService *_remoteAccountService;
    NSString *_invitationCode;
    NSString *_sharedURL;
    NSString *_shortSharedURL;
    NSString *_accountBookSeedURL;
    NSString *_decryptKey;
    UIImage *_screenShotImage;
    NSString *_systemCurrencyCode;
    NSDecimalNumber *_totalAmount;
    NSString *_totalPayout;
    unsigned long long _transactionsCount;
    SyncCenterUI *_syncCenterUI;
    UIScrollView *_scrollView;
    UITableView *_channelTableView;
    NSString *_postTitle;
    NSString *_postContent;
    NSArray *_postImageIds;
    NSString *_boradType;
}

+ (id)renderScrollViewToImage:(id)arg1;
@property(retain, nonatomic) NSString *boradType; // @synthesize boradType=_boradType;
@property(retain, nonatomic) NSArray *postImageIds; // @synthesize postImageIds=_postImageIds;
@property(retain, nonatomic) NSString *postContent; // @synthesize postContent=_postContent;
@property(retain, nonatomic) NSString *postTitle; // @synthesize postTitle=_postTitle;
@property(retain, nonatomic) UITableView *channelTableView; // @synthesize channelTableView=_channelTableView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) SyncCenterUI *syncCenterUI; // @synthesize syncCenterUI=_syncCenterUI;
@property(nonatomic) unsigned long long transactionsCount; // @synthesize transactionsCount=_transactionsCount;
@property(retain, nonatomic) NSString *totalPayout; // @synthesize totalPayout=_totalPayout;
@property(retain, nonatomic) NSDecimalNumber *totalAmount; // @synthesize totalAmount=_totalAmount;
@property(retain, nonatomic) NSString *systemCurrencyCode; // @synthesize systemCurrencyCode=_systemCurrencyCode;
@property(retain, nonatomic) UIImage *screenShotImage; // @synthesize screenShotImage=_screenShotImage;
@property(retain, nonatomic) NSString *decryptKey; // @synthesize decryptKey=_decryptKey;
@property(retain, nonatomic) NSString *accountBookSeedURL; // @synthesize accountBookSeedURL=_accountBookSeedURL;
@property(retain, nonatomic) NSString *shortSharedURL; // @synthesize shortSharedURL=_shortSharedURL;
@property(retain, nonatomic) NSString *sharedURL; // @synthesize sharedURL=_sharedURL;
@property(retain, nonatomic) NSString *invitationCode; // @synthesize invitationCode=_invitationCode;
@property(nonatomic) _Bool hasShared; // @synthesize hasShared=_hasShared;
@property(nonatomic) _Bool hasFinishSync; // @synthesize hasFinishSync=_hasFinishSync;
@property(retain, nonatomic) RemoteAccountService *remoteAccountService; // @synthesize remoteAccountService=_remoteAccountService;
@property(retain, nonatomic) AccountBookVo *sharingAccountBookVo; // @synthesize sharingAccountBookVo=_sharingAccountBookVo;
@property(retain, nonatomic) AccountBookVo *currentAccountBookVo; // @synthesize currentAccountBookVo=_currentAccountBookVo;
@property(retain, nonatomic) NSString *customShareDescription; // @synthesize customShareDescription=_customShareDescription;
@property(retain, nonatomic) NSString *customShareTitle; // @synthesize customShareTitle=_customShareTitle;
@property(nonatomic) _Bool disableSyncCheck; // @synthesize disableSyncCheck=_disableSyncCheck;
@property(nonatomic) double presentingInfoEndTime; // @synthesize presentingInfoEndTime=_presentingInfoEndTime;
@property(nonatomic) double presentingInfoStartTime; // @synthesize presentingInfoStartTime=_presentingInfoStartTime;
@property(retain, nonatomic) NSDictionary *filters; // @synthesize filters=_filters;
@property(retain, nonatomic) NSString *filterType; // @synthesize filterType=_filterType;
- (void).cxx_destruct;
- (void)weiboAuthManager:(id)arg1 didReceviedShareResponseWithErrorMessage:(id)arg2;
- (void)weiboAuthManagerDidReceviedShareResponseSuccessfully:(id)arg1;
- (void)authManager:(id)arg1 didReceivedShareResponseUnSuccessfullyWithErrorMessage:(id)arg2;
- (void)authManagerDidReceivedShareResponseSuccessfully:(id)arg1;
- (void)weChatAPIManager:(id)arg1 didRecivedShareResponseUnsuccessfullyWithErrorMessage:(id)arg2;
- (void)weChatAPIManagerDidRecivedShareResponseSuccessfully:(id)arg1;
- (void)messageComposeViewController:(id)arg1 didFinishWithResult:(int)arg2;
- (id)descriptionText;
- (void)uploadSharingImage:(id)arg1 withShareCode:(id)arg2;
- (void)syncAction:(CDUnknownBlockType)arg1;
- (void)sendStaticRequestWithChannelType:(unsigned long long)arg1;
- (void)showAlertWithMessage:(id)arg1;
- (void)shareToForum:(id)arg1;
- (id)timespanTransShareDescription;
- (id)timespanTransShareTitle;
- (_Bool)isTimespanTransFilterType;
- (void)writeNewPostController:(id)arg1 sendTopicWithTitle:(id)arg2 content:(id)arg3 tag:(id)arg4 imageIDs:(id)arg5;
- (void)pushToCompositePostController;
- (void)shareViaSMS:(id)arg1;
- (void)shareToWeibo:(id)arg1;
- (void)shareToQQ:(id)arg1;
- (void)shareToQzone:(id)arg1;
- (void)shareToWeChatCircleWithShareURL:(id)arg1;
- (void)shareToWeChatFriendsWithShareURL:(id)arg1;
- (_Bool)tryInstallWeibo;
- (_Bool)tryInstallShareWeChat;
- (_Bool)isSupportSMS;
- (void)updateRemoteAccountBookWithAccountBook:(id)arg1 everSharedToSubsriber:(_Bool)arg2;
- (void)showToChannel:(unsigned long long)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (_Bool)needSync;
- (void)reloadData;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;
- (id)initWithSharingAccountBookVo:(id)arg1;
- (id)initWithCurrentAccountBook;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

