//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class AccountBookMarketHistoryNoDataView, AccountBookMarketHistoryStore, NSString, NoNetworkCoverView, UITableView;

@interface AccountBookMarketHistoryViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
{
    UITableView *_tableView;
    NoNetworkCoverView *_noNetworkCoverView;
    AccountBookMarketHistoryNoDataView *_noDataView;
    AccountBookMarketHistoryStore *_store;
}

@property(retain, nonatomic) AccountBookMarketHistoryStore *store; // @synthesize store=_store;
@property(retain, nonatomic) AccountBookMarketHistoryNoDataView *noDataView; // @synthesize noDataView=_noDataView;
@property(retain, nonatomic) NoNetworkCoverView *noNetworkCoverView; // @synthesize noNetworkCoverView=_noNetworkCoverView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)pushToAccountBookCreateViewControllerWithTemplate:(id)arg1;
- (void)showAccountBookDetailViewControllerWithTemplateID:(id)arg1;
- (void)cellViewModelDidUpdate:(id)arg1;
- (void)downloadTemplateAtIndexPath:(id)arg1;
- (id)indexPathForModel:(id)arg1;
- (id)cellViewModelAtIndexPath:(id)arg1;
- (void)reloadData;
- (void)reloadButtonAction:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

