//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AccountBookTemplate, AccountBookTemplateProgressDescription, NSDictionary, NSString;

@interface AccountBookTemplateDownloader : NSObject
{
    NSDictionary *_templateFileProgressConfiguration;
    AccountBookTemplate *_template;
    NSString *_targetDirPath;
    CDUnknownBlockType _completionHandler;
    AccountBookTemplateProgressDescription *_progressDescription;
}

+ (id)templateFileProgressConfiguration;
@property(retain, nonatomic) AccountBookTemplateProgressDescription *progressDescription; // @synthesize progressDescription=_progressDescription;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(retain, nonatomic) NSString *targetDirPath; // @synthesize targetDirPath=_targetDirPath;
@property(retain, nonatomic) AccountBookTemplate *template; // @synthesize template=_template;
@property(retain, nonatomic) NSDictionary *templateFileProgressConfiguration; // @synthesize templateFileProgressConfiguration=_templateFileProgressConfiguration;
- (void).cxx_destruct;
- (void)updateProgressForDownloadResource:(id)arg1 template:(id)arg2;
- (void)updateProgressForDownloadDatabase:(id)arg1 withCurrentProgress:(id)arg2 template:(id)arg3;
- (double)downloadProgressWithFileInfo:(id)arg1 seed:(id)arg2;
- (void)updateProgressForAccountBookInfoStage:(id)arg1 withTemplate:(id)arg2;
- (void)updateProgressForAccountBookURLStage:(id)arg1 withTemplate:(id)arg2;
- (void)removeTmpFilesForPath:(id)arg1;
- (_Bool)cleanTargetDirPath:(id)arg1;
- (_Bool)configTargetDirPath:(id)arg1;
- (id)downloaderWithInfo:(id)arg1 decryptKey:(id)arg2 targetDirPath:(id)arg3;
- (void)downloadTemplateFilesWithTemplate:(id)arg1 toTargetDirPath:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)importResource:(id)arg1;
- (void)downloadAccountBookResourceWithSeed:(id)arg1;
- (void)downloadAccountBookDatabaseWithAccountBookInfo:(id)arg1 decryptKey:(id)arg2;
- (void)fetchAccountBookInfoWithAccountBookString:(id)arg1 decryptKey:(id)arg2;
- (void)fetchAccountBookURLAndDecryptKey;

@end

