//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class FDSettingCellContentView, NSString;

@interface AccountBookPanelSelectCollectionViewCell : UICollectionViewCell
{
    NSString *_title;
    NSString *_subTitle;
    unsigned long long _seperatorLineType;
    FDSettingCellContentView *_settingCellContentView;
}

@property(nonatomic) __weak FDSettingCellContentView *settingCellContentView; // @synthesize settingCellContentView=_settingCellContentView;
@property(nonatomic) unsigned long long seperatorLineType; // @synthesize seperatorLineType=_seperatorLineType;
@property(nonatomic) __weak NSString *subTitle; // @synthesize subTitle=_subTitle;
@property(nonatomic) __weak NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;

@end

