//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseDao.h"

#import "ACLLinkUserRoleDao.h"

@class NSString;

@interface ACLLinkUserRoleDaoImpl : BaseDao <ACLLinkUserRoleDao>
{
}

- (id)linkUserRolesMatchingPredicate:(id)arg1;
- (long long)addLinkUserRole:(id)arg1 toTable:(id)arg2;
- (void)sqlite3Statement:(struct sqlite3_stmt *)arg1 bindLinkUserRole:(id)arg2;
- (id)linkUserRoleForSqlStatement:(struct sqlite3_stmt *)arg1;
- (_Bool)updateLinkUserRole:(id)arg1;
- (_Bool)removeLinkUserRoleById:(long long)arg1;
- (long long)addLinkUserRole:(id)arg1;
- (id)linkUserRoleByFID:(long long)arg1;
- (id)linkUserRolesByRoleUniqueName:(id)arg1;
- (id)linkUserRolesByUid:(id)arg1;
- (id)linkUserRoles;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

