//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AllTransactionLoader : NSObject
{
    unsigned long long _pageSize;
    unsigned long long _currentOffset;
    double _endTimeIntervalOfDay;
}

@property(nonatomic) double endTimeIntervalOfDay; // @synthesize endTimeIntervalOfDay=_endTimeIntervalOfDay;
@property(nonatomic) unsigned long long currentOffset; // @synthesize currentOffset=_currentOffset;
@property(nonatomic) unsigned long long pageSize; // @synthesize pageSize=_pageSize;
- (id)loadTransactionsWithOffset:(unsigned long long)arg1 limit:(unsigned long long)arg2;
- (id)loadOneTransactionNotChangeOffset;
- (id)loadPastTransactionPage;
- (id)loadTodayTransaction;
- (void)resetLoader;
- (id)initWithPageSize:(unsigned long long)arg1 limitDay:(double)arg2;

@end

