//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class NSArray;

@interface AutoChangeStateButton : UIButton
{
    NSArray *_textFields;
}

@property(retain, nonatomic) NSArray *textFields; // @synthesize textFields=_textFields;
- (void).cxx_destruct;
- (void)dealloc;
- (void)setObserveredTextFields:(id)arg1;
- (void)setButtonState;
- (void)textFieldTextDidChangeNotification:(id)arg1;
- (void)commonInit;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

