//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDPOISearchProvider.h"

@interface BaiduMapWebPOISearchProvider : FDPOISearchProvider
{
}

- (void)handleGeocodingResponse:(id)arg1;
- (void)handleResponse:(id)arg1;
- (void)startUpdateAddressesForCoordinate:(CDStruct_2c43369c)arg1;
- (void)startUpdatePOIsForCoordinate:(CDStruct_2c43369c)arg1;

@end

