//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIColor;

@interface BarChartSecondLevelCategoryCellViewModel : NSObject
{
    _Bool _showFullSeparator;
    NSString *_name;
    NSString *_amountText;
    UIColor *_barColor;
    UIColor *_amountTextColor;
    NSString *_percentageText;
    double _barWidth;
}

@property(nonatomic) _Bool showFullSeparator; // @synthesize showFullSeparator=_showFullSeparator;
@property(nonatomic) double barWidth; // @synthesize barWidth=_barWidth;
@property(retain, nonatomic) NSString *percentageText; // @synthesize percentageText=_percentageText;
@property(retain, nonatomic) UIColor *amountTextColor; // @synthesize amountTextColor=_amountTextColor;
@property(retain, nonatomic) UIColor *barColor; // @synthesize barColor=_barColor;
@property(retain, nonatomic) NSString *amountText; // @synthesize amountText=_amountText;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;

@end

