//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CategoryVo, NSMutableArray, NSNumber;

@interface BarChartCategoryModel : NSObject
{
    CategoryVo *_info;
    NSMutableArray *_reportEntrys;
    NSNumber *_total;
}

@property(retain, nonatomic) NSNumber *total; // @synthesize total=_total;
@property(retain, nonatomic) NSMutableArray *reportEntrys; // @synthesize reportEntrys=_reportEntrys;
@property(retain, nonatomic) CategoryVo *info; // @synthesize info=_info;
- (void).cxx_destruct;
- (void)sortEntrys;
- (id)calculateTotal;
- (id)init;

@end

