//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSIndexPath;

@protocol BarChartDefaultDatasourceProtocol <NSObject>
- (_Bool)barChartDefaultCellShouldRouteToNavExpense;
- (NSArray *)barChartDefaultCellViewModels;
- (void)fetchReportEntryVoAtIndexPathThenRouteToAccountDetail:(NSIndexPath *)arg1;
- (void)fetchReportEntryVoAtIndexPathThenRouteToDetail:(NSIndexPath *)arg1;
@end

