//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseTableViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSString, SettingViewController, SyncCenterUI;

@interface BaseTabSettingViewController : BaseTableViewController <UITableViewDelegate, UITableViewDataSource>
{
    SettingViewController *_settingViewController;
    SyncCenterUI *_syncCenterUI;
}

+ (_Bool)showFunctionLimitInDemoModeIfNeeded;
@property(retain, nonatomic) SyncCenterUI *syncCenterUI; // @synthesize syncCenterUI=_syncCenterUI;
@property(nonatomic) __weak SettingViewController *settingViewController; // @synthesize settingViewController=_settingViewController;
- (void).cxx_destruct;
- (void)syncDidFinished;
- (void)syncAction;
- (_Bool)hasSync;
- (_Bool)canOpenScheme:(id)arg1;
- (_Bool)canOpenProVersion;
- (void)reloadViewControllerData;
- (void)loadView;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

