//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BaseDao : NSObject
{
    struct sqlite3 *database;
}

- (id)charToNSString:(const char *)arg1;
- (_Bool)updateLastUpdateTimeOnTable:(id)arg1 wherePrimaryColumn:(id)arg2 equals:(long long)arg3;
- (const char *)charAppendChar:(const char *)arg1 appendChar:(char *)arg2;
- (long long)deleteRowsFromTable:(id)arg1 whereColumn:(id)arg2 equalTo:(long long)arg3;
- (_Bool)deleteTableValueWithTableName:(id)arg1 whereClause:(id)arg2;
- (_Bool)deleteTableValue:(id)arg1 columnName:(id)arg2 columnID:(long long)arg3;
- (long long)nextIdForTable:(id)arg1;
- (id)nextIdsForTable:(id)arg1 idsCount:(unsigned long long)arg2;
- (id)initWithDatabase:(struct sqlite3 *)arg1;

@end

