//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "AccountGroupSelectionControllerDelegate.h"
#import "AddExpenseSearchViewControllerDelegate.h"
#import "AddingAccountViewControllerDelegate.h"
#import "CorporationInputButtonDelegate.h"
#import "DateInputButtonDelegate.h"
#import "EditingCorporationControllerDelegate.h"
#import "EditingMemberControllerDelegate.h"
#import "EditingProjectControllerDelegate.h"
#import "MemberInputButtonDelegate.h"
#import "MemoInputTextViewDelegate.h"
#import "PhotoInputButtonDelegate.h"
#import "ProjectInputButtonDelegate.h"
#import "TransferBottomBarViewDelegate.h"

@class CorporationInputButton, DateInputButton, ExpenseVo, FlatMoneyInputButton, MemberInputButton, MemoInputTextView, NSMutableArray, NSString, PhotoInputButton, ProjectInputButton, TransferBottomBarView, UIResponder;

@interface BaseSaveRecordViewController : UIViewController <PhotoInputButtonDelegate, AccountGroupSelectionControllerDelegate, DateInputButtonDelegate, MemberInputButtonDelegate, ProjectInputButtonDelegate, CorporationInputButtonDelegate, AddingAccountViewControllerDelegate, TransferBottomBarViewDelegate, AddExpenseSearchViewControllerDelegate, EditingCorporationControllerDelegate, EditingMemberControllerDelegate, EditingProjectControllerDelegate, MemoInputTextViewDelegate>
{
    _Bool _isEditing;
    ExpenseVo *_expenseVo;
    ExpenseVo *_oldExpenseVo;
    PhotoInputButton *_photoInputButton;
    DateInputButton *_dateInputButton;
    MemberInputButton *_memberInputButton;
    ProjectInputButton *_projectInputButton;
    CorporationInputButton *_corporationInputButton;
    MemoInputTextView *_memoInputTextView;
    _Bool _suppressFirstResponderWhenViewDidAppear;
    UIResponder *_viewBecomeFirstResponderAtOnceWhenViewDidAppear;
    UIResponder *_preferredFirstResponderWhenViewDidAppear;
    long long _templateId;
    long long _addingAccountTransferType;
    _Bool _enableSecuredInputMode;
    UIResponder *_firstResponderAtOnceWhenViewDidAppear;
    _Bool _hasShowedViewAtPresentViewController;
    _Bool _isSupportedAccount;
    _Bool _shouldPopToRootViewController;
    _Bool _saveRecoredMethodCalled;
    _Bool _hasShowDate;
    _Bool _hasShowMember;
    _Bool _hasShowCorporation;
    _Bool _hasShowProject;
    _Bool _shouldNotTriggerFirstResponderIfSecurityLocked;
    FlatMoneyInputButton *_flatMoneyInputButton;
    TransferBottomBarView *_bottomBarView;
    id <BaseSaveRecordViewControllerDelegate> _delegate;
    NSMutableArray *_buttonArray;
}

+ (double)defaultButtonHeight;
@property(retain, nonatomic) NSMutableArray *buttonArray; // @synthesize buttonArray=_buttonArray;
@property(nonatomic) __weak id <BaseSaveRecordViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool shouldNotTriggerFirstResponderIfSecurityLocked; // @synthesize shouldNotTriggerFirstResponderIfSecurityLocked=_shouldNotTriggerFirstResponderIfSecurityLocked;
@property(nonatomic) _Bool hasShowProject; // @synthesize hasShowProject=_hasShowProject;
@property(nonatomic) _Bool hasShowCorporation; // @synthesize hasShowCorporation=_hasShowCorporation;
@property(nonatomic) _Bool hasShowMember; // @synthesize hasShowMember=_hasShowMember;
@property(nonatomic) _Bool hasShowDate; // @synthesize hasShowDate=_hasShowDate;
@property(nonatomic) _Bool saveRecoredMethodCalled; // @synthesize saveRecoredMethodCalled=_saveRecoredMethodCalled;
@property(nonatomic) long long addingAccountTransferType; // @synthesize addingAccountTransferType=_addingAccountTransferType;
@property(nonatomic) long long templateId; // @synthesize templateId=_templateId;
@property(retain, nonatomic) TransferBottomBarView *bottomBarView; // @synthesize bottomBarView=_bottomBarView;
@property(retain, nonatomic) MemoInputTextView *memoInputTextView; // @synthesize memoInputTextView=_memoInputTextView;
@property(retain, nonatomic) CorporationInputButton *corporationInputButton; // @synthesize corporationInputButton=_corporationInputButton;
@property(retain, nonatomic) ProjectInputButton *projectInputButton; // @synthesize projectInputButton=_projectInputButton;
@property(retain, nonatomic) MemberInputButton *memberInputButton; // @synthesize memberInputButton=_memberInputButton;
@property(retain, nonatomic) DateInputButton *dateInputButton; // @synthesize dateInputButton=_dateInputButton;
@property(retain, nonatomic) PhotoInputButton *photoInputButton; // @synthesize photoInputButton=_photoInputButton;
@property(retain, nonatomic) FlatMoneyInputButton *flatMoneyInputButton; // @synthesize flatMoneyInputButton=_flatMoneyInputButton;
@property(retain, nonatomic) UIResponder *preferredFirstResponderWhenViewDidAppear; // @synthesize preferredFirstResponderWhenViewDidAppear=_preferredFirstResponderWhenViewDidAppear;
@property(retain, nonatomic) UIResponder *viewBecomeFirstResponderAtOnceWhenViewDidAppear; // @synthesize viewBecomeFirstResponderAtOnceWhenViewDidAppear=_viewBecomeFirstResponderAtOnceWhenViewDidAppear;
@property(nonatomic) _Bool suppressFirstResponderWhenViewDidAppear; // @synthesize suppressFirstResponderWhenViewDidAppear=_suppressFirstResponderWhenViewDidAppear;
@property(nonatomic) _Bool shouldPopToRootViewController; // @synthesize shouldPopToRootViewController=_shouldPopToRootViewController;
@property(retain, nonatomic) ExpenseVo *oldExpenseVo; // @synthesize oldExpenseVo=_oldExpenseVo;
@property(retain, nonatomic) ExpenseVo *expenseVo; // @synthesize expenseVo=_expenseVo;
@property(nonatomic) _Bool isSupportedAccount; // @synthesize isSupportedAccount=_isSupportedAccount;
@property(nonatomic) _Bool enableSecuredInputMode; // @synthesize enableSecuredInputMode=_enableSecuredInputMode;
- (void).cxx_destruct;
- (void)modifyCurrentFirstResponderBy:(id)arg1;
- (void)searchAccount;
- (void)addAccountWithAccountGroupVo:(long long)arg1;
- (void)accountDidFinishWithAccountFromSearch:(id)arg1;
- (void)accountDidFinishWithAccount:(id)arg1;
- (void)addAnyAccount;
- (void)addAssetAccount;
- (void)addCreditAccount;
- (void)addLiabilityAccount;
- (id)removePrefixAndSurfixSpaceString:(id)arg1;
- (void)addAccountViewController:(id)arg1 didFinishWithSave:(_Bool)arg2;
- (void)alertTemplateHaveBeenActivatedWithFormattedCost:(id)arg1 pop:(_Bool)arg2;
- (void)increaseRateMeCounter;
- (void)addExperienceIfAvailable;
- (void)pop;
- (void)popViewControllerAfterSaved;
- (void)deleteCurrentExpenseVo;
- (void)deleteExpenseVoIfEditting;
- (void)changeToTransferAction;
- (void)saveAndNewRecordAction;
- (void)saveAsTemplateAction;
- (void)deleteAction;
- (void)saveRecordAction;
- (void)saveRecordActionWithoutLog;
- (void)rightBarButtonItemAction;
- (void)refreshButtonsWithOffset:(double)arg1;
- (double)removeButtons;
- (void)setupDeleteSaveButtonsBelowOffsetY:(double)arg1;
- (void)setupSaveAndNewRecordButtonBelowOffsetY:(double)arg1;
- (void)setupSaveButtonBelowOffsetY:(double)arg1;
- (void)setupButtonsForAddingBelowOffsetY:(double)arg1;
- (id)separatorLineViewAtPoint:(struct CGPoint)arg1 width:(double)arg2;
- (id)createBottomBarViewWithFrame:(struct CGRect)arg1;
- (id)newMemoInputTextViewWithFrame:(struct CGRect)arg1;
- (id)memoLabelAtCenter:(struct CGPoint)arg1;
- (id)newCorporationInputButtonWithFrame:(struct CGRect)arg1;
- (id)newProjectInputButtonWithFrame:(struct CGRect)arg1;
- (id)newMemberInputButtonWithFrame:(struct CGRect)arg1;
- (id)newDateInputButtonWithFrame:(struct CGRect)arg1;
- (id)newPhotoInputButton;
- (void)updateContent;
- (double)defaultBottomButtonHeight;
- (void)setMemoString:(id)arg1;
- (void)setMoneyValue:(id)arg1;
- (id)findFirstResponderInView:(id)arg1;
- (id)currentFirstResponder;
- (void)replaceAddingExpenseVo:(id)arg1;
- (void)resetScrollViewContentOffsetAndContentInsets;
- (void)resetScrollView;
- (void)keyboardWillHidden:(id)arg1;
- (void)keyboardWasShown:(id)arg1;
- (void)unregisterForKeyboardNotifications;
- (void)registerForKeyboardNotifications;
- (void)endEditingText:(id)arg1;
- (void)memoInputTextView:(id)arg1 didChange:(id)arg2;
- (void)editingCorporationController:(id)arg1 didSaveCorporationVoWithId:(long long)arg2;
- (void)addCorporation;
- (void)searchCorporation;
- (void)editCorporation;
- (void)selectedCorporation:(id)arg1;
- (id)currentCorporation;
- (void)editingProjectController:(id)arg1 didSaveProjectVoWithId:(long long)arg2;
- (void)searchProject;
- (void)editProject;
- (void)addProject;
- (void)selectedProject:(id)arg1;
- (id)currentProject;
- (void)editingMemberController:(id)arg1 didSaveMemberVoWithId:(long long)arg2;
- (void)isSelectedFromSearchPageWithType:(long long)arg1;
- (void)searchMember;
- (void)editMember;
- (void)addMember;
- (void)selectedMember:(id)arg1;
- (id)currentMember;
- (void)selectedDate:(id)arg1;
- (id)currentDate;
- (void)photoInputButtonDeleteImage;
- (void)photoInputButton:(id)arg1 selectedImage:(id)arg2;
- (void)handlePhotoInputButtonClicked:(id)arg1;
- (_Bool)setDefaultShowingBottomBarInfo:(id)arg1;
- (id)defaultShowingBottomBarInfo;
- (id)kSaveRecordViewControllerShowingBottomBarInfo;
- (id)kShowingBottomBarInfo;
- (_Bool)saveBottomBarStatus;
- (void)initBottomBarStatus;
- (void)reloadData;
- (_Bool)resignFirstResponderIfNeeded;
- (void)showFirstResponderView;
- (void)ProcessCurrentScrollViewContentFromSearch;
- (void)ProcessCurrentScrollViewContent;
- (void)dealloc;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

