//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSDate, NSTimer, UIImageView;

@interface BatteryView : UIView
{
    UIImageView *_overlayImageView;
    UIImageView *_backgroundImageView;
    UIImageView *_lowImageView;
    UIImageView *_normalImageView;
    UIImageView *_gradientImageView;
    _Bool _isAnimating;
    double _animatingHeight;
    double _animationStartValue;
    double _animationDeltaValue;
    _Bool _isEmpty;
    float _percentage;
    id <BatteryViewDelegate> _delegate;
    NSDate *_animationStartDate;
    NSTimer *_animationTimer;
}

@property(retain, nonatomic) NSTimer *animationTimer; // @synthesize animationTimer=_animationTimer;
@property(retain, nonatomic) NSDate *animationStartDate; // @synthesize animationStartDate=_animationStartDate;
@property(nonatomic) _Bool isEmpty; // @synthesize isEmpty=_isEmpty;
@property(nonatomic) float percentage; // @synthesize percentage=_percentage;
@property(nonatomic) __weak id <BatteryViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)colorWithStartColor:(id)arg1 endColor:(id)arg2 percent:(double)arg3;
- (id)gradientImageWithStartColor:(id)arg1 endColor:(id)arg2 shadowColor:(id)arg3 size:(struct CGSize)arg4;
- (id)gradientImageWithHeight:(double)arg1;
- (void)timerAction:(id)arg1;
- (void)setPercentage:(float)arg1 animated:(_Bool)arg2;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

