//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "BudgetItemCategorySelectionViewControllerDelegate.h"
#import "BudgetKeyBoardViewDelegate.h"
#import "FloatBackgroundWallViewDelegate.h"
#import "ScoreBoardLabelDelegate.h"
#import "SubBudgetViewControllerDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class BudgetKeyboardView, FDDropdownMenuBehavior, FDDropdownMenuController, FDFlipIconButton, FlatNavHeaderView, FloatBackgroundHeaderView, FloatBackgroundWallView, NSDate, NSMutableArray, NSString, UIButton, UILabel, UITableView;

@interface BudgetViewController : UIViewController <FloatBackgroundWallViewDelegate, UITableViewDelegate, UITableViewDataSource, BudgetItemCategorySelectionViewControllerDelegate, BudgetKeyBoardViewDelegate, SubBudgetViewControllerDelegate, UIAlertViewDelegate, ScoreBoardLabelDelegate>
{
    UITableView *_tableView;
    NSMutableArray *_budgetItems;
    NSString *_systemCurrencyCode;
    BudgetKeyboardView *_keyboardView;
    double maxBudgetAmount;
    UIButton *_editButton;
    UIButton *_fakeEditButton;
    FlatNavHeaderView *_headerView;
    UILabel *_headerLabel;
    FloatBackgroundWallView *_wallView;
    FloatBackgroundHeaderView *_tableHeaderView;
    FDFlipIconButton *_menuButton;
    FDDropdownMenuBehavior *_dropdownMenuBehavior;
    FDDropdownMenuController *_dropdownMenuController;
    NSDate *_eventStartDate;
    NSDate *_eventEndDate;
    unsigned long long _recurrenceType;
    long long _currentCollectorIndex;
}

@property(nonatomic) long long currentCollectorIndex; // @synthesize currentCollectorIndex=_currentCollectorIndex;
@property(nonatomic) unsigned long long recurrenceType; // @synthesize recurrenceType=_recurrenceType;
@property(retain, nonatomic) NSDate *eventEndDate; // @synthesize eventEndDate=_eventEndDate;
@property(retain, nonatomic) NSDate *eventStartDate; // @synthesize eventStartDate=_eventStartDate;
@property(retain, nonatomic) FDDropdownMenuController *dropdownMenuController; // @synthesize dropdownMenuController=_dropdownMenuController;
@property(retain, nonatomic) FDDropdownMenuBehavior *dropdownMenuBehavior; // @synthesize dropdownMenuBehavior=_dropdownMenuBehavior;
@property(retain, nonatomic) FDFlipIconButton *menuButton; // @synthesize menuButton=_menuButton;
@property(retain, nonatomic) FloatBackgroundHeaderView *tableHeaderView; // @synthesize tableHeaderView=_tableHeaderView;
@property(retain, nonatomic) FloatBackgroundWallView *wallView; // @synthesize wallView=_wallView;
@property(retain, nonatomic) UILabel *headerLabel; // @synthesize headerLabel=_headerLabel;
@property(retain, nonatomic) FlatNavHeaderView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) NSString *systemCurrencyCode; // @synthesize systemCurrencyCode=_systemCurrencyCode;
@property(retain, nonatomic) NSMutableArray *budgetItems; // @synthesize budgetItems=_budgetItems;
@property(retain, nonatomic) BudgetKeyboardView *keyboardView; // @synthesize keyboardView=_keyboardView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)refreshRightBarItemHiddenStatus;
- (_Bool)isEmptyWithSecondLevelBudget;
- (id)generationForIndexPathCanEdit;
- (void)needSetNavigationBarBackground:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)subBudegetViewController:(id)arg1 updateFirstLevelBudget:(id)arg2;
- (void)pushSubBudgetViewControllerWithBudgetName:(id)arg1 sourceKey:(id)arg2 onNavigationController:(id)arg3;
- (void)updateTotalAmountBudgetItemWith:(id)arg1;
- (void)setTotalBudget:(id)arg1;
- (void)keyBoardView:(id)arg1 inputValue:(id)arg2;
- (void)addCategoryViewController:(id)arg1;
- (void)resetBudgetEvent:(id)arg1;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)dealloc;
- (void)viewDidUnload;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)showKeyboard:(id)arg1;
- (void)refreshBudgetAction:(id)arg1;
- (void)scoreBoardAnimationDidEnd;
- (struct CGRect)editButtonFrame;
- (void)refreshHeaderView;
- (void)viewDidLoad;
- (void)handleMenuButtonClicked:(id)arg1;
- (unsigned long long)setSelectedRecurrenceType:(long long)arg1;
- (void)setupTopContextMenu;
- (void)loadView;
- (void)loadBudgetItemDataWithEventType:(unsigned long long)arg1;
- (void)setBudgetDateWithRecurrenceType:(unsigned long long)arg1;
- (void)setMaxBudgetAmount;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

