//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class NSTimer, TTTAttributedLabel, UIImageView, UIView;

@interface BudgetBarView : UIButton
{
    double _budgetAmount;
    double _expenseAmount;
    float _percent;
    TTTAttributedLabel *_budgetTitleLabel;
    TTTAttributedLabel *_balanceTitleLabel;
    UIImageView *_progressImageView;
    UIView *_progressBackgroundView;
    UIImageView *_indicatorImageView;
    NSTimer *_timer;
    UIView *_separatorLine;
}

+ (id)budgetStringWithAmount:(double)arg1 isHighlighted:(_Bool)arg2;
+ (id)balanceStringWithAmount:(double)arg1 isHighlighted:(_Bool)arg2 hasBudget:(_Bool)arg3;
@property(retain, nonatomic) UIView *separatorLine; // @synthesize separatorLine=_separatorLine;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) UIImageView *indicatorImageView; // @synthesize indicatorImageView=_indicatorImageView;
@property(retain, nonatomic) UIView *progressBackgroundView; // @synthesize progressBackgroundView=_progressBackgroundView;
@property(retain, nonatomic) UIImageView *progressImageView; // @synthesize progressImageView=_progressImageView;
@property(retain, nonatomic) TTTAttributedLabel *balanceTitleLabel; // @synthesize balanceTitleLabel=_balanceTitleLabel;
@property(retain, nonatomic) TTTAttributedLabel *budgetTitleLabel; // @synthesize budgetTitleLabel=_budgetTitleLabel;
- (void).cxx_destruct;
- (void)highlighted:(_Bool)arg1;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)timerAction:(id)arg1;
- (void)displaySettingBudgetMessage:(_Bool)arg1;
- (void)animateBudget:(double)arg1 expense:(double)arg2;
- (void)setBudget:(double)arg1 expense:(double)arg2;
- (void)layoutSubviews;
- (void)dealloc;
- (id)init;

@end

