//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableString, NSString;

@interface Calculator : NSObject
{
    NSMutableString *_display;
    double _operand;
    NSString *_operator;
    _Bool _isNegativeInput;
    _Bool _enableNegativeInput;
    long long _decimalLength;
}

- (void).cxx_destruct;
- (void)clear;
- (id)displayValue;
- (void)input:(id)arg1;
- (void)enableNegativeInput:(_Bool)arg1;
- (_Bool)isNegativeInput;
- (_Bool)isEqauls:(id)arg1;
- (_Bool)isOperators:(id)arg1;
- (void)setOperand:(double)arg1;
- (void)setDecimalLength:(long long)arg1;
- (id)init;

@end

