//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CategoryVo;

@protocol CategoryInputButtonDelegate <NSObject>
- (void)searchCategory;
- (void)addCategory;
- (void)editCategory;
- (void)selectedCategory:(CategoryVo *)arg1;
- (CategoryVo *)currentCategory;
- (unsigned long long)transactionType;
@end

