//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class KDCategory, NSArray, NSString;

@protocol CategoryDao <NSObject>
- (NSArray *)categoryPOIDsDuplicatedInTransactionsBetweenStartTime:(double)arg1 andEndTime:(double)arg2;
- (KDCategory *)categoryInPayoutAndIncomeWithName:(NSString *)arg1;
- (_Bool)categoryIsExist:(NSString *)arg1;
- (long long)projectRootCategoryId;
- (NSArray *)listIncomeCategoryUnderRoot;
- (KDCategory *)incomeRootCategory;
- (long long)incomeRootCategoryId;
- (NSArray *)listPayoutCategoryUnderRoot;
- (KDCategory *)payoutRootCategory;
- (long long)payoutRootCategoryId;
- (_Bool)addToDeleteTableWithId:(long long)arg1;
- (KDCategory *)categoryWithName:(NSString *)arg1;
- (KDCategory *)categoryWithoutHasChildrenById:(long long)arg1;
- (KDCategory *)parentCategoryById:(long long)arg1;
- (KDCategory *)categoryById:(long long)arg1;
- (NSArray *)listHierarchySubcategory:(long long)arg1;
- (NSArray *)listSubCategory:(long long)arg1;
- (_Bool)updateCategory:(KDCategory *)arg1;
- (_Bool)deleteCategory:(long long)arg1;
- (_Bool)existTransactionWithCategoryId:(long long)arg1;
- (long long)addCategory:(KDCategory *)arg1 at:(long long)arg2;
@end

