//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSIndexPath;

@interface CompositeIndexPath : NSObject
{
    NSIndexPath *_indexPath;
    unsigned long long _subRow;
}

+ (id)compositeIndexPathForSubRow:(unsigned long long)arg1 indexPath:(id)arg2;
@property unsigned long long subRow; // @synthesize subRow=_subRow;
@property(retain, nonatomic) NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;
- (void).cxx_destruct;

@end

