//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CompositeIndexPath, CompositeTableView, NSIndexPath, UITableView, UITableViewCell;

@protocol CompositeTableViewDataSource <NSObject>
- (UITableViewCell *)subTableView:(UITableView *)arg1 cellForSubrow:(long long)arg2 atIndexPath:(NSIndexPath *)arg3 rightTableIndexPath:(NSIndexPath *)arg4;
- (UITableViewCell *)mainTableView:(UITableView *)arg1 cellForRowAtIndexPath:(NSIndexPath *)arg2;
- (long long)compositeTableView:(CompositeTableView *)arg1 numberOfSubRowsAtIndexPath:(NSIndexPath *)arg2 rightTableIndexPath:(NSIndexPath *)arg3;
- (long long)compositeTableView:(CompositeTableView *)arg1 numberOfRowsInSection:(long long)arg2;

@optional
- (_Bool)compositeTableView:(CompositeTableView *)arg1 canEditAtIndexPath:(NSIndexPath *)arg2;
- (void)rightTableView:(UITableView *)arg1 commitEditingStyle:(long long)arg2 atIndexPath:(NSIndexPath *)arg3 compositeIndexPath:(CompositeIndexPath *)arg4;
- (long long)numberOfSectionsInCompositeTableView:(CompositeTableView *)arg1;
@end

