//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CorporationPickerView, CorporationVo, ExpenseVo;

@protocol CorporationPickerViewDelegate <NSObject>
- (void)corporationPicker:(CorporationPickerView *)arg1 didSelectedCorporation:(CorporationVo *)arg2;
- (ExpenseVo *)expenseVoFromCorporationDelegate;

@optional
- (void)finishFetchLBSinfo;
- (void)startFetchLBSinfo;
@end

