//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSString, UIButton, UIImageView, UILabel, UIView;

@interface CreditRewardCell : UITableViewCell
{
    _Bool _isAnimating;
    UILabel *_nameLabel;
    UILabel *_memoLabel;
    UILabel *_surnameLabel;
    UILabel *_animatingPotintLabel;
    UIImageView *_iconImageView;
    UIView *_cellSeperatorLine;
    UIButton *_getCreditButton;
    NSString *_finalCredit;
}

@property(nonatomic) _Bool isAnimating; // @synthesize isAnimating=_isAnimating;
@property(retain, nonatomic) NSString *finalCredit; // @synthesize finalCredit=_finalCredit;
@property(retain, nonatomic) UIButton *getCreditButton; // @synthesize getCreditButton=_getCreditButton;
@property(retain, nonatomic) UIView *cellSeperatorLine; // @synthesize cellSeperatorLine=_cellSeperatorLine;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) UILabel *animatingPotintLabel; // @synthesize animatingPotintLabel=_animatingPotintLabel;
@property(retain, nonatomic) UILabel *surnameLabel; // @synthesize surnameLabel=_surnameLabel;
@property(retain, nonatomic) UILabel *memoLabel; // @synthesize memoLabel=_memoLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
- (void).cxx_destruct;
- (void)setGetCreditButtonTitle:(id)arg1;
- (void)finishTaskAnimationWithFinalCredit:(id)arg1 isTaskFinished:(_Bool)arg2;
- (void)setGetCreditButtonWithControlState:(unsigned long long)arg1;
- (void)dealloc;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

