//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CorporationVo.h"

@class NSDecimalNumber;

@interface CreditorVo : CorporationVo
{
    NSDecimalNumber *_repaymentAmount;
    NSDecimalNumber *_receivableAmount;
    long long _numberOfLoan;
    long long _ordered;
}

+ (id)nullCreditorVo;
@property long long ordered; // @synthesize ordered=_ordered;
@property long long numberOfLoan; // @synthesize numberOfLoan=_numberOfLoan;
@property(retain, nonatomic) NSDecimalNumber *receivableAmount; // @synthesize receivableAmount=_receivableAmount;
@property(retain, nonatomic) NSDecimalNumber *repaymentAmount; // @synthesize repaymentAmount=_repaymentAmount;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

