//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseTableViewController.h"

#import "AccountPickerViewDelegate.h"
#import "CategoryPickerViewDelegate.h"
#import "CorporationPickerViewDelegate.h"
#import "MemberPickerViewDelegate.h"
#import "ProjectPickerViewDelegate.h"

@class AccountPickerView, AccountVo, CategoryPickerView, CategoryVo, CorporationPickerView, CorporationVo, HMSegmentedControl, KDTabView, MemberPickerView, MemberVo, NSString, ProjectPickerView, ProjectVo, UIScrollView, UITableView;

@interface CustomAddExpenseViewController : BaseTableViewController <CategoryPickerViewDelegate, AccountPickerViewDelegate, MemberPickerViewDelegate, ProjectPickerViewDelegate, CorporationPickerViewDelegate>
{
    int _currencyType;
    UITableView *_tableView;
    KDTabView *_currencyPicker;
    CategoryPickerView *_categoryPicker;
    AccountPickerView *_accountPicker;
    MemberPickerView *_memberPicker;
    ProjectPickerView *_projectPicker;
    CorporationPickerView *_corporationPicker;
    CategoryVo *_selectedCategoryVo;
    AccountVo *_selectedAccountVo;
    MemberVo *_selectedMemberVo;
    ProjectVo *_selectedProjectVo;
    CorporationVo *_selectedCorporationVo;
    HMSegmentedControl *_segementedControl;
    UIScrollView *_scrollView;
    UITableView *_incomeTableView;
}

@property(retain, nonatomic) UITableView *incomeTableView; // @synthesize incomeTableView=_incomeTableView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) HMSegmentedControl *segementedControl; // @synthesize segementedControl=_segementedControl;
@property(retain, nonatomic) CorporationVo *selectedCorporationVo; // @synthesize selectedCorporationVo=_selectedCorporationVo;
@property(retain, nonatomic) ProjectVo *selectedProjectVo; // @synthesize selectedProjectVo=_selectedProjectVo;
@property(retain, nonatomic) MemberVo *selectedMemberVo; // @synthesize selectedMemberVo=_selectedMemberVo;
@property(retain, nonatomic) AccountVo *selectedAccountVo; // @synthesize selectedAccountVo=_selectedAccountVo;
@property(retain, nonatomic) CategoryVo *selectedCategoryVo; // @synthesize selectedCategoryVo=_selectedCategoryVo;
@property(retain, nonatomic) CorporationPickerView *corporationPicker; // @synthesize corporationPicker=_corporationPicker;
@property(retain, nonatomic) ProjectPickerView *projectPicker; // @synthesize projectPicker=_projectPicker;
@property(retain, nonatomic) MemberPickerView *memberPicker; // @synthesize memberPicker=_memberPicker;
@property(retain, nonatomic) AccountPickerView *accountPicker; // @synthesize accountPicker=_accountPicker;
@property(retain, nonatomic) CategoryPickerView *categoryPicker; // @synthesize categoryPicker=_categoryPicker;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)reloadForOtherSegement;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)segmentedControlChangedValue:(id)arg1;
- (void)corporationPicker:(id)arg1 didSelectedCorporation:(id)arg2;
- (id)expenseVoFromCorporationDelegate;
- (_Bool)isHideAccountBalance;
- (void)accountPickerView:(id)arg1 didSelectedReimburseAccount:(id)arg2;
- (void)accountPickerView:(id)arg1 didSelectedAccount:(id)arg2;
- (id)expenseVoForAccountFromDelegate;
- (void)categoryPickerView:(id)arg1 didSelectedCategory:(id)arg2;
- (id)expenseVoForCategoryFromDelegate;
- (void)projectPickerView:(id)arg1 didSelectedProject:(id)arg2;
- (id)expenseVoForProjectFromDelegate;
- (void)memberPickerView:(id)arg1 didSelectedMemeber:(id)arg2;
- (id)expenseVoFromDelegate;
- (void)willSlideUpAction:(id)arg1;
- (void)closeAction:(id)arg1;
- (void)tapViewAddEvents:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)reloadSelectedVos;
- (void)viewDidLoad;
- (void)delayDismisDSAlertView:(id)arg1;
- (void)saveAction:(id)arg1;
- (void)createTableFooterForTable:(id)arg1;
- (void)loadView;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

