//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel;

@interface DailySummaryView : UIView
{
    UILabel *_expenceLabel;
    UILabel *_incomeLabel;
    UILabel *_balanceLabel;
}

@property(nonatomic) __weak UILabel *balanceLabel; // @synthesize balanceLabel=_balanceLabel;
@property(nonatomic) __weak UILabel *incomeLabel; // @synthesize incomeLabel=_incomeLabel;
@property(nonatomic) __weak UILabel *expenceLabel; // @synthesize expenceLabel=_expenceLabel;
- (void).cxx_destruct;
- (void)setupLabel:(id)arg1;
- (void)setupBalanceLabel;
- (void)setupIncomeLabel;
- (void)setupExpenceLabel;
- (void)awakeFromNib;
- (void)setExpence:(id)arg1 income:(id)arg2 balance:(id)arg3;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

