//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DaoFactory : NSObject
{
    struct sqlite3 *database;
}

+ (id)sharedInstance;
@property(nonatomic) struct sqlite3 *database; // @synthesize database;
- (id)recurrenceRuleDao;
- (id)multiDimensionBudgetDao;
- (id)ACLLinkRolePermissionDao;
- (id)ACLLinkUserRoleDao;
- (id)ACLRoleDao;
- (id)transactionListTemplateDao;
@property(readonly) __weak id <PreferenceDao> preferenceDao;
- (id)loanDao;
- (id)importDao;
@property(readonly) __weak id <ResourceDao> resourceDao;
- (id)notificationDao;
- (id)recentUsedDao;
- (id)messageCenterDao;
- (id)propertyDao;
@property(readonly) __weak id <TransactionTemplateDao> transactionTemplateDao;
@property(readonly) __weak id <ReportDao> reportDao;
@property(readonly) __weak id <SyncLogDao> syncLogDao;
@property(readonly) __weak id <ExchangeDao> exchangeDao;
@property(readonly) __weak id <ProfileDao> profileDao;
- (id)settingDao;
@property(readonly) __weak id <MaintainDao> maintainDao;
@property(readonly) __weak id <BudgetDao> budgetDao;
@property(readonly) __weak id <TagDao> tagDao;
- (id)planningDao;
@property(readonly) __weak id <CategoryDao> categoryDao;
@property(readonly) __weak id <UserDao> userDao;
@property(readonly) __weak id <CorporationDao> corporationDao;
@property(readonly) __weak id <AccountGroupDao> accountGroupDao;
@property(readonly) __weak id <AccountDao> accountDao;
@property(readonly) __weak id <TransactionDao> transactionDao;
- (id)databaseConnection;
- (id)stockTransactionDao;
- (id)stockHoldingDao;
- (id)stockRecordDao;
- (id)fundTransactionDao;
- (id)fundHoldingDao;
- (id)fundPriceDao;
- (id)fundDao;

@end

