//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DatabaseEncryptor : NSObject
{
}

+ (_Bool)writeHeaderData:(id)arg1 toFile:(id)arg2;
+ (_Bool)decryptDataBaseAtPath:(id)arg1;
+ (_Bool)encryptDataBaseAtPath:(id)arg1;

@end

