//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DataSetSyncConnectionHandler : NSObject
{
}

- (id)generateBoundaryString;
- (id)requestWithFilePath:(id)arg1 sessionKey:(id)arg2 URL:(id)arg3;
- (void)requestUploadWithFilePath:(id)arg1 sessionKey:(id)arg2 URL:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;

@end

