//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface DataSuiteVo : NSObject
{
    NSString *_displayName;
    NSString *_name;
    NSString *_path;
    NSString *_accountName;
    _Bool _everSync;
}

@property(retain, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property _Bool everSync; // @synthesize everSync=_everSync;
@property(retain, nonatomic) NSString *accountName; // @synthesize accountName=_accountName;
@property(retain, nonatomic) NSString *path; // @synthesize path=_path;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)description;
- (id)initWithName:(id)arg1 path:(id)arg2;

@end

