//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString;

@interface DayProfitView : UIView
{
    _Bool _isSecureShow;
    NSString *_profitString;
}

@property(retain, nonatomic) NSString *profitString; // @synthesize profitString=_profitString;
@property(nonatomic) _Bool isSecureShow; // @synthesize isSecureShow=_isSecureShow;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

