//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIActivityIndicatorView, UILabel;

@interface DSActivityView : UIView
{
    UIView *_originalView;
    UIView *_borderView;
    UIActivityIndicatorView *_activityIndicator;
    UILabel *_activityLabel;
    unsigned long long _labelWidth;
    _Bool _showNetworkActivityIndicator;
}

+ (void)removeView;
+ (id)newActivityViewForView:(id)arg1 withLabel:(id)arg2 width:(unsigned long long)arg3;
+ (id)newActivityViewForView:(id)arg1 withLabel:(id)arg2;
+ (id)newActivityViewForView:(id)arg1;
+ (id)currentActivityView;
@property(nonatomic) _Bool showNetworkActivityIndicator; // @synthesize showNetworkActivityIndicator=_showNetworkActivityIndicator;
@property(nonatomic) unsigned long long labelWidth; // @synthesize labelWidth=_labelWidth;
@property(retain, nonatomic) UIView *originalView; // @synthesize originalView=_originalView;
- (void).cxx_destruct;
- (void)animateRemove;
- (void)animateShow;
- (void)layoutSubviews;
@property(readonly, nonatomic) __weak UILabel *activityLabel;
@property(readonly, nonatomic) __weak UIActivityIndicatorView *activityIndicator;
@property(readonly, nonatomic) __weak UIView *borderView;
- (void)setupBackground;
- (struct CGRect)enclosingFrame;
- (id)viewForView:(id)arg1;
- (void)dealloc;
- (id)initForView:(id)arg1 withLabel:(id)arg2 width:(unsigned long long)arg3;

@end

