//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, RemoteAccountService;

@interface DumpDataHelper : NSObject
{
    NSMutableDictionary *_categoryIdMap;
    NSMutableDictionary *_accountIdMap;
    NSMutableDictionary *_entityIdMap;
    NSMutableDictionary *_tagIdMap;
    RemoteAccountService *_remoteAccountService;
    NSMutableDictionary *_transactionIdMap;
    NSMutableDictionary *_debtHasTransIdMap;
}

@property(retain, nonatomic) NSMutableDictionary *debtHasTransIdMap; // @synthesize debtHasTransIdMap=_debtHasTransIdMap;
@property(retain, nonatomic) NSMutableDictionary *transactionIdMap; // @synthesize transactionIdMap=_transactionIdMap;
@property(retain, nonatomic) RemoteAccountService *remoteAccountService; // @synthesize remoteAccountService=_remoteAccountService;
@property(retain, nonatomic) NSMutableDictionary *tagIdMap; // @synthesize tagIdMap=_tagIdMap;
@property(retain, nonatomic) NSMutableDictionary *entityIdMap; // @synthesize entityIdMap=_entityIdMap;
@property(retain, nonatomic) NSMutableDictionary *accountIdMap; // @synthesize accountIdMap=_accountIdMap;
@property(retain, nonatomic) NSMutableDictionary *categoryIdMap; // @synthesize categoryIdMap=_categoryIdMap;
- (void).cxx_destruct;
- (id)sortRecordsByCreatTime:(id)arg1;
- (void)addProjectToTagMaps:(id)arg1 transId:(long long)arg2;
- (_Bool)copyTransactionsToNewAccountBook:(id)arg1;
- (id)getAllLoanTransactionsThatNotClose;
- (id)getAllTransactionsAfterGivenTimeExceptLoan:(id)arg1;
- (long long)getNewIdFromOld:(id)arg1 oldid:(long long)arg2;
- (void)convertAllTransactionsIdMAP:(id)arg1;
- (id)getAllPhotoName:(id)arg1;
- (_Bool)copyPhotosFrom:(id)arg1 toPath:(id)arg2 nameArray:(id)arg3;
- (_Bool)dumpTransactions:(id)arg1 projectMapsArray:(id)arg2;
- (id)getAllTransactionsAfterGivenTime:(id)arg1;
- (_Bool)dumpAllTransactionDebtGroup:(id)arg1;
- (id)getAllTransactionDebtGroup;
- (_Bool)dumpAllTransactionDebt:(id)arg1;
- (id)getAllTransactionDebt;
- (id)errorWithMessage:(id)arg1;
- (void)dumpProfile:(id)arg1;
- (void)dumpLocalRecents:(id)arg1;
- (void)dumpTransactionTemplates:(id)arg1;
- (void)dumpBudgets:(id)arg1;
- (void)dumpCorporations:(id)arg1 creditors:(id)arg2;
- (void)dumpRates:(id)arg1;
- (void)calcuteAcccountNewBalanceByAccounts:(id)arg1;
- (void)dumpAccounts:(id)arg1;
- (void)dumpCategoriesAtFirstLevel:(id)arg1 secondLevel:(id)arg2 rootId:(long long)arg3 type:(int)arg4;
- (void)dumpMembers:(id)arg1 projects:(id)arg2;
- (void)dumpPreference:(id)arg1;
- (id)getPreference;
- (_Bool)dumpBaseDataToAccountBook:(id)arg1 date:(id)arg2 error:(id *)arg3;
- (_Bool)isName:(id)arg1 existIn:(id)arg2;
- (id)newBaseName:(id)arg1 inAccountBooks:(id)arg2;
- (void)dumpBaseTableFromAccountBook:(id)arg1 date:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)init;

@end

