//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseCategoryViewController.h"

#import "DirtyDataDetectable.h"

@class CategoryVo, NSString;

@interface EditingCategoryViewController : BaseCategoryViewController <DirtyDataDetectable>
{
    id <EditingCategoryViewControllerDelegate> delegate;
    CategoryVo *categoryVo;
    NSString *_initializedName;
}

@property(retain, nonatomic) NSString *initializedName; // @synthesize initializedName=_initializedName;
@property(retain, nonatomic) CategoryVo *categoryVo; // @synthesize categoryVo;
@property(nonatomic) __weak id <EditingCategoryViewControllerDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (_Bool)containDirtyDataAfterSynced;
- (void)save:(id)arg1;
- (void)cancel:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

