//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSString, UILabel;

@interface EmptyDataViewController : UIViewController
{
    NSString *_titleString;
    NSString *_descriptionString;
    UILabel *_titleLabel;
    UILabel *_descriptionLabel;
}

@property __weak UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) NSString *descriptionString; // @synthesize descriptionString=_descriptionString;
@property(retain, nonatomic) NSString *titleString; // @synthesize titleString=_titleString;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)init;

@end

