//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ExchangeService.h"

@interface ExchangeServiceImpl : NSObject <ExchangeService>
{
}

- (_Bool)updateFrom:(id)arg1 to:(id)arg2 rate:(float)arg3 update:(_Bool)arg4;
- (id)allExchangeRates;
- (float)rateFrom:(id)arg1 to:(id)arg2;

@end

