//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ExpenseVo.h"

@class NSString;

@interface ExpenseTemplateVo : ExpenseVo
{
    NSString *_templateName;
    long long _repeatInterval;
    double _firstReminderTime;
    long long _createdSourceType;
    long long _groupType;
    NSString *_changedLog;
}

@property(retain, nonatomic) NSString *changedLog; // @synthesize changedLog=_changedLog;
@property(nonatomic) long long groupType; // @synthesize groupType=_groupType;
@property(nonatomic) long long createdSourceType; // @synthesize createdSourceType=_createdSourceType;
@property(nonatomic) double firstReminderTime; // @synthesize firstReminderTime=_firstReminderTime;
@property(nonatomic) long long repeatInterval; // @synthesize repeatInterval=_repeatInterval;
@property(retain, nonatomic) NSString *templateName; // @synthesize templateName=_templateName;
- (void).cxx_destruct;
- (id)toExpenseVoForAdding;
- (id)toStringReminderTime;
- (id)nextReminderTimeSince:(id)arg1;
- (id)initWithTemplateExpenseVo:(id)arg1;
- (id)initWithExpenseVo:(id)arg1;

@end

