//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface FastContentView : UIView
{
    int positionType;
    _Bool _isLastSectionLastRow;
    _Bool _isInLastSection;
    _Bool _isLastRowInSection;
}

@property(nonatomic) _Bool isLastRowInSection; // @synthesize isLastRowInSection=_isLastRowInSection;
@property(nonatomic) _Bool isInLastSection; // @synthesize isInLastSection=_isInLastSection;
@property(nonatomic) _Bool isLastSectionLastRow; // @synthesize isLastSectionLastRow=_isLastSectionLastRow;
@property(nonatomic) int positionType; // @synthesize positionType;
- (id)initWithFrame:(struct CGRect)arg1;

@end

