//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FDAccountBookTemplateImporter : NSObject
{
    _Bool _isRemoteAccountBook;
    _Bool _isBunchImporting;
    id <FDAccountBookImporterDelegate> _importerDelegate;
}

@property(nonatomic) _Bool isBunchImporting; // @synthesize isBunchImporting=_isBunchImporting;
@property(nonatomic) _Bool isRemoteAccountBook; // @synthesize isRemoteAccountBook=_isRemoteAccountBook;
@property(nonatomic) __weak id <FDAccountBookImporterDelegate> importerDelegate; // @synthesize importerDelegate=_importerDelegate;
- (void).cxx_destruct;
- (id)renameAccountBookNameIfIsExist:(id)arg1 isRemoteAccountBook:(_Bool)arg2;
- (void)handleFailedImportedTemplateNotification:(id)arg1;
- (void)handleSuccessImportedTemplateNotification:(id)arg1;
- (void)importTemplate:(id)arg1 accountBookName:(id)arg2 isRemoteAccountBook:(_Bool)arg3;
- (void)importAccountBookWithTemplate:(id)arg1 accountBookName:(id)arg2 isRemoteAccountBook:(_Bool)arg3;
- (void)importLocalAccountBooksWithTemplates:(id)arg1;
- (void)removeObserver;
- (void)addObserver;
- (void)dealloc;

@end

