//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FDSharedAccountBookDownloadFileInfo, NSString;

@interface FDAccountBookTemplateDatabaseHelper : NSObject
{
    FDSharedAccountBookDownloadFileInfo *_fileInfo;
    NSString *_destination;
    NSString *_decryptKey;
    NSString *_temporaryFilePath;
}

+ (id)generateUnzipTemporaryPath;
+ (_Bool)parseDatabaseZipFile:(id)arg1 toDestination:(id)arg2 decryptKey:(id)arg3 error:(id *)arg4;
@property(retain, nonatomic) NSString *temporaryFilePath; // @synthesize temporaryFilePath=_temporaryFilePath;
@property(retain, nonatomic) NSString *decryptKey; // @synthesize decryptKey=_decryptKey;
@property(retain, nonatomic) NSString *destination; // @synthesize destination=_destination;
@property(retain, nonatomic) FDSharedAccountBookDownloadFileInfo *fileInfo; // @synthesize fileInfo=_fileInfo;
- (void).cxx_destruct;
- (_Bool)parseDatabaseFileAtPath:(id)arg1 toDestinationWithError:(id *)arg2;
- (id)initWithDestination:(id)arg1 decryptKey:(id)arg2;

@end

