//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray, UIButton, UILabel;

@interface FDAccountBookSharingActionSheet : UIView
{
    _Bool _animating;
    _Bool _showSaveToAlbumButton;
    _Bool _hasTitleLabel;
    _Bool _hasSecondLine;
    id <FDAccountBookSharingActionSheetDelegate> _delegate;
    NSMutableArray *_buttons;
    UIView *_firstLine;
    UIView *_secondLine;
    UILabel *_titleLabel;
    UIView *_containerView;
    UIButton *_cancelButton;
    UIButton *_saveToAlbumButton;
    long long _numOfLines;
}

@property(nonatomic) _Bool hasSecondLine; // @synthesize hasSecondLine=_hasSecondLine;
@property(nonatomic) long long numOfLines; // @synthesize numOfLines=_numOfLines;
@property(retain, nonatomic) UIButton *saveToAlbumButton; // @synthesize saveToAlbumButton=_saveToAlbumButton;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *secondLine; // @synthesize secondLine=_secondLine;
@property(retain, nonatomic) UIView *firstLine; // @synthesize firstLine=_firstLine;
@property(retain, nonatomic) NSMutableArray *buttons; // @synthesize buttons=_buttons;
@property(nonatomic) _Bool hasTitleLabel; // @synthesize hasTitleLabel=_hasTitleLabel;
@property(nonatomic) _Bool showSaveToAlbumButton; // @synthesize showSaveToAlbumButton=_showSaveToAlbumButton;
@property(nonatomic) __weak id <FDAccountBookSharingActionSheetDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)showOnView:(id)arg1;
- (void)reloadData;
- (void)setTitle:(id)arg1;
- (void)notifyClicked:(long long)arg1;
- (void)notifySaveToAlbum;
- (void)notifyCancel;
- (void)handleSaveButtonClicked:(id)arg1;
- (void)handleCancelButtonClicked:(id)arg1;
- (void)handleButtonClicked:(id)arg1;
- (void)reloadScrollView;
- (void)dismiss:(CDUnknownBlockType)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

