//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FDAccountBookSeed, FDSharedAccountBookDownloadFileInfo, NSString;

@interface FDAccountBookTemplateHeaderFileHelper : NSObject
{
    _Bool _isVersionSupport;
    FDAccountBookSeed *_seed;
    FDSharedAccountBookDownloadFileInfo *_fileInfo;
    NSString *_destinationPath;
    NSString *_temporaryFilePath;
}

@property(retain, nonatomic) NSString *temporaryFilePath; // @synthesize temporaryFilePath=_temporaryFilePath;
@property(retain, nonatomic) NSString *destinationPath; // @synthesize destinationPath=_destinationPath;
@property(retain, nonatomic) FDSharedAccountBookDownloadFileInfo *fileInfo; // @synthesize fileInfo=_fileInfo;
@property(nonatomic) _Bool isVersionSupport; // @synthesize isVersionSupport=_isVersionSupport;
@property(retain, nonatomic) FDAccountBookSeed *seed; // @synthesize seed=_seed;
- (void).cxx_destruct;
- (void)cleanTemporyFile:(_Bool)arg1;
- (_Bool)parseHeaderFileToDestination:(id)arg1 errorString:(id *)arg2;
- (_Bool)parseHeaderFileDataToDestination:(id)arg1 errorString:(id *)arg2;
- (id)initWithDestinationPath:(id)arg1;

@end

