//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FDAccountBookSharingAPIManager : NSObject
{
}

+ (id)coverNameStringWithAccountBookVo:(id)arg1;
+ (id)sortedArrayForTopTransactionsArray:(id)arg1;
+ (id)presentingInformationForCurrentAccountBookTransactionSharingWithStartTime:(double)arg1 endTime:(double)arg2;
+ (id)presentingInformationForCurrentAccountBookSharing;
+ (id)sharedManager;
- (id)encryptString:(id)arg1;
- (void)updateSubscribeShareAccountBookUpdateWithShareCode:(id)arg1 acceptPush:(_Bool)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)batchDeleteSubscribeShareAccountBookUpdateWithShareCode:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)deleteSubscribeShareAccountBookUpdateWithShareCode:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)newSubscribeShareAccountBookUpdateWithAccount:(id)arg1 password:(id)arg2 shareCode:(id)arg3 acceptPush:(_Bool)arg4 success:(CDUnknownBlockType)arg5 failure:(CDUnknownBlockType)arg6;
- (void)stopSharingAccountBookVo:(id)arg1 withUsername:(id)arg2 andPassword:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)querySharedAccountBookInfoWithInvitationCode:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)querySharedAccountBookInfoWithInvitationCode:(id)arg1 ftype:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)uploadAccountBookSharingImage:(id)arg1 withUserName:(id)arg2 andPassword:(id)arg3 andShareCode:(id)arg4 onSuccess:(CDUnknownBlockType)arg5 onFailure:(CDUnknownBlockType)arg6;
- (void)exportAccountBook:(id)arg1 withUsername:(id)arg2 password:(id)arg3 title:(id)arg4 description:(id)arg5 redirectURL:(id)arg6 presentingInfo:(id)arg7 filterType:(id)arg8 filters:(id)arg9 hasUpdate:(_Bool)arg10 completion:(CDUnknownBlockType)arg11;
- (void)queryAccountBookHasUpdatedWithShareCodes:(id)arg1 andSuccessCompletion:(CDUnknownBlockType)arg2 andFailureCompletion:(CDUnknownBlockType)arg3;
- (void)queryAccountBookSharingInformationWithSyncId:(id)arg1 andSuccessCompletion:(CDUnknownBlockType)arg2 andFailureCompletion:(CDUnknownBlockType)arg3;

@end

