//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDBaseAccountBookCell.h"

@class FDEditButton, NSLayoutConstraint, UILabel, UIView;

@interface FDAccountBookCell : FDBaseAccountBookCell
{
    _Bool _isSelected;
    _Bool _isShared;
    _Bool _isRemote;
    _Bool _isSubScribe;
    _Bool _isUpdate;
    _Bool _isLastRowInSection;
    _Bool _isEditFinished;
    UILabel *_sharedLabel;
    UILabel *_sharedNumberLabel;
    FDEditButton *_editButton;
    UIView *_redDotView;
    NSLayoutConstraint *_accountBookLabelTopConstraint;
    NSLayoutConstraint *_coverImageViewLeftConstraint;
    NSLayoutConstraint *_accountBookNameLabelWidthConstraint;
    UIView *_bottomLineView;
    UIView *_selectedSignView;
}

@property(retain, nonatomic) UIView *selectedSignView; // @synthesize selectedSignView=_selectedSignView;
@property(retain, nonatomic) UIView *bottomLineView; // @synthesize bottomLineView=_bottomLineView;
@property(nonatomic) __weak NSLayoutConstraint *accountBookNameLabelWidthConstraint; // @synthesize accountBookNameLabelWidthConstraint=_accountBookNameLabelWidthConstraint;
@property(nonatomic) __weak NSLayoutConstraint *coverImageViewLeftConstraint; // @synthesize coverImageViewLeftConstraint=_coverImageViewLeftConstraint;
@property(nonatomic) __weak NSLayoutConstraint *accountBookLabelTopConstraint; // @synthesize accountBookLabelTopConstraint=_accountBookLabelTopConstraint;
@property(nonatomic) _Bool isEditFinished; // @synthesize isEditFinished=_isEditFinished;
@property(nonatomic) _Bool isLastRowInSection; // @synthesize isLastRowInSection=_isLastRowInSection;
@property(nonatomic) _Bool isUpdate; // @synthesize isUpdate=_isUpdate;
@property(nonatomic) _Bool isSubScribe; // @synthesize isSubScribe=_isSubScribe;
@property(nonatomic) _Bool isRemote; // @synthesize isRemote=_isRemote;
@property(nonatomic) _Bool isShared; // @synthesize isShared=_isShared;
@property(nonatomic) _Bool isSelected; // @synthesize isSelected=_isSelected;
@property(retain, nonatomic) UIView *redDotView; // @synthesize redDotView=_redDotView;
@property(retain, nonatomic) FDEditButton *editButton; // @synthesize editButton=_editButton;
@property(nonatomic) __weak UILabel *sharedNumberLabel; // @synthesize sharedNumberLabel=_sharedNumberLabel;
@property(nonatomic) __weak UILabel *sharedLabel; // @synthesize sharedLabel=_sharedLabel;
- (void).cxx_destruct;
- (void)dealloc;
- (void)hideSelectedSignView;
- (void)showSelectedSignView:(_Bool)arg1;
- (void)layoutSubviews;
- (void)setupBottomLineViewLayout;
- (void)adjustAccountBookTopConstraint;
- (void)setupEditButtonTarget:(id)arg1 action:(SEL)arg2;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

