//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class FDBookTemplateImageInfo, NSMutableArray, NSString;

@interface FDBookTemplate : NSObject <NSCopying>
{
    NSMutableArray *_entryInfos;
    long long _ID;
    unsigned long long _layoutType;
    NSString *_name;
    FDBookTemplateImageInfo *_imageInfo;
    unsigned long long _textColorScheme;
}

+ (id)infoFromString:(id)arg1;
+ (id)stringFromColorScheme:(unsigned long long)arg1;
+ (unsigned long long)colorSchemeFromString:(id)arg1;
+ (id)stringFromTemplateType:(unsigned long long)arg1;
+ (unsigned long long)templateTypeFromString:(id)arg1;
+ (void)initialize;
+ (id)templateFromDictionary:(id)arg1;
+ (id)templateFromJSON:(id)arg1;
@property(nonatomic) unsigned long long textColorScheme; // @synthesize textColorScheme=_textColorScheme;
@property(retain, nonatomic) FDBookTemplateImageInfo *imageInfo; // @synthesize imageInfo=_imageInfo;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) unsigned long long layoutType; // @synthesize layoutType=_layoutType;
@property(nonatomic) long long ID; // @synthesize ID=_ID;
- (void).cxx_destruct;
- (_Bool)isDefault;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)setEntryInfos:(id)arg1;
- (_Bool)setInfo:(id)arg1 atIndex:(long long)arg2;
- (id)infoAtIndex:(long long)arg1;
- (id)entryInfos;
- (void)initInfos;
- (id)init;
- (id)toDictionary;
- (id)toJSON;
- (id)defaultBookTemplateForImage;
- (id)defaultBGImage;
- (id)scaledBackgroundImageWithTargetSize:(struct CGSize)arg1;
- (struct CGSize)topPanelImageSize;
- (unsigned long long)accountBookCoverType;
- (id)defaultImageInfo;
- (id)textColor;
- (id)backgroundImage;
- (id)backgroundImagePath;

@end

