//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface FDBookTemplateImageInfo : NSObject <NSCopying>
{
    int _imgID;
    unsigned long long _type;
    NSString *_customImgName;
}

+ (id)imagePathWithCustomImageName:(id)arg1;
+ (id)imagePathWithImageID:(long long)arg1;
+ (id)loadFromDictionary:(id)arg1;
@property(retain, nonatomic) NSString *customImgName; // @synthesize customImgName=_customImgName;
@property(nonatomic) int imgID; // @synthesize imgID=_imgID;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)imagePath;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithType:(unsigned long long)arg1 imgID:(int)arg2;
- (id)toDictionary;

@end

