//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FDBookTemplate;

@interface FDBookTemplateSample : NSObject
{
    FDBookTemplate *_bookTemplate;
}

+ (struct CGSize)imageSizeFromAttributes:(id)arg1;
+ (id)monthFromAttributes:(id)arg1;
+ (id)yearFromAttributes:(id)arg1;
+ (id)entryValuesFromAttributes:(id)arg1;
+ (id)entryKeysFromAttributes:(id)arg1;
+ (id)bookTemplateFromAttributes:(id)arg1;
+ (id)previewAttributesWithBookTemplate:(id)arg1;
@property(retain, nonatomic) FDBookTemplate *bookTemplate; // @synthesize bookTemplate=_bookTemplate;
- (void).cxx_destruct;
- (id)errorWithTipsString:(id)arg1;
- (id)storedKeyForThumbPreviewImageWithPath:(id)arg1 targetSize:(struct CGSize)arg2;
- (void)asyncLoadPreviewImageWithCompletion:(CDUnknownBlockType)arg1;
- (void)loadThumbPreviewImageWithCompletion:(CDUnknownBlockType)arg1;
- (void)drawPreviewImageWithCompletion:(CDUnknownBlockType)arg1;
- (struct CGRect)cropImageRectForThumb:(struct CGRect)arg1;
- (id)thumbImage;
- (struct CGSize)previewViewSize;
- (id)previewImage;
- (id)previewView:(_Bool)arg1;
- (id)initWithTemplate:(id)arg1;
- (id)init;

@end

