//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class MBProgressHUD, UIButton, UITextView;

@interface FDBrokenDBFixViewController : UIViewController
{
    MBProgressHUD *_hud;
    UITextView *_textView;
    UIButton *_manualFixButton;
}

@property(retain, nonatomic) UIButton *manualFixButton; // @synthesize manualFixButton=_manualFixButton;
@property(retain, nonatomic) UITextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) MBProgressHUD *hud; // @synthesize hud=_hud;
- (void).cxx_destruct;
- (void)showFixFailDialog;
- (void)showFixSuccessedDialog;
- (void)hideWaitingDialog;
- (void)showWaitingDialog;
- (void)fixBrokenDB;
- (void)checkAllDBs;
- (void)startFix:(id)arg1;
- (void)initButton;
- (void)initTextView;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)loadView;

@end

