//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewFlowLayout.h"

@interface FDCollectionViewSeperatorFlowLayout : UICollectionViewFlowLayout
{
}

- (id)layoutAttributesForDecorationViewOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (void)prepareLayout;
- (_Bool)indexPathLastItemInSection:(id)arg1;
- (_Bool)indexPathLastItemInLine:(id)arg1;

@end

