//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class FDCollapsableTableViewDataManager, NSArray, NSString, UITableView;

@interface FDCollapsableTableViewController : UIViewController <UITableViewDelegate, UITableViewDataSource>
{
    _Bool _fullySelected;
    _Bool _showAllSelectionSection;
    NSArray *_sectionSources;
    NSArray *_selectedRowSources;
    UITableView *_tableView;
    FDCollapsableTableViewDataManager *_dataManager;
    long long _allSelectionState;
    long long _expandedSectionIndex;
}

@property(nonatomic) long long expandedSectionIndex; // @synthesize expandedSectionIndex=_expandedSectionIndex;
@property(nonatomic) long long allSelectionState; // @synthesize allSelectionState=_allSelectionState;
@property(retain, nonatomic) FDCollapsableTableViewDataManager *dataManager; // @synthesize dataManager=_dataManager;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) _Bool showAllSelectionSection; // @synthesize showAllSelectionSection=_showAllSelectionSection;
@property(nonatomic) _Bool fullySelected; // @synthesize fullySelected=_fullySelected;
@property(retain, nonatomic) NSArray *selectedRowSources; // @synthesize selectedRowSources=_selectedRowSources;
@property(retain, nonatomic) NSArray *sectionSources; // @synthesize sectionSources=_sectionSources;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)iconTapActionForTapGesture:(id)arg1;
- (void)didSelectCommonSelectionCellForRowAtIndexPath:(id)arg1;
- (void)didSelectAllSelectionCellAction;
- (void)reloadAllSelectionCellIfIsShown;
- (id)allIndexPathsFromSection:(long long)arg1;
- (void)setSectionState:(unsigned long long)arg1 collapsed:(_Bool)arg2;
- (id)reusableAllSelectionCellWithCellIdentifier:(id)arg1;
- (id)reusableCommonSelectionCell;
- (id)tableView:(id)arg1 allSelectionCellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 commonSelectionCellForRowAtIndexPath:(id)arg2;
- (void)expandSection:(unsigned long long)arg1;
- (void)collapseSection:(unsigned long long)arg1;
- (void)loadView;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

