//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FDDatabaseTableInspector : NSObject
{
}

+ (id)allTableNamesForDatabase:(struct sqlite3 *)arg1;
+ (id)allTableNamesForDatabase:(struct sqlite3 *)arg1 forDatabaseName:(id)arg2;
+ (_Bool)inspectDatabase:(struct sqlite3 *)arg1 forTableName:(id)arg2 andOutMissingTableNames:(id *)arg3 andOutExtraTableNames:(id *)arg4;
+ (_Bool)inspectDatabase:(struct sqlite3 *)arg1 forDatabaseName:(id)arg2 forTableName:(id)arg3 andOutMissingTableNames:(id *)arg4 andOutExtraTableNames:(id *)arg5;

@end

