//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSData, NSDictionary;

@interface FDDownloadCacheItem : NSObject <NSCoding, NSCopying>
{
    NSData *_data;
    NSDictionary *_userInfo;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)userInfo;
- (id)data;
- (void)dealloc;
- (id)initWithData:(id)arg1 andUserInfo:(id)arg2;
- (id)initWithData:(id)arg1;

@end

