//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FDFinanceProductScrollViewDelegate.h"

#import "FDFinanceProductListDatasource.h"

@class FinanceMarketProductListNoticeModel, NSArray, NSString;

@interface FDFinanceProductListDatasource : FDFinanceProductScrollViewDelegate <FDFinanceProductListDatasource>
{
    NSArray *_data;
    NSArray *_bottomData;
    FinanceMarketProductListNoticeModel *_notice;
    id <FinanceProductTableViewActionDelegate> _actionDelegate;
}

@property(nonatomic) __weak id <FinanceProductTableViewActionDelegate> actionDelegate; // @synthesize actionDelegate=_actionDelegate;
@property(retain, nonatomic) FinanceMarketProductListNoticeModel *notice; // @synthesize notice=_notice;
@property(retain, nonatomic) NSArray *bottomData; // @synthesize bottomData=_bottomData;
@property(retain, nonatomic) NSArray *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (_Bool)isBottomSectionWithIndexPath:(id)arg1;
- (_Bool)isNoticeCellWithIndexPath:(id)arg1;
- (void)tableView:(id)arg1 registerNib:(id)arg2 forReuseIdentifer:(id)arg3;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <FinanceTableViewScrollDelegate> delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

