//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface FDFileAnalyseManager : NSObject
{
    NSString *_lastBrokenDBDetailInfo;
    NSString *_lastBrokenDBDPath;
}

+ (id)shareInstance;
@property(retain, nonatomic) NSString *lastBrokenDBDPath; // @synthesize lastBrokenDBDPath=_lastBrokenDBDPath;
@property(retain, nonatomic) NSString *lastBrokenDBDetailInfo; // @synthesize lastBrokenDBDetailInfo=_lastBrokenDBDetailInfo;
- (void).cxx_destruct;
- (id)fetchAllDBFilesInFolder:(id)arg1;
- (_Bool)isFileExited:(id)arg1;
- (_Bool)isFolder:(id)arg1;
- (id)analyseOldDBFileInSyncFolder:(id)arg1;
- (_Bool)checkNewDBFileInSyncFolderIsBroken:(id)arg1;
- (_Bool)checkHasSyncFolder:(id)arg1;
- (_Bool)preCheckCanBeFixed:(id)arg1;
- (_Bool)checkDBIsBroken:(id)arg1;
- (_Bool)fixBrokenDBByOldOne;
- (_Bool)checkDocumentFiles;
- (id)init;

@end

