//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FDForumToolboxActionSheet;

@protocol FDForumToolboxActionSheetDelegate <NSObject>
- (void)forumToolBoxActionSheetDidSelectCancelButton:(FDForumToolboxActionSheet *)arg1;
- (void)forumToolBoxActionSheet:(FDForumToolboxActionSheet *)arg1 didSelectShareButtonAtIndex:(long long)arg2;
- (void)forumToolBoxActionSheet:(FDForumToolboxActionSheet *)arg1 didSelectToolButtonAtIndex:(long long)arg2;
@end

