//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "AttachImagesViewDelegate.h"
#import "EmojiViewDelegate.h"
#import "ForumAttachmentViewDelegate.h"
#import "UITextViewDelegate.h"

@class AttachImagesView, EmojiView, ForumAttachmentView, NSString;

@interface FDForumReplyView : UIView <ForumAttachmentViewDelegate, EmojiViewDelegate, AttachImagesViewDelegate, UITextViewDelegate>
{
    _Bool _isTextAttachViewShow;
    _Bool _isAttachImagesViewShow;
    _Bool _isKeyboardShow;
    _Bool _isEmojiListViewShow;
    EmojiView *_emojiListView;
    AttachImagesView *_attachImagesView;
    id <FDForumReplyViewDelegate> _delegate;
    ForumAttachmentView *_forumAttachmentView;
    ForumAttachmentView *_replyToCustomerAttachmentView;
    ForumAttachmentView *_replyAttachmentView;
    UIView *_bgView;
}

@property(nonatomic) _Bool isEmojiListViewShow; // @synthesize isEmojiListViewShow=_isEmojiListViewShow;
@property(nonatomic) _Bool isKeyboardShow; // @synthesize isKeyboardShow=_isKeyboardShow;
@property(nonatomic) _Bool isAttachImagesViewShow; // @synthesize isAttachImagesViewShow=_isAttachImagesViewShow;
@property(nonatomic) _Bool isTextAttachViewShow; // @synthesize isTextAttachViewShow=_isTextAttachViewShow;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) ForumAttachmentView *replyAttachmentView; // @synthesize replyAttachmentView=_replyAttachmentView;
@property(retain, nonatomic) ForumAttachmentView *replyToCustomerAttachmentView; // @synthesize replyToCustomerAttachmentView=_replyToCustomerAttachmentView;
@property(retain, nonatomic) ForumAttachmentView *forumAttachmentView; // @synthesize forumAttachmentView=_forumAttachmentView;
@property(nonatomic) __weak id <FDForumReplyViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) AttachImagesView *attachImagesView; // @synthesize attachImagesView=_attachImagesView;
@property(retain, nonatomic) EmojiView *emojiListView; // @synthesize emojiListView=_emojiListView;
- (void).cxx_destruct;
- (void)willChoosePhotoToUpload;
- (void)showFullSizeImageWithButton:(id)arg1;
- (void)addPhotoAction;
- (void)emojiDidDelete;
- (void)emojiNumDidSelect:(long long)arg1;
- (void)willSlideUp;
- (void)hideAttachImagesView;
- (void)hideEmojiListView;
- (void)showAttachImagesView;
- (void)showEmojiListView;
- (void)showTextAttachViewAboveView:(id)arg1;
- (void)showTextAttachViewWithNotify:(id)arg1;
- (void)sendButtonAction:(id)arg1;
- (void)stopSendingAnimation;
- (void)startSendingAnimation;
- (void)clear;
- (void)hide;
- (void)showWithReplyUsername:(id)arg1 onView:(id)arg2;
- (void)initialize;
- (id)initWithDelegate:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

