//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HTTPRequestOperation.h"

#import "NSURLConnectionDataDelegate.h"

@class NSString;

@interface FDHTTPRequestOperation : HTTPRequestOperation <NSURLConnectionDataDelegate>
{
    CDUnknownBlockType _progressed;
}

+ (id)FDHTTPRequestOperationWithRequest:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3 progressed:(CDUnknownBlockType)arg4;
@property(copy, nonatomic) CDUnknownBlockType progressed; // @synthesize progressed=_progressed;
- (void).cxx_destruct;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)cancel;
- (void)main;
- (id)initWithRequest:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

