//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, UIImage, UIView;

@interface FDNewbieGuideViewManager : NSObject
{
    struct CGRect _displayArea;
    UIView *_stayCoverView;
    UIView *_coverView;
    NSDictionary *_accountBookMaps;
    long long _imageLayoutMode;
    double _cornerRadius;
    double _imageDisplayInterval;
    UIImage *_guideImage;
    id <FDNewbieGuideViewManagerDelegate> _delegate;
}

+ (void)clearNewbieGuideView;
@property(nonatomic) __weak id <FDNewbieGuideViewManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIImage *guideImage; // @synthesize guideImage=_guideImage;
@property(nonatomic) double imageDisplayInterval; // @synthesize imageDisplayInterval=_imageDisplayInterval;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(nonatomic) long long imageLayoutMode; // @synthesize imageLayoutMode=_imageLayoutMode;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSDictionary *accountBookMaps;
- (void)removeCoverView;
- (void)generateCoverView;
- (void)skipButtonWasPressed:(id)arg1;
- (void)enableScrollOfView:(id)arg1 enable:(_Bool)arg2;
- (id)initWithDisplayArea:(struct CGRect)arg1 stayCoverView:(id)arg2;

@end

