//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FDPOISearchProvider, NSArray, NSError;

@protocol FDPOISearchProviderDelegate <NSObject>
- (void)POISearchProvider:(FDPOISearchProvider *)arg1 didFinishSearchWithPOIs:(NSArray *)arg2;
- (void)POISearchProvider:(FDPOISearchProvider *)arg1 didSearchFailWithError:(NSError *)arg2;
@end

