//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface FDSharedData : NSObject
{
    NSString *_type;
}

+ (id)decryptString:(id)arg1;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)payload;
- (id)initWithPayloadString:(id)arg1;
- (id)encryptedString;
- (id)init;

@end

