//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSString, UIImage;

@interface FDShareCenterAccountBookMember : NSObject <NSCoding>
{
    NSString *_account;
    NSString *_nickname;
    NSString *_avatarURL;
    UIImage *_avatar;
}

@property(retain, nonatomic) UIImage *avatar; // @synthesize avatar=_avatar;
@property(retain, nonatomic) NSString *avatarURL; // @synthesize avatarURL=_avatarURL;
@property(retain, nonatomic) NSString *nickname; // @synthesize nickname=_nickname;
@property(retain, nonatomic) NSString *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

