//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CAGradientLayer, CALayer;

@interface FDShimmerView : UIView
{
    _Bool _shimmering;
    double _shimmeringAnimationOpacity;
    double _shimmeringOpacity;
    double _shimmeringSpeed;
    double _shimmeringPauseDuration;
    UIView *_contentView;
    CAGradientLayer *_maskLayer;
    CALayer *_contentLayer;
}

@property(retain, nonatomic) CALayer *contentLayer; // @synthesize contentLayer=_contentLayer;
@property(retain, nonatomic) CAGradientLayer *maskLayer; // @synthesize maskLayer=_maskLayer;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) double shimmeringPauseDuration; // @synthesize shimmeringPauseDuration=_shimmeringPauseDuration;
@property(nonatomic) double shimmeringSpeed; // @synthesize shimmeringSpeed=_shimmeringSpeed;
@property(nonatomic) double shimmeringOpacity; // @synthesize shimmeringOpacity=_shimmeringOpacity;
@property(nonatomic) double shimmeringAnimationOpacity; // @synthesize shimmeringAnimationOpacity=_shimmeringAnimationOpacity;
@property(nonatomic, getter=isShimmering) _Bool shimmering; // @synthesize shimmering=_shimmering;
- (void).cxx_destruct;
- (void)updateMaskLayout;
- (void)updateMaskColors;
- (void)createMaskIfNeeded;
- (void)clearMask;
- (void)updateShimmering;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

