//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FDShareCenterAccountBookMember, FDShareCenterCollectionView;

@protocol FDShareCenterCollectionViewDelegate <NSObject>
- (long long)numberOfParticipantsInShareCenterCollectionView:(FDShareCenterCollectionView *)arg1;

@optional
- (void)shareCenterCollectionViewDidClickRemove:(FDShareCenterCollectionView *)arg1;
- (_Bool)shareCenterCollectionView:(FDShareCenterCollectionView *)arg1 isMeAtIndex:(unsigned long long)arg2;
- (_Bool)shareCenterCollectionView:(FDShareCenterCollectionView *)arg1 isOwnerAtIndex:(unsigned long long)arg2;
- (void)shareCenterCollectionView:(FDShareCenterCollectionView *)arg1 needResize:(struct CGSize)arg2;
- (void)shareCenterCollectionViewDidClickAdd:(FDShareCenterCollectionView *)arg1;
- (void)shareCenterCollectionView:(FDShareCenterCollectionView *)arg1 didClickMemberAtIndex:(unsigned long long)arg2;
- (FDShareCenterAccountBookMember *)shareCenterCollectionView:(FDShareCenterCollectionView *)arg1 participantAtIndex:(unsigned long long)arg2;
@end

