//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class FDShareCenterCollectionViewEditItem, NSMutableArray;

@interface FDShareCenterCollectionView : UIView
{
    _Bool _editing;
    _Bool _canEdit;
    _Bool _clicking;
    id <FDShareCenterCollectionViewDelegate> _delegate;
    long long _participantCount;
    NSMutableArray *_memberItems;
    FDShareCenterCollectionViewEditItem *_addItem;
    FDShareCenterCollectionViewEditItem *_removeItem;
    struct FDShareCenterCollectionViewItemGeometry _itemGeometry;
}

+ (void)loadMember:(id)arg1 forMemberItem:(id)arg2;
@property(nonatomic) _Bool clicking; // @synthesize clicking=_clicking;
@property(nonatomic) struct FDShareCenterCollectionViewItemGeometry itemGeometry; // @synthesize itemGeometry=_itemGeometry;
@property(retain, nonatomic) FDShareCenterCollectionViewEditItem *removeItem; // @synthesize removeItem=_removeItem;
@property(retain, nonatomic) FDShareCenterCollectionViewEditItem *addItem; // @synthesize addItem=_addItem;
@property(retain, nonatomic) NSMutableArray *memberItems; // @synthesize memberItems=_memberItems;
@property(nonatomic) long long participantCount; // @synthesize participantCount=_participantCount;
@property(nonatomic) _Bool canEdit; // @synthesize canEdit=_canEdit;
@property(nonatomic, getter=isEditing) _Bool editing; // @synthesize editing=_editing;
@property(nonatomic) __weak id <FDShareCenterCollectionViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)handleClickTouch:(id)arg1;
- (void)layoutItems;
- (void)updateItemGeometry;
- (void)updateEditItems;
- (_Bool)shouldShowRemove;
- (_Bool)shouldShowAdd;
- (void)updateMemberItems;
- (void)reloadParticipantAtIndex:(long long)arg1;
- (void)reloadData;
- (void)layoutSubviews;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

