//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextField.h"

@class UIView;

@interface FDTextField : UITextField
{
    UIView *_placeHolderView;
}

@property(readonly, nonatomic) UIView *placeHolderView; // @synthesize placeHolderView=_placeHolderView;
- (void).cxx_destruct;
- (void)handleDidEndEditingNotification:(id)arg1;
- (void)handleDidBeginEditingNotification:(id)arg1;
- (void)setText:(id)arg1;
- (void)layoutSubviews;
- (void)registerNotifications:(_Bool)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

