//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FDWeChatAPIManager, NSString;

@protocol FDWeChatAPIManagerDelegate <NSObject>

@optional
- (void)weChatAPIManagerDidAuthorizedSuccessfully:(FDWeChatAPIManager *)arg1;
- (void)weChatAPIManager:(FDWeChatAPIManager *)arg1 didRecivedPayResponseUnsuccessfullyWithErrorMessage:(NSString *)arg2;
- (void)weChatAPIManagerDidRecivedPayResponseSuccessfully:(FDWeChatAPIManager *)arg1;
- (void)weChatAPIManager:(FDWeChatAPIManager *)arg1 didRecivedShareResponseUnsuccessfullyWithErrorMessage:(NSString *)arg2;
- (void)weChatAPIManagerDidRecivedShareResponseSuccessfully:(FDWeChatAPIManager *)arg1;
@end

