//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FDWebView, NSError, NSURLRequest;

@protocol FDWebViewDelegate <NSObject>

@optional
- (void)webView:(FDWebView *)arg1 didFailLoadWithError:(NSError *)arg2;
- (void)webViewDidFinishLoad:(FDWebView *)arg1;
- (void)webViewDidStartLoad:(FDWebView *)arg1;
- (_Bool)webView:(FDWebView *)arg1 shouldStartLoadWithRequest:(NSURLRequest *)arg2 navigationType:(long long)arg3;
- (void)webViewStyleDidChanged:(FDWebView *)arg1;
@end

