//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FeedbackConnection, NSError, NSString;

@protocol FeedbackConnectionDelegate <NSObject>
- (void)feedbackConnection:(FeedbackConnection *)arg1 didSuccessWithString:(NSString *)arg2;
- (void)feedbackConnection:(FeedbackConnection *)arg1 didFailWithError:(NSError *)arg2;
@end

