//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BillFilterViewController.h"

#import "SearchExecutor.h"

@class NSMutableArray;

@interface FilterViewControllerWithAllTime : BillFilterViewController <SearchExecutor>
{
    NSMutableArray *_accountVos;
    NSMutableArray *_categoryVos;
    NSMutableArray *_projectVos;
    NSMutableArray *_corporationVos;
    NSMutableArray *_memberVos;
    id <FilterViewControllerWithAllTimeProtocol> _filterAllTimeDelegate;
}

+ (void)filterWithReportViewController:(id)arg1 config:(id)arg2;
@property(nonatomic) __weak id <FilterViewControllerWithAllTimeProtocol> filterAllTimeDelegate; // @synthesize filterAllTimeDelegate=_filterAllTimeDelegate;
@property(retain, nonatomic) NSMutableArray *memberVos; // @synthesize memberVos=_memberVos;
@property(retain, nonatomic) NSMutableArray *corporationVos; // @synthesize corporationVos=_corporationVos;
@property(retain, nonatomic) NSMutableArray *projectVos; // @synthesize projectVos=_projectVos;
@property(retain, nonatomic) NSMutableArray *categoryVos; // @synthesize categoryVos=_categoryVos;
@property(retain, nonatomic) NSMutableArray *accountVos; // @synthesize accountVos=_accountVos;
- (void).cxx_destruct;
- (void)backAction;
- (id)searchByFilter;
- (void)initializeFilterVos;
- (_Bool)isAllDate;
- (double)endTimeInterval;
- (double)startTimeInterval;
- (void)filterAction;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

