//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseTableViewController.h"

@class NSArray;

@interface FilterBaseMultiSelectionViewController : BaseTableViewController
{
    _Bool _firstLevelFullySelected;
    _Bool _firstLevelHalfFullySelected;
    _Bool _secondLevelFullySelected;
    _Bool _isSecondLevelCellShown;
    id <FilterBaseMultiSelectionViewControllerDelegate> _delegate;
    NSArray *_insertIndexPaths;
}

@property(retain, nonatomic) NSArray *insertIndexPaths; // @synthesize insertIndexPaths=_insertIndexPaths;
@property(nonatomic) _Bool isSecondLevelCellShown; // @synthesize isSecondLevelCellShown=_isSecondLevelCellShown;
@property(nonatomic) __weak id <FilterBaseMultiSelectionViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool secondLevelFullySelected; // @synthesize secondLevelFullySelected=_secondLevelFullySelected;
@property(nonatomic) _Bool firstLevelHalfFullySelected; // @synthesize firstLevelHalfFullySelected=_firstLevelHalfFullySelected;
@property(nonatomic) _Bool firstLevelFullySelected; // @synthesize firstLevelFullySelected=_firstLevelFullySelected;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (unsigned long long)numberOfInsertedCell;
- (unsigned long long)numberOfSecondLevelSelectedData;
- (unsigned long long)numberOfSecondLevelData;
- (unsigned long long)numberOfFirstLevelSelectedData;
- (unsigned long long)numberOfFirstLevelData;
- (id)tableView:(id)arg1 commonSelectionCellForRowAtIndexPath:(id)arg2;
- (void)didSelectCommonSelectionCellForRowAtIndexPath:(id)arg1;
- (void)setCheckMarkInCell:(id)arg1;
- (id)reusableAllSelectionCellWithCellIdentifier:(id)arg1;
- (id)tableView:(id)arg1 allSelectionCellForRowAtIndexPath:(id)arg2;
- (void)didSelectAllSelectionCellAction;
- (_Bool)isAllSelectionSection:(long long)arg1;
- (_Bool)isIndexPathForAllSelectionCell:(id)arg1;
- (void)refreshSelectionStates;
- (void)batchSelect:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;

@end

