//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSOperationQueue;

@interface FinanceMarketResourcesZipDownloader : NSObject
{
    NSOperationQueue *_queue;
    CDUnknownBlockType _completion;
}

@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(retain, nonatomic) NSOperationQueue *queue; // @synthesize queue=_queue;
- (void).cxx_destruct;
- (void)downloadZip:(id)arg1 MD5:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)init;

@end

