//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FinanceWalletNonIconCell, NSIndexPath, NSString;

@protocol FinanceWalletNonIconCellDataSource <NSObject>
- (NSIndexPath *)indexPathForFinanceWalletNonIconCell:(FinanceWalletNonIconCell *)arg1;
- (NSString *)detailTextForFinanceWalletNonIconCell:(FinanceWalletNonIconCell *)arg1 indexPath:(NSIndexPath *)arg2;
- (NSString *)titleForFinanceWalletNonIconCell:(FinanceWalletNonIconCell *)arg1 indexPath:(NSIndexPath *)arg2;
@end

