//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView, UILabel;

@interface FinanceWalletServicePhoneFooterView : UIView
{
    id <FinanceWalletServicePhoneFooterViewDelegate> _delegate;
    id <FinanceWalletServicePhoneFooterViewDataSource> _dataSource;
    UIImageView *_phoneFooterView;
    UIView *_containerView;
    UIView *_helperView;
    UILabel *_wordsLabel;
    UILabel *_phoneLabel;
}

@property(retain, nonatomic) UILabel *phoneLabel; // @synthesize phoneLabel=_phoneLabel;
@property(retain, nonatomic) UILabel *wordsLabel; // @synthesize wordsLabel=_wordsLabel;
@property(retain, nonatomic) UIView *helperView; // @synthesize helperView=_helperView;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UIImageView *phoneFooterView; // @synthesize phoneFooterView=_phoneFooterView;
@property(nonatomic) __weak id <FinanceWalletServicePhoneFooterViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak id <FinanceWalletServicePhoneFooterViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)phoneFooterViewTapAction:(id)arg1;
- (void)updateConstraints;
- (id)initWithFrame:(struct CGRect)arg1;

@end

