//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class FinanceMarketProductLIstViewController, FinanceMarketProductListNoticeModel, NSArray;

@interface FinanceMarketProductTableCollectionCell : UICollectionViewCell
{
    NSArray *_listData;
    NSArray *_bottomData;
    FinanceMarketProductListNoticeModel *_notice;
    id <FinanceTableViewScrollDelegate><FinanceProductTableViewActionDelegate> _delegate;
    FinanceMarketProductLIstViewController *_controller;
}

@property(retain, nonatomic) FinanceMarketProductLIstViewController *controller; // @synthesize controller=_controller;
@property(nonatomic) __weak id <FinanceTableViewScrollDelegate><FinanceProductTableViewActionDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) FinanceMarketProductListNoticeModel *notice; // @synthesize notice=_notice;
@property(retain, nonatomic) NSArray *bottomData; // @synthesize bottomData=_bottomData;
@property(retain, nonatomic) NSArray *listData; // @synthesize listData=_listData;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

