//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FinancialTaskRewardViewControllerOutput.h"

@class NSString;

@interface FinancialTaskRewardInteractor : NSObject <FinancialTaskRewardViewControllerOutput>
{
    _Bool _hasUploadToBigDataCenter;
    id <FinancialTaskRewardInteractorOutput> _output;
    NSString *_lastSubtitle;
    long long *_currentTask;
}

@property(nonatomic) _Bool hasUploadToBigDataCenter; // @synthesize hasUploadToBigDataCenter=_hasUploadToBigDataCenter;
@property(nonatomic) long long *currentTask; // @synthesize currentTask=_currentTask;
@property(copy, nonatomic) NSString *lastSubtitle; // @synthesize lastSubtitle=_lastSubtitle;
@property(nonatomic) __weak id <FinancialTaskRewardInteractorOutput> output; // @synthesize output=_output;
- (void).cxx_destruct;
- (double)fontSize;
- (id)rewardViewControllerViewModelWithSubtitle:(id)arg1 andTask:(long long)arg2;
- (_Bool)shouldShowRewardWithTask:(long long)arg1;
- (void)setAllCompletedTasksToRewarded;
- (void)querySubTitle:(CDUnknownBlockType)arg1;
- (void)reloadViewModel;
- (void)judgeShouldShowRewardOrNotWithTask:(long long)arg1;
- (void)showRewardWithTask:(long long)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

