//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class NSString, UIImageView, UILabel;

@interface FinanceMarketCollectionViewCell : UICollectionViewCell
{
    NSString *_iconString;
    NSString *_text;
    UIImageView *_imageView;
    UILabel *_textLabel;
}

@property(nonatomic) __weak UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(nonatomic) __weak UIImageView *imageView; // @synthesize imageView=_imageView;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(copy, nonatomic) NSString *iconString; // @synthesize iconString=_iconString;
- (void).cxx_destruct;
- (void)awakeFromNib;

@end

