//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UILabel;

@interface FinanceWalletServiceAlertView : UIView
{
    UIView *_keyView;
    UIView *_topHelperView;
    UILabel *_titleLabel;
    UIButton *_closeButton;
    UILabel *_serviceTitleLabel;
    UILabel *_serviceContentLabel;
    UILabel *_serviceTipsLabel;
    UIButton *_confirmButton;
    UIView *_topSpliteLineView;
    UIView *_bottomSpliteLineView;
}

@property(retain, nonatomic) UIView *bottomSpliteLineView; // @synthesize bottomSpliteLineView=_bottomSpliteLineView;
@property(retain, nonatomic) UIView *topSpliteLineView; // @synthesize topSpliteLineView=_topSpliteLineView;
@property(retain, nonatomic) UIButton *confirmButton; // @synthesize confirmButton=_confirmButton;
@property(retain, nonatomic) UILabel *serviceTipsLabel; // @synthesize serviceTipsLabel=_serviceTipsLabel;
@property(retain, nonatomic) UILabel *serviceContentLabel; // @synthesize serviceContentLabel=_serviceContentLabel;
@property(retain, nonatomic) UILabel *serviceTitleLabel; // @synthesize serviceTitleLabel=_serviceTitleLabel;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *topHelperView; // @synthesize topHelperView=_topHelperView;
@property(retain, nonatomic) UIView *keyView; // @synthesize keyView=_keyView;
- (void).cxx_destruct;
- (void)closeAction:(id)arg1;
- (void)handleCloseButtonClicked:(id)arg1;
- (void)handleConfirmButtonClicked:(id)arg1;
- (void)layoutSubviews;
- (void)updateConstraints;
- (id)initWithFrame:(struct CGRect)arg1 contentDictionary:(id)arg2;

@end

