//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton;

@interface FinanceBottomUnLoginView : UIView
{
    UIView *_loginView;
    UIButton *_lotteryButton;
}

@property(retain, nonatomic) UIButton *lotteryButton; // @synthesize lotteryButton=_lotteryButton;
@property(retain, nonatomic) UIView *loginView; // @synthesize loginView=_loginView;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

