//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AccountDaoHelper, KDAccountFix, NSArray, NSDecimalNumber, NSMutableArray, TransactionDaoHelper;

@interface FixTransactionRecord : NSObject
{
    NSMutableArray *_handledTransactions;
    long long _adjustAccountId;
    KDAccountFix *_adjustAccount;
    NSDecimalNumber *_originalAdjustAccountBalance;
    double _adjustTradeTime;
    NSArray *_allTransactions;
    struct sqlite3 *database;
    AccountDaoHelper *_accountDao;
    TransactionDaoHelper *_transactionDao;
}

@property(retain, nonatomic) NSDecimalNumber *originalAdjustAccountBalance; // @synthesize originalAdjustAccountBalance=_originalAdjustAccountBalance;
@property(retain, nonatomic) TransactionDaoHelper *transactionDao; // @synthesize transactionDao=_transactionDao;
@property(retain, nonatomic) AccountDaoHelper *accountDao; // @synthesize accountDao=_accountDao;
@property(retain, nonatomic) NSArray *allTransactions; // @synthesize allTransactions=_allTransactions;
@property(retain, nonatomic) NSMutableArray *handledTransactions; // @synthesize handledTransactions=_handledTransactions;
- (void).cxx_destruct;
- (void)fixMoneyForTransaction:(id)arg1;
- (_Bool)execSql:(id)arg1;
- (long long)createAdjustAccount;
@property(readonly, nonatomic) __weak KDAccountFix *adjustAccount;
- (long long)idFromAdjustAccount;
- (id)generateTransactionRelation;
- (id)transactonsWithRelation:(id)arg1 exceptForId:(long long)arg2;
- (_Bool)resetRelationFieldForTransactions:(id)arg1;
- (_Bool)updateRelationForTransaction:(id)arg1;
- (_Bool)copyAccountToTransactionWithId:(long long)arg1 fromTransaction:(id)arg2;
- (_Bool)updateBuyerAccountId:(long long)arg1 SellerAccountId:(long long)arg2 withTransactionId:(long long)arg3;
- (_Bool)updateAccountForTransaction:(id)arg1;
- (void)fillAndInsertTransferType:(int)arg1 forTransaction:(id)arg2 withSellerId:(long long)arg3 buyerId:(long long)arg4;
- (void)fillAndInsertTransferInForTransaction:(id)arg1 withSellerId:(long long)arg2 buyerId:(long long)arg3;
- (void)fillAndInsertTransferOutForTransaction:(id)arg1 withSellerId:(long long)arg2 buyerId:(long long)arg3;
- (void)fillAndInsertTransferType:(int)arg1 forTransaction:(id)arg2;
- (void)fillAndInsertTransferInForTransaction:(id)arg1;
- (void)fillAndInsertTransferOutForTransaction:(id)arg1;
- (void)fillAndInsertFuZhaiForTransaction:(id)arg1;
- (void)fillSellerAccountIntoTransaction:(id)arg1;
- (void)fillBuyerAccountIntoTransaction:(id)arg1;
- (void)fixHuanChu:(id)arg1;
- (void)fixHuanRu:(id)arg1;
- (void)fixJieChu:(id)arg1;
- (void)fixJieRu:(id)arg1;
- (void)fixTransferOutZhaiQuanAndFuZhai:(id)arg1 withOthers:(id)arg2;
- (void)fixTransferOutZhaiQuanAndZiChan:(id)arg1 withOthers:(id)arg2;
- (void)fixTransferOutFuZhaiAndZiChan:(id)arg1 withOthers:(id)arg2;
- (void)fixTransferOutZiChanAndZhaiQuan:(id)arg1 withOthers:(id)arg2;
- (void)fixTransferOutZiChanAndFuZhai:(id)arg1 withOthers:(id)arg2;
- (void)fixTransferOutAllZiChan:(id)arg1 withOthers:(id)arg2;
- (void)fixTransferOut:(id)arg1;
- (void)fixTransferInZhaiQuanAndFuZhai:(id)arg1 withOthers:(id)arg2;
- (void)fixTransferInZhaiQuanAndZiChan:(id)arg1 withOthers:(id)arg2;
- (void)fixTransferInFuZhaiAndZiChan:(id)arg1 withOthers:(id)arg2;
- (void)fixTransferInZiChanAndZhaiQuan:(id)arg1 withOthers:(id)arg2;
- (void)fixTransferInZiChanAndFuZhai:(id)arg1 withOthers:(id)arg2;
- (void)fixTransferInAllZiChan:(id)arg1 withOthers:(id)arg2;
- (void)fixTransferIn:(id)arg1;
- (void)fixLiabilityBalanceChanged:(id)arg1;
- (void)fixCreditBalanceChanged:(id)arg1;
- (void)fixBalanceChanged:(id)arg1;
- (void)fixIncome:(id)arg1;
- (void)fixExpense:(id)arg1;
- (void)loadAllTransactions;
- (void)resetAdjustAccountBalance;
- (void)fix;
- (id)init;

@end

