//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSDateFormatter, NSMutableArray, NSString, UIButton, UILabel, UITableView;

@interface FlatTemplateListViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
{
    UITableView *_tableView;
    id <FlatTemplateListViewControllerDelegate> _delegate;
    UILabel *_titleLabel;
    UIButton *_editButton;
    UIButton *_addButton;
    NSMutableArray *_templateInfoArr;
    NSMutableArray *_incomeTemplateArr;
    NSMutableArray *_payoutTemplateArr;
    NSMutableArray *_transferTemplateArr;
    NSMutableArray *_holderTemplateArr;
    unsigned long long _incomeNullObjectCount;
    NSDateFormatter *_dateFormatter;
    NSArray *_repeatIntervals;
}

@property(retain, nonatomic) NSArray *repeatIntervals; // @synthesize repeatIntervals=_repeatIntervals;
@property(retain, nonatomic) NSDateFormatter *dateFormatter; // @synthesize dateFormatter=_dateFormatter;
@property(nonatomic) unsigned long long incomeNullObjectCount; // @synthesize incomeNullObjectCount=_incomeNullObjectCount;
@property(retain, nonatomic) NSMutableArray *holderTemplateArr; // @synthesize holderTemplateArr=_holderTemplateArr;
@property(retain, nonatomic) NSMutableArray *transferTemplateArr; // @synthesize transferTemplateArr=_transferTemplateArr;
@property(retain, nonatomic) NSMutableArray *payoutTemplateArr; // @synthesize payoutTemplateArr=_payoutTemplateArr;
@property(retain, nonatomic) NSMutableArray *incomeTemplateArr; // @synthesize incomeTemplateArr=_incomeTemplateArr;
@property(retain, nonatomic) NSMutableArray *templateInfoArr; // @synthesize templateInfoArr=_templateInfoArr;
@property(retain, nonatomic) UIButton *addButton; // @synthesize addButton=_addButton;
@property(retain, nonatomic) UIButton *editButton; // @synthesize editButton=_editButton;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak id <FlatTemplateListViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (id)templateArrayAtSection:(long long)arg1;
- (id)templateInfoAtIndexPath:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (_Bool)deleteTemplate:(long long)arg1;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 targetIndexPathForMoveFromRowAtIndexPath:(id)arg2 toProposedIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)getTemplateInfo;
- (_Bool)hasData;
- (void)delayReloadDataAfterDeleteRow;
- (void)addAction:(id)arg1;
- (void)editAction:(id)arg1;
- (void)reloadData;
- (void)initParameter;
- (void)setupUI;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

