//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "AutoCompleteViewDelegate.h"
#import "UITextFieldDelegate.h"

@class AutoCompleteTextField, NSArray, NSString;

@interface ForgetPasswordController : UIViewController <AutoCompleteViewDelegate, UITextFieldDelegate>
{
    NSArray *_emailsProviders;
    _Bool _isEmail;
    _Bool _isTel;
    AutoCompleteTextField *_nameTextField;
}

+ (void)sendRequest:(id)arg1 isEmail:(_Bool)arg2 callback:(CDUnknownBlockType)arg3;
@property(retain, nonatomic) AutoCompleteTextField *nameTextField; // @synthesize nameTextField=_nameTextField;
- (void).cxx_destruct;
- (void)pushToTelResult:(id)arg1 applyFloodGuard:(_Bool)arg2;
- (void)processWithSuccess:(_Bool)arg1 fatal:(_Bool)arg2 info:(id)arg3;
- (void)nextAction;
- (void)didReceiveMemoryWarning;
- (id)autoCompleteViewDataSource;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (id)textFieldWithPlaceholder:(id)arg1 secure:(_Bool)arg2 origin:(struct CGPoint)arg3;
- (void)configTextField:(id)arg1 withPlaceholder:(id)arg2 secure:(_Bool)arg3 origin:(struct CGPoint)arg4;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

