//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ForumTaskManager.h"

@class NSString;

@interface ForumTaskManagerImpl : NSObject <ForumTaskManager>
{
}

- (void)forumTasksWithCompletinCallback:(CDUnknownBlockType)arg1;
- (void)setCreditForServerWithTaskName:(id)arg1 completinCallback:(CDUnknownBlockType)arg2;
- (void)setCreditForServerWithID:(long long)arg1 completinCallback:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

