//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface FundChartData : NSObject
{
    int _fundUpDownFlag;
    int _needDrawLinePointsCount;
    int _investmentItemType;
    NSString *_mymoneyMillionIndexTitle;
    NSString *_mymoneyMillionIndexValue;
    NSString *_topFundValueTitle;
    NSString *_fundLastDayValue;
    NSString *_summaryFundTitle;
    NSString *_summaryFundValue;
    NSString *_fundMonetaryUnit;
    NSString *_fundUpDownValue;
    NSString *_fundUpDownPercent;
    NSArray *_fundDaysArray;
    NSArray *_fundDaysTimeIntervalArray;
    NSArray *_leftValueRuleDataArray;
    NSArray *_fund5YearLinePoints;
    NSString *_fund5YearLineTitle;
    NSArray *_fundYEBLinePoints;
    NSString *_fundYEBLineTitle;
    NSArray *_fundTrustLinePoints;
    NSString *_fundTrustLineTitle;
    NSArray *_fundLinePoints;
}

@property(nonatomic) int investmentItemType; // @synthesize investmentItemType=_investmentItemType;
@property(nonatomic) int needDrawLinePointsCount; // @synthesize needDrawLinePointsCount=_needDrawLinePointsCount;
@property(retain, nonatomic) NSArray *fundLinePoints; // @synthesize fundLinePoints=_fundLinePoints;
@property(retain, nonatomic) NSString *fundTrustLineTitle; // @synthesize fundTrustLineTitle=_fundTrustLineTitle;
@property(retain, nonatomic) NSArray *fundTrustLinePoints; // @synthesize fundTrustLinePoints=_fundTrustLinePoints;
@property(retain, nonatomic) NSString *fundYEBLineTitle; // @synthesize fundYEBLineTitle=_fundYEBLineTitle;
@property(retain, nonatomic) NSArray *fundYEBLinePoints; // @synthesize fundYEBLinePoints=_fundYEBLinePoints;
@property(retain, nonatomic) NSString *fund5YearLineTitle; // @synthesize fund5YearLineTitle=_fund5YearLineTitle;
@property(retain, nonatomic) NSArray *fund5YearLinePoints; // @synthesize fund5YearLinePoints=_fund5YearLinePoints;
@property(retain, nonatomic) NSArray *leftValueRuleDataArray; // @synthesize leftValueRuleDataArray=_leftValueRuleDataArray;
@property(retain, nonatomic) NSArray *fundDaysTimeIntervalArray; // @synthesize fundDaysTimeIntervalArray=_fundDaysTimeIntervalArray;
@property(retain, nonatomic) NSArray *fundDaysArray; // @synthesize fundDaysArray=_fundDaysArray;
@property(nonatomic) int fundUpDownFlag; // @synthesize fundUpDownFlag=_fundUpDownFlag;
@property(retain, nonatomic) NSString *fundUpDownPercent; // @synthesize fundUpDownPercent=_fundUpDownPercent;
@property(retain, nonatomic) NSString *fundUpDownValue; // @synthesize fundUpDownValue=_fundUpDownValue;
@property(retain, nonatomic) NSString *fundMonetaryUnit; // @synthesize fundMonetaryUnit=_fundMonetaryUnit;
@property(retain, nonatomic) NSString *summaryFundValue; // @synthesize summaryFundValue=_summaryFundValue;
@property(retain, nonatomic) NSString *summaryFundTitle; // @synthesize summaryFundTitle=_summaryFundTitle;
@property(retain, nonatomic) NSString *fundLastDayValue; // @synthesize fundLastDayValue=_fundLastDayValue;
@property(retain, nonatomic) NSString *topFundValueTitle; // @synthesize topFundValueTitle=_topFundValueTitle;
@property(retain, nonatomic) NSString *mymoneyMillionIndexValue; // @synthesize mymoneyMillionIndexValue=_mymoneyMillionIndexValue;
@property(retain, nonatomic) NSString *mymoneyMillionIndexTitle; // @synthesize mymoneyMillionIndexTitle=_mymoneyMillionIndexTitle;
- (void).cxx_destruct;
- (id)init;

@end

