//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GlobalBaseDao.h"

#import "FundDao.h"

@class NSString;

@interface FundDaoImpl : GlobalBaseDao <FundDao>
{
}

- (id)fundsWithCodes:(id)arg1;
- (int)dumpTableTFund;
- (int)insertAllFundRecords:(id)arg1;
- (id)fundWithCode:(id)arg1;
- (_Bool)deleteFundWithCode:(id)arg1;
- (id)allFunds;
- (_Bool)insertFund:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

