//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class FundSummaryChartData, KDActivityIndicatorMessageView, KDFundChartView, NSMutableArray, NSString, UIButton, UIImageView, UILabel, UITableView, UIView;

@interface FundCenterViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
{
    KDFundChartView *fundReportChartView;
    UITableView *fundListTableView;
    NSMutableArray *fundContentArray;
    FundSummaryChartData *chartData;
    _Bool hasRunChartAnimation;
    _Bool hasShowFullListTableView;
    UIView *rightBarView;
    UIButton *editBarButton;
    UIButton *middleExpandButton;
    UILabel *tableHeaderRightLabel;
    int currentShowProfitType;
    double totalMarketValue;
    double totalHoldingCostValue;
    _Bool hasViewDidAppear;
    _Bool hasFetchQuotesForFund;
    _Bool viewFirstDidAppear;
    UIImageView *noRecordImageView;
    UILabel *noRecordtipsLabel;
    double dayBeforeYesterDayMarketValue;
    double fundTradeCenterChartReportHeight;
    KDActivityIndicatorMessageView *requestIndicatorView;
}

- (void).cxx_destruct;
- (void)showInvalidFundDatabaseAlert;
- (void)handleChartReportSwipeNotify:(id)arg1;
- (void)unregisterChartReportSwipeNotify;
- (void)registerChartReportSwipeNotify;
- (void)handleQuoteDateChangeNotify:(id)arg1;
- (void)unregisterQuoteDateChangeNotify;
- (void)registerQuoteDateChangeNotify;
- (void)loadFundHoldingData;
- (void)setupMockData;
- (void)adaptToScreenSize;
- (void)storeFundsRecordToDatabase:(id)arg1;
- (void)caculateFundChartData;
- (void)caculateAllFundProfitLoss;
- (void)caculateAllFundHoldingCost;
- (void)caculateFundReportData:(id)arg1;
- (void)caculateFundQuoteData:(id)arg1;
- (void)caculateYEBQuoteData:(id)arg1;
- (void)caculateFundDateRule:(id)arg1;
- (void)caculteAllFundMarketValue:(id)arg1;
- (void)showNetworkErrorToast;
- (void)handleFetchQuotesForFundsCallback:(id)arg1;
- (void)handleFetchAllFundsCallback:(id)arg1;
- (void)handleFetchQuotesForStocksCallback:(id)arg1;
- (void)handleFetchAllStocksCallback:(id)arg1;
- (void)fetchQuoteForFunds:(id)arg1;
- (void)fetchAllFunds;
- (void)unregisterRemoteServiceCallback;
- (void)registerRemoteServiceCallback;
- (void)expandTableView:(id)arg1;
- (void)handleTableHeaderTap:(id)arg1;
- (void)setEditingAction;
- (void)switchProfitTypeInCell:(int)arg1;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)addAction;
- (void)createListContent:(id)arg1;
- (void)createRequestIndicatorView;
- (void)createFundListReport;
- (void)createFundReportChart;
- (void)setupNavigationBar;
- (void)loadView;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

