//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "MFMailComposeViewControllerDelegate.h"
#import "MFMessageComposeViewControllerDelegate.h"

@class NSString, RemoteAccountService, UIButton, UILabel;

@interface GenerateRedeemCodeController : UIViewController <MFMailComposeViewControllerDelegate, MFMessageComposeViewControllerDelegate>
{
    RemoteAccountService *_remoteService;
    UILabel *_redeemCodeLabel;
    UIButton *_emailButton;
    UIButton *_smsButton;
    UIButton *_saveToPasteboardButton;
    NSString *_invitationCode;
    NSString *_email;
}

+ (void)sendStatistic;
@property(retain, nonatomic) NSString *email; // @synthesize email=_email;
@property(retain, nonatomic) NSString *invitationCode; // @synthesize invitationCode=_invitationCode;
@property(retain, nonatomic) UIButton *saveToPasteboardButton; // @synthesize saveToPasteboardButton=_saveToPasteboardButton;
@property(retain, nonatomic) UIButton *smsButton; // @synthesize smsButton=_smsButton;
@property(retain, nonatomic) UIButton *emailButton; // @synthesize emailButton=_emailButton;
@property(retain, nonatomic) UILabel *redeemCodeLabel; // @synthesize redeemCodeLabel=_redeemCodeLabel;
@property(retain, nonatomic) RemoteAccountService *remoteService; // @synthesize remoteService=_remoteService;
- (void).cxx_destruct;
- (void)messageComposeViewController:(id)arg1 didFinishWithResult:(int)arg2;
- (void)handleCopyToClipboardButtonClicked:(id)arg1;
- (void)smsAction;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
- (void)displayComposerSheet;
- (void)emailAction;
- (void)didReceiveMemoryWarning;
- (void)setupUI;
- (void)viewDidLoad;
- (id)initWithInvitationCode:(id)arg1 email:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

