//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GlobalBusinessFactory : NSObject
{
}

+ (id)sharedInstance;
@property(readonly, nonatomic) __weak id <GlobalTaskManager> globalTaskManager;
@property(readonly, nonatomic) __weak id <GlobalTaskTrigger> globalTaskTrigger;
@property(readonly, nonatomic) __weak id <GlobalUpgradeService> globalUpgradeService;
@property(readonly, nonatomic) __weak id <LocalMessageService> localMesageService;
@property(readonly, nonatomic) __weak id <PushMessageService> pushMessageService;

@end

