//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GlobalUser, NSString;

@interface GlobalMessage : NSObject
{
    _Bool _hasRead;
    long long _oid;
    unsigned long long _type;
    unsigned long long _level;
    unsigned long long _handleResult;
    NSString *_title;
    NSString *_content;
    double _createdTime;
    NSString *_extraParams;
    NSString *_userDefinedParams;
    unsigned long long _scope;
    GlobalUser *_sender;
    GlobalUser *_receiver;
    NSString *_identifier;
}

+ (id)postIdFromCustomArgs:(id)arg1;
+ (long long)urlTypeFromCustomArgs:(id)arg1;
+ (id)messageWithOid:(long long)arg1 type:(unsigned long long)arg2 level:(unsigned long long)arg3 handleResult:(unsigned long long)arg4 title:(id)arg5 content:(id)arg6 createdTime:(double)arg7 hasRead:(_Bool)arg8 extraParams:(id)arg9 userDefinedParams:(id)arg10 scope:(unsigned long long)arg11 sender:(id)arg12 receiver:(id)arg13;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(retain, nonatomic) GlobalUser *receiver; // @synthesize receiver=_receiver;
@property(retain, nonatomic) GlobalUser *sender; // @synthesize sender=_sender;
@property(nonatomic) unsigned long long scope; // @synthesize scope=_scope;
@property(retain, nonatomic) NSString *userDefinedParams; // @synthesize userDefinedParams=_userDefinedParams;
@property(retain, nonatomic) NSString *extraParams; // @synthesize extraParams=_extraParams;
@property(nonatomic) _Bool hasRead; // @synthesize hasRead=_hasRead;
@property(nonatomic) double createdTime; // @synthesize createdTime=_createdTime;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) unsigned long long handleResult; // @synthesize handleResult=_handleResult;
@property(nonatomic) unsigned long long level; // @synthesize level=_level;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(nonatomic) long long oid; // @synthesize oid=_oid;
- (void).cxx_destruct;
- (id)extraParamsWithContentUrl:(id)arg1;
- (id)removePrefixAndSuffixSpaceString:(id)arg1;
- (id)toNotificationMessage;
- (id)dictForUser:(id)arg1;
- (id)JSONString;
- (id)description;
- (id)initWithOid:(long long)arg1 type:(unsigned long long)arg2 level:(unsigned long long)arg3 handleResult:(unsigned long long)arg4 title:(id)arg5 content:(id)arg6 createdTime:(double)arg7 hasRead:(_Bool)arg8 extraParams:(id)arg9 userDefinedParams:(id)arg10 scope:(unsigned long long)arg11 sender:(id)arg12 receiver:(id)arg13;

@end

