//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AccountBookTemplate, NSArray, NSString;

@protocol GlobalAccountBookTemplateDao <NSObject>
- (void)rollbackTransaction;
- (void)endTransaction;
- (void)beginTransaction;
- (NSArray *)templates;
- (AccountBookTemplate *)templateWithTemplateID:(NSString *)arg1;
- (_Bool)updateTemplatesOrder:(NSArray *)arg1;
- (_Bool)updateTemplate:(AccountBookTemplate *)arg1;
- (_Bool)removeTemplate:(AccountBookTemplate *)arg1;
- (_Bool)safetyRemoveTemplate:(AccountBookTemplate *)arg1;
- (_Bool)safetyRemoveTemplateWithTemplateID:(NSString *)arg1;
- (_Bool)removeTemplateWithTemplateID:(NSString *)arg1;
- (_Bool)safetyInsertTemplate:(AccountBookTemplate *)arg1;
- (_Bool)insertTemplate:(AccountBookTemplate *)arg1;
@end

