//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface HomeBottomboardFinanceData : NSObject
{
    NSString *_profitToday;
    NSString *_totalAmount;
}

@property(retain, nonatomic) NSString *totalAmount; // @synthesize totalAmount=_totalAmount;
@property(retain, nonatomic) NSString *profitToday; // @synthesize profitToday=_profitToday;
- (void).cxx_destruct;
- (id)initWithProfitTodayString:(id)arg1 totalAmountString:(id)arg2;

@end

