//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseTableViewController.h"

#import "BillBatchDeleteViewControllerDelegate.h"
#import "DirtyDataDetectable.h"
#import "FloatBackgroundWallViewDelegate.h"
#import "ImportViewControllerDelegate.h"
#import "ScoreBoardLabelDelegate.h"

@class AccountEyeButton, AccountVo, ExpenseVo, FDAccountHeaderScrollView, FloatBackgroundHeaderView, FloatBackgroundWallView, NSArray, NSDecimalNumber, NSDictionary, NSIndexPath, NSMutableArray, NSMutableDictionary, NSString, UIButton, UIView;

@interface HomeAccountSelectionViewController : BaseTableViewController <ImportViewControllerDelegate, FloatBackgroundWallViewDelegate, ScoreBoardLabelDelegate, DirtyDataDetectable, BillBatchDeleteViewControllerDelegate>
{
    _Bool _isCreditAccounts;
    double _minBalance;
    double _maxBalance;
    _Bool _hasShownImportView;
    _Bool _isReimburse;
    _Bool _isBaseHiddenEdit;
    _Bool _isTransacionalAccountShow;
    _Bool _isEditing;
    _Bool _isSettingView;
    _Bool _hasRegistedKVO;
    _Bool _isEnterForum;
    _Bool _hasShowAccountAddView;
    NSString *_mycardImportString;
    NSString *_version;
    NSString *_importDirection;
    NSString *_filteredCardDataJSONString;
    id <HomeAccountSelectionViewControllerProtocol> _delegate;
    ExpenseVo *_expenseVo;
    NSMutableDictionary *_data;
    NSMutableArray *_accountGroupBalanceArr;
    NSMutableArray *_cacheOfHeaders;
    UIView *_rightBarView;
    UIButton *_editBarButton;
    NSMutableArray *_sectionColors;
    NSMutableArray *_rowColors;
    NSString *_importAction;
    NSString *_importMode;
    NSDecimalNumber *_allInvestmentAccountMarketValue;
    NSDecimalNumber *_balance;
    NSDecimalNumber *_asset;
    NSDecimalNumber *_liability;
    NSIndexPath *_indexPathToDelete;
    NSString *_fromApp;
    NSString *_defaultCurrencyCode;
    NSArray *_duplicateAccountHandlers;
    NSArray *_duplicateAccountIdsToRename;
    FloatBackgroundHeaderView *_tableHeaderView;
    FloatBackgroundWallView *_wallView;
    AccountEyeButton *_eyeButton;
    NSString *_originNetAssets;
    NSString *_originAssets;
    NSString *_originDebt;
    FDAccountHeaderScrollView *_scrollHeader;
    NSMutableDictionary *_accountInvestmentAmount;
    NSMutableDictionary *_compositedAccountAmounts;
    NSDecimalNumber *_headerBalance;
    AccountVo *_toBeDeletedAccountVo;
    NSDictionary *_allAccountMarketValueCache;
}

+ (id)calculateBalanceWithAsset:(id)arg1 andLiability:(id)arg2;
+ (id)calculateLiability:(_Bool)arg1;
+ (id)calculateAsset:(id)arg1 isTransacionalAccountShow:(_Bool)arg2;
+ (id)calculateAllInvestmentAccountMarketValue;
@property(nonatomic) _Bool hasShowAccountAddView; // @synthesize hasShowAccountAddView=_hasShowAccountAddView;
@property(retain, nonatomic) NSDictionary *allAccountMarketValueCache; // @synthesize allAccountMarketValueCache=_allAccountMarketValueCache;
@property(nonatomic) _Bool isEnterForum; // @synthesize isEnterForum=_isEnterForum;
@property(retain, nonatomic) AccountVo *toBeDeletedAccountVo; // @synthesize toBeDeletedAccountVo=_toBeDeletedAccountVo;
@property(retain, nonatomic) NSDecimalNumber *headerBalance; // @synthesize headerBalance=_headerBalance;
@property(retain, nonatomic) NSMutableDictionary *compositedAccountAmounts; // @synthesize compositedAccountAmounts=_compositedAccountAmounts;
@property(retain, nonatomic) NSMutableDictionary *accountInvestmentAmount; // @synthesize accountInvestmentAmount=_accountInvestmentAmount;
@property(retain, nonatomic) FDAccountHeaderScrollView *scrollHeader; // @synthesize scrollHeader=_scrollHeader;
@property(retain, nonatomic) NSString *originDebt; // @synthesize originDebt=_originDebt;
@property(retain, nonatomic) NSString *originAssets; // @synthesize originAssets=_originAssets;
@property(retain, nonatomic) NSString *originNetAssets; // @synthesize originNetAssets=_originNetAssets;
@property(retain, nonatomic) AccountEyeButton *eyeButton; // @synthesize eyeButton=_eyeButton;
@property(retain, nonatomic) FloatBackgroundWallView *wallView; // @synthesize wallView=_wallView;
@property(retain, nonatomic) FloatBackgroundHeaderView *tableHeaderView; // @synthesize tableHeaderView=_tableHeaderView;
@property(retain, nonatomic) NSArray *duplicateAccountIdsToRename; // @synthesize duplicateAccountIdsToRename=_duplicateAccountIdsToRename;
@property(retain, nonatomic) NSArray *duplicateAccountHandlers; // @synthesize duplicateAccountHandlers=_duplicateAccountHandlers;
@property(retain, nonatomic) NSString *defaultCurrencyCode; // @synthesize defaultCurrencyCode=_defaultCurrencyCode;
@property(nonatomic) _Bool hasRegistedKVO; // @synthesize hasRegistedKVO=_hasRegistedKVO;
@property(retain, nonatomic) NSString *fromApp; // @synthesize fromApp=_fromApp;
@property(retain, nonatomic) NSIndexPath *indexPathToDelete; // @synthesize indexPathToDelete=_indexPathToDelete;
@property(nonatomic) _Bool isSettingView; // @synthesize isSettingView=_isSettingView;
@property(retain, nonatomic) NSDecimalNumber *liability; // @synthesize liability=_liability;
@property(retain, nonatomic) NSDecimalNumber *asset; // @synthesize asset=_asset;
@property(retain, nonatomic) NSDecimalNumber *balance; // @synthesize balance=_balance;
@property(retain, nonatomic) NSDecimalNumber *allInvestmentAccountMarketValue; // @synthesize allInvestmentAccountMarketValue=_allInvestmentAccountMarketValue;
@property(retain, nonatomic) NSString *importMode; // @synthesize importMode=_importMode;
@property(retain, nonatomic) NSString *importAction; // @synthesize importAction=_importAction;
@property(retain, nonatomic) NSMutableArray *rowColors; // @synthesize rowColors=_rowColors;
@property(retain, nonatomic) NSMutableArray *sectionColors; // @synthesize sectionColors=_sectionColors;
@property(retain, nonatomic) UIButton *editBarButton; // @synthesize editBarButton=_editBarButton;
@property(nonatomic) _Bool isEditing; // @synthesize isEditing=_isEditing;
@property(retain, nonatomic) UIView *rightBarView; // @synthesize rightBarView=_rightBarView;
@property(nonatomic) _Bool isTransacionalAccountShow; // @synthesize isTransacionalAccountShow=_isTransacionalAccountShow;
@property(retain, nonatomic) NSMutableArray *cacheOfHeaders; // @synthesize cacheOfHeaders=_cacheOfHeaders;
@property _Bool isBaseHiddenEdit; // @synthesize isBaseHiddenEdit=_isBaseHiddenEdit;
@property(retain, nonatomic) NSMutableArray *accountGroupBalanceArr; // @synthesize accountGroupBalanceArr=_accountGroupBalanceArr;
@property(retain, nonatomic) NSMutableDictionary *data; // @synthesize data=_data;
@property(retain, nonatomic) ExpenseVo *expenseVo; // @synthesize expenseVo=_expenseVo;
@property(nonatomic) __weak id <HomeAccountSelectionViewControllerProtocol> delegate; // @synthesize delegate=_delegate;
@property _Bool isReimburse; // @synthesize isReimburse=_isReimburse;
@property(retain, nonatomic) NSString *filteredCardDataJSONString; // @synthesize filteredCardDataJSONString=_filteredCardDataJSONString;
@property(retain, nonatomic) NSString *importDirection; // @synthesize importDirection=_importDirection;
@property(retain, nonatomic) NSString *version; // @synthesize version=_version;
@property(retain, nonatomic) NSString *mycardImportString; // @synthesize mycardImportString=_mycardImportString;
- (void).cxx_destruct;
- (void)needSetNavigationBarBackground:(id)arg1;
- (void)scoreBoardAnimationDidEnd;
- (void)scrollViewDidScroll:(id)arg1;
- (_Bool)containDirtyDataAfterSynced;
- (id)accountDictionaryAtSection:(long long)arg1;
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (id)tableView:(id)arg1 targetIndexPathForMoveFromRowAtIndexPath:(id)arg2 toProposedIndexPath:(id)arg3;
- (void)loadChartData;
- (void)refreshData;
- (void)refreshTable;
- (void)muteSwitchAction:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)hideAccountActionAtBase:(id)arg1;
- (id)typeIdWithUrl:(id)arg1;
- (void)querySpecialBoardWithName:(id)arg1 success:(CDUnknownBlockType)arg2;
- (void)enterForumAction;
- (void)addAccount;
- (void)import:(id)arg1 cancelImport:(_Bool)arg2;
- (void)import:(id)arg1 importJSON:(id)arg2;
- (void)removeActivityView;
- (void)finishImportAction:(id)arg1;
- (void)beginImportMycardData;
- (void)beginImportMycardDataAction;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)billBatchDeleteDidFinish:(id)arg1;
- (void)deleteAccountAtIndexPath:(id)arg1;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)backAction;
- (void)setTitleWithString:(id)arg1;
- (void)logBusineseAccordingToSection:(long long)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)refreshStatisticsInSection:(long long)arg1 header:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)loadHeaderIndex;
- (void)handleEyeButton;
- (void)initEyeButton;
- (void)updateEyeButtonFrame;
- (void)updateTextsByIsEyeClose;
- (void)updateDisableAnimationStatusForScoreboardLabel;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)unregisterKVO;
- (void)registerKVO;
- (void)setEditingAction;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)animateBalanceIfNeeded;
- (void)showImportViewController;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)balanceHasChanged;
- (void)refreshScrollHeader;
- (void)refreshTotalAssetLiabilityAndBalance;
- (void)viewDidUnload;
- (void)resetColors;
- (void)dealloc;
- (void)viewDidLoad;
- (void)loadView;
- (void)initCacheOfHeaders;
- (void)initScrollHeader;
- (void)initAccountGroupBalance;
- (id)init;
- (id)initWithExpenseVo:(id)arg1 isCreditAccounts:(_Bool)arg2 isTransacionalAccountShow:(_Bool)arg3;
- (id)initWithExpenseVo:(id)arg1 isCreditAccounts:(_Bool)arg2;
- (id)initWithExpenseVo:(id)arg1 isTransacionalAccountShow:(_Bool)arg2;
- (id)initWithExpenseVo:(id)arg1;
- (void)initDictionary;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

