//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ZFCustomHighlightCell.h"

@class NSLayoutConstraint, RecommendationPostItem, UILabel, UIView;

@interface HotPostsCell : ZFCustomHighlightCell
{
    RecommendationPostItem *_recommendationPostItem;
    UILabel *_petNameLabel;
    UILabel *_titleLabel;
    UILabel *_detailLabel;
    UIView *_spliteView;
    UILabel *_viewsLabel;
    NSLayoutConstraint *_heightConstraint;
}

@property(nonatomic) __weak NSLayoutConstraint *heightConstraint; // @synthesize heightConstraint=_heightConstraint;
@property(nonatomic) __weak UILabel *viewsLabel; // @synthesize viewsLabel=_viewsLabel;
@property(nonatomic) __weak UIView *spliteView; // @synthesize spliteView=_spliteView;
@property(nonatomic) __weak UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak UILabel *petNameLabel; // @synthesize petNameLabel=_petNameLabel;
@property(retain, nonatomic) RecommendationPostItem *recommendationPostItem; // @synthesize recommendationPostItem=_recommendationPostItem;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

