//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RequestCmdPresentation.h"

@interface InviteShareInfoXmlPresentation : RequestCmdPresentation
{
}

+ (id)inviteShareInfoXmlPresentationWithResponseXmlString:(id)arg1;
- (id)xmlString;
- (id)initWithUserName:(id)arg1 password:(id)arg2 syncAccountBookId:(id)arg3;

@end

