//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITextFieldDelegate.h"

@class NSMutableArray, NSString, UIImageView, UILabel, UITextField;

@interface KDAlertView : UIView <UITextFieldDelegate>
{
    _Bool _isLastAnimationShow;
    _Bool _transitionStart;
    id <KDAlertViewDelegate> _delegate;
    unsigned long long _style;
    UITextField *_textField;
    long long _cancelButtonIndex;
    long long _firstOtherButtonIndex;
    NSMutableArray *_buttons;
    NSMutableArray *_buttonTitles;
    UILabel *_titleLabel;
    UILabel *_messageLabel;
    long long _selectIndex;
    UIView *_textFieldContainer;
    UIView *_underlineView;
    UIImageView *_backgroundImageView;
    UIView *_topBackgroundView;
    NSMutableArray *_seperators;
    CDUnknownBlockType _dismissBlock;
    CDUnknownBlockType _completeBlock;
    CDUnknownBlockType _transitionBlock;
    CDUnknownBlockType _transitionTextBlock;
    struct UIEdgeInsets _textFieldEdgeInsets;
    struct UIEdgeInsets _titleInsets;
    struct UIEdgeInsets _messageInsets;
}

+ (void)alertWeiboNotInstalled;
+ (void)alertQQNotInstalled;
+ (void)alertWeChatNotInstalledWhenInvite;
+ (void)alertWeChatNotInstalledWithMessage:(id)arg1;
+ (void)alertWeChatNotInstalled;
+ (id)showAlertViewWithTitle:(id)arg1 message:(id)arg2 cancelButtonTitle:(id)arg3 okButtonTitles:(id)arg4 withDismissBlock:(CDUnknownBlockType)arg5;
+ (id)showAlertViewWithMessage:(id)arg1;
+ (void)cancelAllCallback;
+ (id)shareAlertWindow;
@property(nonatomic) struct UIEdgeInsets messageInsets; // @synthesize messageInsets=_messageInsets;
@property(nonatomic) struct UIEdgeInsets titleInsets; // @synthesize titleInsets=_titleInsets;
@property(nonatomic) _Bool transitionStart; // @synthesize transitionStart=_transitionStart;
@property(copy, nonatomic) CDUnknownBlockType transitionTextBlock; // @synthesize transitionTextBlock=_transitionTextBlock;
@property(copy, nonatomic) CDUnknownBlockType transitionBlock; // @synthesize transitionBlock=_transitionBlock;
@property(copy, nonatomic) CDUnknownBlockType completeBlock; // @synthesize completeBlock=_completeBlock;
@property(copy, nonatomic) CDUnknownBlockType dismissBlock; // @synthesize dismissBlock=_dismissBlock;
@property(nonatomic) _Bool isLastAnimationShow; // @synthesize isLastAnimationShow=_isLastAnimationShow;
@property(retain, nonatomic) NSMutableArray *seperators; // @synthesize seperators=_seperators;
@property(retain, nonatomic) UIView *topBackgroundView; // @synthesize topBackgroundView=_topBackgroundView;
@property(retain, nonatomic) UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
@property(nonatomic) __weak UIView *underlineView; // @synthesize underlineView=_underlineView;
@property(nonatomic) struct UIEdgeInsets textFieldEdgeInsets; // @synthesize textFieldEdgeInsets=_textFieldEdgeInsets;
@property(retain, nonatomic) UIView *textFieldContainer; // @synthesize textFieldContainer=_textFieldContainer;
@property(nonatomic) long long selectIndex; // @synthesize selectIndex=_selectIndex;
@property(retain, nonatomic) UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) NSMutableArray *buttonTitles; // @synthesize buttonTitles=_buttonTitles;
@property(retain, nonatomic) NSMutableArray *buttons; // @synthesize buttons=_buttons;
@property(readonly, nonatomic) long long firstOtherButtonIndex; // @synthesize firstOtherButtonIndex=_firstOtherButtonIndex;
@property(readonly, nonatomic) long long cancelButtonIndex; // @synthesize cancelButtonIndex=_cancelButtonIndex;
@property(retain, nonatomic) UITextField *textField; // @synthesize textField=_textField;
@property(nonatomic) unsigned long long style; // @synthesize style=_style;
@property(nonatomic) __weak id <KDAlertViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)keyboardWillShowNotification:(id)arg1;
- (void)textFieldTextDidEndEditingNotification:(id)arg1;
- (long long)countOfAlertViewInSharedWindow;
- (_Bool)sharedAlertWindowCanDismiss;
- (void)tryDismissWindow:(_Bool)arg1;
- (void)notifyDidDismiss;
- (void)notifyWillDismiss;
- (void)notifyDidShow;
- (void)notifyWillShow;
- (struct CGRect)destFrameAfterKeyBoardShow;
- (void)animateTransitionWithDuration:(double)arg1 timeFunction:(long long)arg2;
- (void)transitionToSecureTextInput;
- (void)dismissWithAnimation:(_Bool)arg1;
- (void)showWithAnimation:(_Bool)arg1;
- (void)handleButtonClicked:(id)arg1;
- (void)registerTextFieldNotifications:(_Bool)arg1;
- (void)showWithCompletionBlock:(CDUnknownBlockType)arg1 transitionBlock:(CDUnknownBlockType)arg2 transitionTextBlock:(CDUnknownBlockType)arg3 dismissBlock:(CDUnknownBlockType)arg4;
- (void)showWithCompletionBlock:(CDUnknownBlockType)arg1 dismissBlock:(CDUnknownBlockType)arg2;
- (void)show;
- (void)catchUnderlineView;
- (void)dismissWithClickedButtonIndex:(long long)arg1 animated:(_Bool)arg2;
- (id)buttonTitleAtIndex:(long long)arg1;
- (long long)addButtonWithTitle:(id)arg1;
- (void)updateBackgroundView;
- (void)dealloc;
- (double)caculateButtonHeight;
- (double)caculateAlertViewHeight;
- (id)seperatorView;
- (void)layoutButtonWithCurrentYoffset:(double)arg1;
- (void)layoutSubviews;
- (id)downSubviewBackgroundImage;
- (id)normalSubviewBackgroundImage;
- (id)downSubviewBackgroundColor;
- (id)normalSubviewBackgroundColor;
- (id)attributedMessageString:(id)arg1;
- (void)setMessageLabelText:(id)arg1;
- (id)initWithTitle:(id)arg1 message:(id)arg2 delegate:(id)arg3 cancelButtonTitle:(id)arg4 otherButtonTitles:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

