//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class KDInvestmentQuoteTipsData, UIColor, UILabel;

@interface KDInvestmentTopQuoteTipsView : UIView
{
    KDInvestmentQuoteTipsData *currentQuoteTipsData;
    UILabel *qouteDateLabel;
    UILabel *indexQuoteTitleLabel;
    UILabel *fiveYearQuoteTitleLabel;
    UILabel *fundQuoteTitleLabel;
    UILabel *indexQuoteValueLabel;
    UILabel *fiveYearQuoteValueLabel;
    UILabel *fundQuoteValueLabel;
    UIColor *trustLineColor;
    UIColor *yebLineColor;
    UIColor *fiveYearLineColor;
}

- (void).cxx_destruct;
- (void)setQuoteTime:(double)arg1;
- (id)createLabelWithText:(id)arg1 frame:(struct CGRect)arg2 textAligin:(long long)arg3 fontName:(id)arg4 fontSize:(double)arg5 textColor:(id)arg6;
- (void)layoutInvestmentUI;
- (void)setTipsComponentInfo:(id)arg1 quoteValue:(double)arg2 percentagePostfixFlag:(_Bool)arg3;
- (void)redrawQuoteTipsView;
- (void)setQuoteData:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

