//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "KDFundQuoteReportGestureView.h"

@class NSString, UILabel;

@interface KDStockQuoteReportGestureView : KDFundQuoteReportGestureView
{
    UILabel *currentQuoteValueLabel;
    _Bool showCurrentQuoteValueLabel;
    NSString *currentQuoteValueFontName;
    double currentQuoteValueFontSize;
    int currentInvestmentType;
}

- (void).cxx_destruct;
- (void)showQuoteValueLabel:(_Bool)arg1;
- (void)createCurrentQuoteValueLabel;
- (_Bool)moveDotImageZone:(int)arg1;
- (void)setGestureRecognizerRect:(struct CGRect)arg1 zoneCount:(int)arg2 trustLineYVectexArray:(id)arg3 fiveYearLineYVectexArray:(id)arg4 yebLineYVectexArray:(id)arg5 fundLineYVectexArray:(id)arg6 showPercentageFlag:(_Bool)arg7 trustLineQuoteValueArray:(id)arg8 fiveYearLineQuoteValueArray:(id)arg9 yebLineQuoteValueArray:(id)arg10 fundLineQuoteValueArray:(id)arg11 quoteDateArray:(id)arg12;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 investmentType:(int)arg2;

@end

