//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSString, TransactionDebt, TransactionDebtGroup;

@protocol LoanDao <NSObject>
- (NSArray *)addTransactionDebtGroups:(NSArray *)arg1;
- (NSArray *)addTransactionDebts:(NSArray *)arg1;
- (NSDictionary *)transactionDebtsByTransactionIds:(NSArray *)arg1;
- (_Bool)updateCreditor:(long long)arg1 withHidden:(_Bool)arg2;
- (NSArray *)listOfMigrationTransactionWithAccountId:(long long)arg1 currencyCode:(NSString *)arg2;
- (NSDictionary *)mapOfTransactionWaitingForMigrating;
- (NSArray *)debtTransactionsWithRelationTransByCreditorId:(long long)arg1;
- (NSArray *)debtTransactionsByCreditorId:(long long)arg1;
- (NSArray *)listOfAllTransactionDebt;
- (NSArray *)listOfAllTransactionDebtGroup;
- (NSArray *)listOfTransactionDebtGroupByCreditorId:(long long)arg1;
- (NSArray *)listOfTransactionDebtGroupByGroupUUID:(NSString *)arg1;
- (TransactionDebtGroup *)transactionDebtGroupByTransactionId:(long long)arg1;
- (_Bool)updateTransactionDebtGroup:(TransactionDebtGroup *)arg1;
- (_Bool)deleteTransactionDebtGroupByTransactionId:(long long)arg1;
- (_Bool)addTransactionDebtGroup:(TransactionDebtGroup *)arg1;
- (NSArray *)listOfTransactionDebtByCreditorId:(long long)arg1;
- (TransactionDebt *)transactionDebtByTransactionId:(long long)arg1;
- (_Bool)updateTransactionDebt:(TransactionDebt *)arg1;
- (_Bool)deleteTransactionDebtByTransactionId:(long long)arg1;
- (_Bool)addTransactionDebt:(TransactionDebt *)arg1;
@end

