//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class FDHiddenButton, UILabel, UIView;

@interface LoanCenterCell : UITableViewCell
{
    _Bool _isHiddenOcularButton;
    UILabel *_nameLabel;
    UILabel *_receivableLabel;
    UILabel *_receivableTitleLabel;
    UILabel *_repaymentLabel;
    UILabel *_repaymentTitleLabel;
    UIView *_separatorView;
    UIView *_colorBar;
    FDHiddenButton *_ocularButton;
}

@property(nonatomic) _Bool isHiddenOcularButton; // @synthesize isHiddenOcularButton=_isHiddenOcularButton;
@property(retain, nonatomic) FDHiddenButton *ocularButton; // @synthesize ocularButton=_ocularButton;
@property(retain, nonatomic) UIView *colorBar; // @synthesize colorBar=_colorBar;
@property(retain, nonatomic) UIView *separatorView; // @synthesize separatorView=_separatorView;
@property(retain, nonatomic) UILabel *repaymentTitleLabel; // @synthesize repaymentTitleLabel=_repaymentTitleLabel;
@property(retain, nonatomic) UILabel *repaymentLabel; // @synthesize repaymentLabel=_repaymentLabel;
@property(retain, nonatomic) UILabel *receivableTitleLabel; // @synthesize receivableTitleLabel=_receivableTitleLabel;
@property(retain, nonatomic) UILabel *receivableLabel; // @synthesize receivableLabel=_receivableLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

