//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "KDTabView.h"

#import "UIPickerViewAccessibilityDelegate.h"
#import "UIPickerViewDataSource.h"
#import "UIPickerViewDelegate.h"

@class NSMutableArray, NSString, UIButton, UIPickerView;

@interface LoanToAccountPickerView : KDTabView <UIPickerViewDelegate, UIPickerViewDataSource, UIPickerViewAccessibilityDelegate>
{
    id <LoanToAccountPickerViewDelegate> _delegate;
    UIPickerView *_loanToAccountPicker;
    NSMutableArray *_loanToAccounts;
    UIButton *_switchDoubleColumnButton;
    _Bool _isLend;
    long long _selectedAccountIndex;
}

@property(retain, nonatomic) UIButton *switchDoubleColumnButton; // @synthesize switchDoubleColumnButton=_switchDoubleColumnButton;
@property(nonatomic) long long selectedAccountIndex; // @synthesize selectedAccountIndex=_selectedAccountIndex;
@property(nonatomic) __weak id <LoanToAccountPickerViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSMutableArray *loanToAccounts; // @synthesize loanToAccounts=_loanToAccounts;
- (void).cxx_destruct;
- (id)pickerView:(id)arg1 accessibilityLabelForComponent:(long long)arg2;
- (void)touchShowAnotherAccountButton;
- (void)reselectPickerRow;
- (void)showAnotherAccount;
- (void)fillAccountPickerComponentView:(id)arg1 withAccountVo:(id)arg2;
- (id)pickerView:(id)arg1 viewForRow:(long long)arg2 forComponent:(long long)arg3 reusingView:(id)arg4;
- (void)pickerView:(id)arg1 didSelectRow:(long long)arg2 inComponent:(long long)arg3;
- (double)pickerView:(id)arg1 rowHeightForComponent:(long long)arg2;
- (double)pickerView:(id)arg1 widthForComponent:(long long)arg2;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (id)accountPickerFromAccountVo:(id)arg1;
- (void)reloadLendAccounts;
- (void)reloadAskDebtAccounts;
- (void)reloadBorrowOrPayDebtAccounts;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

