//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseTabSettingViewController.h"

#import "MailBillImportUndoActionDelegate.h"
#import "UIAlertViewDelegate.h"

@class NSArray, NSMutableArray, NSString, UILabel, UIView;

@interface MailBillImportUndoViewController : BaseTabSettingViewController <UIAlertViewDelegate, MailBillImportUndoActionDelegate>
{
    long long _platform;
    _Bool _isMycardUndoAction;
    NSArray *_transactionGroup;
    long long _undoSelectRow;
    UIView *_undoSuccessView;
    UILabel *_undoSuccessLabel;
    NSMutableArray *_importedTimes;
    NSString *_deletedTransactionCreatedTime;
}

@property(retain, nonatomic) NSString *deletedTransactionCreatedTime; // @synthesize deletedTransactionCreatedTime=_deletedTransactionCreatedTime;
@property(retain, nonatomic) NSMutableArray *importedTimes; // @synthesize importedTimes=_importedTimes;
@property(retain, nonatomic) UILabel *undoSuccessLabel; // @synthesize undoSuccessLabel=_undoSuccessLabel;
@property(retain, nonatomic) UIView *undoSuccessView; // @synthesize undoSuccessView=_undoSuccessView;
@property(nonatomic) long long undoSelectRow; // @synthesize undoSelectRow=_undoSelectRow;
@property(retain, nonatomic) NSArray *transactionGroup; // @synthesize transactionGroup=_transactionGroup;
- (void).cxx_destruct;
- (void)hideWaitingDialog;
- (void)showWaitingDialog:(id)arg1;
- (void)importAction;
- (void)mailBillImportUndoCell:(id)arg1 andUndoButton:(id)arg2;
- (void)delayDismisBezelActivityView;
- (void)finishUndoAction:(id)arg1;
- (_Bool)calculateAndUpdateBalanceById:(long long)arg1;
- (_Bool)updateAccountBalanceOrValueWithAccountIds:(id)arg1;
- (void)beginMycardUndo;
- (void)beginMycardUndoAction;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForMailImportSectionRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForMycardImportSectionRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)disappearUndoSuccessView;
- (void)didFinishOfBillBatchDelete:(id)arg1;
- (void)deleteChoosedBill:(id)arg1;
- (void)asyncReloadImortedTimesWithWaitDialog;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)reloadMillImportGroups;
- (void)reloadImortedTimes;
- (id)initWithImportPlatfrom:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

