//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray, NSDate, NSString;

@protocol MaintainDao
- (_Bool)checkDBFileIsBroken;
- (_Bool)tryFix;
- (_Bool)hasPhotoNeedUpload;
- (NSDate *)timestampForPullDataFromServer;
- (_Bool)deletePullDataFromServerRequestTimestamp;
- (_Bool)createPullDataFromServerTimestamp;
- (_Bool)onlyAddTransactionsSineDate:(NSDate *)arg1;
- (_Bool)hasChangedDataAfterTime:(NSDate *)arg1;
- (_Bool)setEmptyBasicDataFlag:(_Bool)arg1;
- (_Bool)isNeedDeleteBasicTablesData;
- (_Bool)hasDataInTransactionTable;
- (_Bool)hasSynchronizedBefore;
- (NSArray *)csvRows;
- (NSString *)agentVersion;
- (_Bool)setAgentVersion;
- (_Bool)setLocalization;
- (_Bool)vacuumDatabase;
- (_Bool)deleteDatabaseDefaultData;
- (_Bool)emptyDatabaseDefaultData:(id *)arg1;
- (_Bool)upgradeDatabaseFromVersion:(long long)arg1;
- (_Bool)setAccountBookTemplate:(unsigned long long)arg1;
- (unsigned long long)accountBookTemplate;
- (_Bool)emptyProfileSyncLabelAndSyncOffsetTime;
- (NSString *)platform;
- (_Bool)updateDatabaseVersion:(long long)arg1 forTemplate:(unsigned long long)arg2;
- (_Bool)updateDatabaseVersion:(long long)arg1;
- (long long)databaseVersion;
- (long long)requiredDatabaseVersion;
- (void)cleanDd;
@end

