//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseTableViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class AccountVo, NSArray, NSString, UILabel;

@interface MergeAccountDuplicateTransViewController : BaseTableViewController <UITableViewDelegate, UITableViewDataSource>
{
    AccountVo *_mainAccountVo;
    AccountVo *_mergedAccountVo;
    NSArray *_duplicateRecords;
    NSString *_systemCurrencyCode;
    UILabel *_duplicateRecordCountLabel;
    UILabel *_duplicateTimeLabel;
    UILabel *_tipsLabel;
}

@property(retain, nonatomic) UILabel *tipsLabel; // @synthesize tipsLabel=_tipsLabel;
@property(retain, nonatomic) UILabel *duplicateTimeLabel; // @synthesize duplicateTimeLabel=_duplicateTimeLabel;
@property(retain, nonatomic) UILabel *duplicateRecordCountLabel; // @synthesize duplicateRecordCountLabel=_duplicateRecordCountLabel;
@property(retain, nonatomic) NSString *systemCurrencyCode; // @synthesize systemCurrencyCode=_systemCurrencyCode;
@property(retain, nonatomic) AccountVo *mergedAccountVo; // @synthesize mergedAccountVo=_mergedAccountVo;
@property(retain, nonatomic) AccountVo *mainAccountVo; // @synthesize mainAccountVo=_mainAccountVo;
@property(retain, nonatomic) NSArray *duplicateRecords; // @synthesize duplicateRecords=_duplicateRecords;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewDidUnload;
- (id)duplicateReocordVoWithIndexPath:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)assembleDuplicateRecords;
- (void)nextStepAction:(id)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

