//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class MessageCenterNetwork, MessageCenterPusher, NSMutableArray, NSString, UIBarButtonItem, UITableView;

@interface MessageReadViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
{
    UITableView *_tableView;
    NSMutableArray *_readMessages;
    MessageCenterNetwork *_network;
    MessageCenterPusher *_pusher;
    UIBarButtonItem *_emptyButton;
}

@property(retain, nonatomic) UIBarButtonItem *emptyButton; // @synthesize emptyButton=_emptyButton;
@property(retain, nonatomic) MessageCenterPusher *pusher; // @synthesize pusher=_pusher;
@property(retain, nonatomic) MessageCenterNetwork *network; // @synthesize network=_network;
@property(retain, nonatomic) NSMutableArray *readMessages; // @synthesize readMessages=_readMessages;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)isEmpty;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)clearReadMessages;
- (void)handleEmptyButton;
- (void)updateEmptyButtonStatus;
- (void)initNavigationBar;
- (void)initTableView;
- (void)initSubviews;
- (void)initDatas;
- (void)updateViewConstraints;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

