//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseTableViewController.h"

@class NSMutableArray, NoRecordView;

@interface MigrationOutCreditorSelectionViewController : BaseTableViewController
{
    NoRecordView *_noBillView;
    NSMutableArray *_creditors;
}

@property(retain, nonatomic) NSMutableArray *creditors; // @synthesize creditors=_creditors;
@property(retain, nonatomic) NoRecordView *noBillView; // @synthesize noBillView=_noBillView;
- (void).cxx_destruct;
- (void)reloadCreditors;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)createNoRecordView;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;

@end

