//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIGestureRecognizerDelegate.h"

@class MLSwipeBackIndicatorView, NSMutableArray, NSString, UIImageView, UINavigationController, UIScreenEdgePanGestureRecognizer, UIView;

@interface MLSwipeBackNavigationBehavior : NSObject <UIGestureRecognizerDelegate>
{
    struct CGPoint startTouch;
    UIImageView *lastScreenShotView;
    UIView *blackMask;
    MLSwipeBackIndicatorView *indicatorView;
    UIScreenEdgePanGestureRecognizer *recognizer;
    _Bool _canDragBack;
    _Bool _isMoving;
    UINavigationController *_navigationController;
    CDUnknownBlockType _shouldReciveTouch;
    UIView *_backgroundView;
    NSMutableArray *_screenShotsList;
}

@property(nonatomic) _Bool isMoving; // @synthesize isMoving=_isMoving;
@property(retain, nonatomic) NSMutableArray *screenShotsList; // @synthesize screenShotsList=_screenShotsList;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(copy, nonatomic) CDUnknownBlockType shouldReciveTouch; // @synthesize shouldReciveTouch=_shouldReciveTouch;
@property(nonatomic) _Bool canDragBack; // @synthesize canDragBack=_canDragBack;
@property(nonatomic) __weak UINavigationController *navigationController; // @synthesize navigationController=_navigationController;
- (void).cxx_destruct;
- (void)paningGestureReceive:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)moveViewWithX:(float)arg1 released:(_Bool)arg2;
- (id)capture;
- (void)popToViewControllerWithIndex:(long long)arg1 animated:(_Bool)arg2;
- (void)popToRootViewControllerAnimated:(_Bool)arg1;
- (void)popViewControllerAnimated:(_Bool)arg1;
- (void)pushViewController:(id)arg1 animated:(_Bool)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)swipeBackRecognizer;
- (id)initWithController:(id)arg1;
- (void)setPriority:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

