//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseTableViewController.h"

#import "MobileRegisterPhoneCellDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UITextFieldDelegate.h"

@class AutoChangeStateButton, CaptchaButton, EmailRegisterConfig, NSArray, NSString, UIButton, UITextField;

@interface MobileRegisterViewController : BaseTableViewController <MobileRegisterPhoneCellDelegate, UITextFieldDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate>
{
    NSArray *emailsProviders;
    EmailRegisterConfig *_emailRegisterConfig;
    NSString *_loginEntranceIdentifier;
    CDUnknownBlockType _completionBlock;
    UITextField *_textFieldMobilePhone;
    UITextField *_textFieldCaptcha;
    CaptchaButton *_captchaButton;
    UITextField *_textFieldPassword;
    UIButton *_regViaEmailButton;
    AutoChangeStateButton *_registerDoneButton;
}

@property(retain, nonatomic) AutoChangeStateButton *registerDoneButton; // @synthesize registerDoneButton=_registerDoneButton;
@property(retain, nonatomic) UIButton *regViaEmailButton; // @synthesize regViaEmailButton=_regViaEmailButton;
@property(retain, nonatomic) UITextField *textFieldPassword; // @synthesize textFieldPassword=_textFieldPassword;
@property(retain, nonatomic) CaptchaButton *captchaButton; // @synthesize captchaButton=_captchaButton;
@property(retain, nonatomic) UITextField *textFieldCaptcha; // @synthesize textFieldCaptcha=_textFieldCaptcha;
@property(retain, nonatomic) UITextField *textFieldMobilePhone; // @synthesize textFieldMobilePhone=_textFieldMobilePhone;
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(copy, nonatomic) NSString *loginEntranceIdentifier; // @synthesize loginEntranceIdentifier=_loginEntranceIdentifier;
@property(retain, nonatomic) EmailRegisterConfig *emailRegisterConfig; // @synthesize emailRegisterConfig=_emailRegisterConfig;
- (void).cxx_destruct;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)phoneCell:(id)arg1 didClickOnCaptchaButton:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)regSucceededWithName:(id)arg1 pwd:(id)arg2;
- (void)sendVerificationCodeRequest;
- (void)regViaEmailPressed:(id)arg1;
- (void)registerButtonPressed:(id)arg1;
- (void)backAction;
- (void)setUpRegisterViaEmailButton;
- (void)setUpTableViewFooter;
- (void)setUpTableViewHeader;
- (void)dealloc;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

