//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

#import "UIScrollViewDelegate.h"

@class NSString, UIImageView;

@interface MPZoomScrollView : UIScrollView <UIScrollViewDelegate>
{
    UIImageView *photoImgView;
}

@property(retain, nonatomic) UIImageView *photoImgView; // @synthesize photoImgView;
- (void).cxx_destruct;
- (void)adjustFramesAndContentSizeAfterZooming;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1 imageView:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

