//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseDao.h"

#import "MultiDimensionBudgetDao.h"

@class NSString;

@interface MultiDimensionBudgetDaoImpl : BaseDao <MultiDimensionBudgetDao>
{
}

- (id)findOldBudgets;
- (long long)countOfBudget;
- (_Bool)updateBudgetItem:(id)arg1;
- (id)fastAllBudgetsFromStatement:(struct sqlite3_stmt *)arg1;
- (id)fetchBudgetItem:(struct sqlite3_stmt *)arg1;
- (id)findAllBudgetAmountOfCategoryByRecurrenceType:(unsigned long long)arg1 eventStart:(id)arg2 eventEnd:(id)arg3;
- (id)findBudgetItemsUnderCategoryWithId:(long long)arg1 parentSourceKey:(id)arg2 recurrenceType:(unsigned long long)arg3 eventStart:(id)arg4 eventEnd:(id)arg5;
- (id)sumBudgetItemByParentCategoryPOID:(long long)arg1 parentSourceKey:(id)arg2 recurrenceType:(unsigned long long)arg3 eventStart:(id)arg4 eventEnd:(id)arg5;
- (id)findQuarterlyBudgetItemsUnderCategoryWithId:(long long)arg1 parentSourceKey:(id)arg2 eventStart:(id)arg3 eventEnd:(id)arg4;
- (id)findDaylyBudgetItemsUnderCategoryWithId:(long long)arg1 parentSourceKey:(id)arg2 eventStart:(id)arg3 eventEnd:(id)arg4;
- (id)findWeeklyBudgetItemsUnderCategoryWithId:(long long)arg1 parentSourceKey:(id)arg2 eventStart:(id)arg3 eventEnd:(id)arg4;
- (id)findYearlyBudgetItemsUnderCategoryWithId:(long long)arg1 parentSourceKey:(id)arg2 eventStart:(id)arg3 eventEnd:(id)arg4;
- (id)findMonthlyBudgetItemsUnderCategoryWithId:(long long)arg1 parentSourceKey:(id)arg2 eventStart:(id)arg3 eventEnd:(id)arg4;
- (id)findBudgetEventsByCategoryId:(long long)arg1 recurrenceRulesArray:(id)arg2;
- (id)findBudgetEventsByRecurrenceRules:(id)arg1 atDate:(id)arg2;
- (id)findBudgetEventsByRecurrenceRules:(id)arg1;
- (id)findOutOfDateBudgetAtDate:(id)arg1 recurrenceType:(unsigned long long)arg2;
- (id)findBudgetEventsByRecurrenceBudgetType:(unsigned long long)arg1 recurrenceType:(unsigned long long)arg2;
- (id)findBudgetEventsByRecurrenceBudgetType:(unsigned long long)arg1 Rules:(id)arg2;
- (id)findBudgetEventsByCategoryId:(long long)arg1 tagId:(long long)arg2 accountId:(long long)arg3 tradingEntityId:(long long)arg4 recurrenceRuleId:(long long)arg5;
- (id)findBudgetEventByEventIds:(id)arg1;
- (id)findBudgetEventByCategoryId:(long long)arg1 sourceKey:(id)arg2 recurrenceType:(unsigned long long)arg3 eventStart:(id)arg4 eventEnd:(id)arg5;
- (id)findBudgetEventByCategoryId:(long long)arg1 recurrenceType:(unsigned long long)arg2 eventStart:(id)arg3 eventEnd:(id)arg4;
- (id)findBudgetEventByEventId:(long long)arg1;
- (_Bool)deleteBudgetEventsByBudgetEvents:(id)arg1;
- (void)transferBudgetsToDeletedTableByBudgetEvents:(id)arg1;
- (void)transferBudgetToDeletedTableById:(long long)arg1;
- (_Bool)deleteBudgetEventAndChildBudgetEventsByEventId:(long long)arg1;
- (_Bool)deleteBudgetEventByCategoryId:(long long)arg1;
- (id)selectBudgetEventByCategoryId:(long long)arg1;
- (long long)deleteBudgetEventByEventId:(long long)arg1;
- (_Bool)addBudgetEvents:(id)arg1 tableName:(id)arg2;
- (long long)addBudgetEvent:(id)arg1 tableName:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

