//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MyCardSchemAction : NSObject
{
}

+ (void)openMyCardInAppStore;
+ (_Bool)showFunctionLimitInDemoModeIfNeeded;
+ (_Bool)openMyCardWithScheme:(id)arg1 importType:(long long)arg2 sources:(id)arg3 action:(id)arg4 mode:(id)arg5;
+ (_Bool)openMyCardWithScheme:(id)arg1;
+ (_Bool)importDataFromMyCardDailyWithImportType:(long long)arg1 sources:(id)arg2 action:(id)arg3 mode:(id)arg4;
+ (_Bool)importDataFromMyCardDaily;
+ (_Bool)openMyCardDaily;
+ (_Bool)importDataFromMyCardWithImportType:(long long)arg1 sources:(id)arg2 action:(id)arg3 mode:(id)arg4;
+ (_Bool)importDataFromMyCard;
+ (_Bool)openMyCard;
+ (_Bool)canOpenOldMyCardDaily;
+ (_Bool)canOpenOldMyCard;
+ (_Bool)canOpenMyCardDaily;
+ (_Bool)canOpenMyCard;

@end

