//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MyMoneyMillionIndexVo : NSObject
{
    double _indexValue;
    double _indexDate;
}

@property(nonatomic) double indexDate; // @synthesize indexDate=_indexDate;
@property(nonatomic) double indexValue; // @synthesize indexValue=_indexValue;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;

@end

