//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface NameIndex : NSObject
{
    NSString *_lastName;
    NSString *_firstName;
    long long _sectionNum;
    long long _originIndex;
}

+ (id)nameSortByPinyinWithArray:(id)arg1;
@property(nonatomic) long long originIndex; // @synthesize originIndex=_originIndex;
@property(nonatomic) long long sectionNum; // @synthesize sectionNum=_sectionNum;
@property(retain, nonatomic) NSString *firstName; // @synthesize firstName=_firstName;
@property(retain, nonatomic) NSString *lastName; // @synthesize lastName=_lastName;
- (void).cxx_destruct;
- (id)getLastName;
- (id)getFirstName;

@end

