//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class ScoreBoardLabel, UIFont, UILabel;

@interface NavHeaderView : UIView
{
    UIFont *_middleLabelFont;
    UIFont *_bigLabelFont;
    ScoreBoardLabel *_topValue;
    UILabel *_leftValue;
    UILabel *_rightValue;
    UILabel *_topLabel;
    UILabel *_leftLabel;
    UILabel *_rightLabel;
    UILabel *_bottomLabel;
}

@property(retain, nonatomic) UILabel *bottomLabel; // @synthesize bottomLabel=_bottomLabel;
@property(retain, nonatomic) UILabel *rightLabel; // @synthesize rightLabel=_rightLabel;
@property(retain, nonatomic) UILabel *leftLabel; // @synthesize leftLabel=_leftLabel;
@property(retain, nonatomic) UILabel *topLabel; // @synthesize topLabel=_topLabel;
@property(retain, nonatomic) UILabel *rightValue; // @synthesize rightValue=_rightValue;
@property(retain, nonatomic) UILabel *leftValue; // @synthesize leftValue=_leftValue;
@property(retain, nonatomic) ScoreBoardLabel *topValue; // @synthesize topValue=_topValue;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

