//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UILabel, UIView;

@interface NavHeaderContentViewController : UIViewController
{
    _Bool _isIncomeRatioZero;
    _Bool _isExpenseRatioZero;
    double _monthTextLabelOffsetY;
    UILabel *_monthLabel;
    UILabel *_daysLabel;
    UILabel *_monthTextLabel;
    UIView *_incomeExpenseGroup;
    UILabel *_incomeTextLabel;
    UIView *_incomeValueView;
    UILabel *_incomeValueLabel;
    UILabel *_expenseTextLabel;
    UIView *_expenseValueView;
    UILabel *_expenseValueLabel;
    UILabel *_balanceValueLabel;
    UIView *_balanceValueView;
    UILabel *_balanceTextLabel;
    UIView *_separatorView;
}

@property(retain, nonatomic) UIView *separatorView; // @synthesize separatorView=_separatorView;
@property(retain, nonatomic) UILabel *balanceTextLabel; // @synthesize balanceTextLabel=_balanceTextLabel;
@property(retain, nonatomic) UIView *balanceValueView; // @synthesize balanceValueView=_balanceValueView;
@property(retain, nonatomic) UILabel *balanceValueLabel; // @synthesize balanceValueLabel=_balanceValueLabel;
@property(retain, nonatomic) UILabel *expenseValueLabel; // @synthesize expenseValueLabel=_expenseValueLabel;
@property(retain, nonatomic) UIView *expenseValueView; // @synthesize expenseValueView=_expenseValueView;
@property(retain, nonatomic) UILabel *expenseTextLabel; // @synthesize expenseTextLabel=_expenseTextLabel;
@property(retain, nonatomic) UILabel *incomeValueLabel; // @synthesize incomeValueLabel=_incomeValueLabel;
@property(retain, nonatomic) UIView *incomeValueView; // @synthesize incomeValueView=_incomeValueView;
@property(retain, nonatomic) UILabel *incomeTextLabel; // @synthesize incomeTextLabel=_incomeTextLabel;
@property(retain, nonatomic) UIView *incomeExpenseGroup; // @synthesize incomeExpenseGroup=_incomeExpenseGroup;
@property(retain, nonatomic) UILabel *monthTextLabel; // @synthesize monthTextLabel=_monthTextLabel;
@property(retain, nonatomic) UILabel *daysLabel; // @synthesize daysLabel=_daysLabel;
@property(retain, nonatomic) UILabel *monthLabel; // @synthesize monthLabel=_monthLabel;
- (void).cxx_destruct;
- (void)viewDidUnload;
- (void)setWidth:(id)arg1 width:(double)arg2;
- (void)setX:(id)arg1 x:(double)arg2;
- (void)setY:(id)arg1 y:(double)arg2;
- (void)appendToRight:(id)arg1 target:(id)arg2 padding:(double)arg3;
- (void)trimIncomeExpenseGroupWidth;
- (void)setIncomeVisibility:(_Bool)arg1 visible:(_Bool)arg2;
- (void)alignIncomeToVerticalCenter:(_Bool)arg1;
- (void)alignToRight:(id)arg1;
- (void)setBalanceRatio:(float)arg1;
- (void)setExpenseRatio:(float)arg1;
- (void)setIncomeRatio:(float)arg1;
- (void)setExpenseLabel:(id)arg1;
- (void)setIncomeLabel:(id)arg1;
- (void)tryTrimLabel:(id)arg1 maxWidth:(double)arg2;
- (void)setBalanceNumberString:(id)arg1;
- (void)setExpenseNumberString:(id)arg1;
- (void)setIncomeNumberString:(id)arg1;
- (void)setDaysString:(id)arg1;
- (void)setMonthTextFont:(double)arg1;
- (void)setMonthTextString:(id)arg1;
- (void)setMonthString:(id)arg1;
- (void)setIsHighlighted:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

