//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "NewUserGuideFourthViewControllerDelegate.h"
#import "UIScrollViewDelegate.h"

@class NSString, NewUserGuideFirstViewController, NewUserGuideFourthViewController, NewUserGuideSecondViewController, NewUserGuideThirdViewController, UIPageControl, UIScrollView, UIView;

@interface NewUserGuideViewController : UIViewController <UIScrollViewDelegate, NewUserGuideFourthViewControllerDelegate>
{
    _Bool _originStatusBarHidden;
    id <NewUserGuideViewControllerDelegate> _delegate;
    UIScrollView *_scrollView;
    UIView *_backgroundView;
    NewUserGuideFirstViewController *_firstController;
    NewUserGuideSecondViewController *_secondController;
    NewUserGuideThirdViewController *_thirdController;
    NewUserGuideFourthViewController *_fourthController;
    UIPageControl *_pageControl;
}

@property(retain, nonatomic) UIPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(nonatomic) _Bool originStatusBarHidden; // @synthesize originStatusBarHidden=_originStatusBarHidden;
@property(retain, nonatomic) NewUserGuideFourthViewController *fourthController; // @synthesize fourthController=_fourthController;
@property(retain, nonatomic) NewUserGuideThirdViewController *thirdController; // @synthesize thirdController=_thirdController;
@property(retain, nonatomic) NewUserGuideSecondViewController *secondController; // @synthesize secondController=_secondController;
@property(retain, nonatomic) NewUserGuideFirstViewController *firstController; // @synthesize firstController=_firstController;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak id <NewUserGuideViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)postRegistNotificationNotification;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)updateViewConstraints;
- (void)initLastThreeControllers;
- (void)initFirstController;
- (void)initScrollView;
- (void)initBackgroundView;
- (void)initPageControl;
- (void)initSubviews;
- (void)hideStatusBar;
- (void)restoreStatusBar;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

