//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView;

@interface NewUserGuidePageTwoBillView : UIView
{
    UIImageView *_oneIconImageView;
    UIView *_oneHeadlineView;
    UIImageView *_oneDetailImageView;
    UIImageView *_twoIconImageView;
    UIView *_twoHeadlineView;
    UIView *_twoDetailline1View;
    UIView *_twoDetailline2View;
    UIImageView *_threeIconImageView;
    UIView *_threeHeadlineView;
    UIView *_threeDetailline1View;
    UIView *_threeDetailline2View;
    UIImageView *_fourIconImageView;
    UIView *_fourHeadlineView;
    UIView *_fourDetailline1View;
    UIView *_fourDetailline2View;
}

@property(retain, nonatomic) UIView *fourDetailline2View; // @synthesize fourDetailline2View=_fourDetailline2View;
@property(retain, nonatomic) UIView *fourDetailline1View; // @synthesize fourDetailline1View=_fourDetailline1View;
@property(retain, nonatomic) UIView *fourHeadlineView; // @synthesize fourHeadlineView=_fourHeadlineView;
@property(retain, nonatomic) UIImageView *fourIconImageView; // @synthesize fourIconImageView=_fourIconImageView;
@property(retain, nonatomic) UIView *threeDetailline2View; // @synthesize threeDetailline2View=_threeDetailline2View;
@property(retain, nonatomic) UIView *threeDetailline1View; // @synthesize threeDetailline1View=_threeDetailline1View;
@property(retain, nonatomic) UIView *threeHeadlineView; // @synthesize threeHeadlineView=_threeHeadlineView;
@property(retain, nonatomic) UIImageView *threeIconImageView; // @synthesize threeIconImageView=_threeIconImageView;
@property(retain, nonatomic) UIView *twoDetailline2View; // @synthesize twoDetailline2View=_twoDetailline2View;
@property(retain, nonatomic) UIView *twoDetailline1View; // @synthesize twoDetailline1View=_twoDetailline1View;
@property(retain, nonatomic) UIView *twoHeadlineView; // @synthesize twoHeadlineView=_twoHeadlineView;
@property(retain, nonatomic) UIImageView *twoIconImageView; // @synthesize twoIconImageView=_twoIconImageView;
@property(retain, nonatomic) UIImageView *oneDetailImageView; // @synthesize oneDetailImageView=_oneDetailImageView;
@property(retain, nonatomic) UIView *oneHeadlineView; // @synthesize oneHeadlineView=_oneHeadlineView;
@property(retain, nonatomic) UIImageView *oneIconImageView; // @synthesize oneIconImageView=_oneIconImageView;
- (void).cxx_destruct;
- (void)setupAfterAnimationFourthLine;
- (void)setupAfterAnimationThirdLine;
- (void)setupAfterAnimationSecondLine;
- (void)setupAfterAnimationFirstLine;
- (void)setupBeforeAnimationFourthLine;
- (void)setupBeforeAnimationThirdLine;
- (void)setupBeforeAnimationSecondLine;
- (void)setupBeforeAnimationFirstLine;
- (void)setupAfterAnimation;
- (void)setupBeforeAnimation;
- (void)animate;
- (void)initOne;
- (void)initTwo;
- (void)initThree;
- (void)initFour;
- (void)initSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

