//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSString, UITextField;

@interface NicknameEditingViewController : UIViewController
{
    UITextField *_editingField;
    NSString *_content;
    id <NicknameEditingViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <NicknameEditingViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
- (void).cxx_destruct;
- (_Bool)isValidMessage:(id *)arg1;
- (void)dismissBeforeBlock:(CDUnknownBlockType)arg1;
- (void)handleCancelButtonClicked:(id)arg1;
- (void)handleFinishButtonClicked:(id)arg1;
- (id)originString;
- (void)setOriginString:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

