//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NicknameEditingViewController;

@protocol NicknameEditingViewControllerDelegate <NSObject>
- (void)nicknameEditingViewController:(NicknameEditingViewController *)arg1 didDismissedWithResult:(NSString *)arg2;
@end

