//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GlobalMessage, NSString;

@interface NotificationMessage : NSObject
{
    long long _index;
    unsigned long long _type;
    unsigned long long _level;
    NSString *_title;
    NSString *_content;
    NSString *_extraParams;
    NSString *_contentURL;
    NSString *_thumbnailURL;
    NSString *_thumbnailName;
    NSString *_messageClassID;
    double _createdTime;
    long long _read;
    NSString *_iconUrl;
    NSString *_iconFileName;
    NSString *_iconTypeName;
    long long _topicURLType;
    NSString *_topicPostId;
    GlobalMessage *_globalMessage;
}

@property(retain, nonatomic) GlobalMessage *globalMessage; // @synthesize globalMessage=_globalMessage;
@property(copy, nonatomic) NSString *topicPostId; // @synthesize topicPostId=_topicPostId;
@property(nonatomic) long long topicURLType; // @synthesize topicURLType=_topicURLType;
@property(retain, nonatomic) NSString *iconTypeName; // @synthesize iconTypeName=_iconTypeName;
@property(retain, nonatomic) NSString *iconFileName; // @synthesize iconFileName=_iconFileName;
@property(retain, nonatomic) NSString *iconUrl; // @synthesize iconUrl=_iconUrl;
@property(nonatomic) long long read; // @synthesize read=_read;
@property(nonatomic) double createdTime; // @synthesize createdTime=_createdTime;
@property(retain, nonatomic) NSString *messageClassID; // @synthesize messageClassID=_messageClassID;
@property(retain, nonatomic) NSString *thumbnailName; // @synthesize thumbnailName=_thumbnailName;
@property(retain, nonatomic) NSString *thumbnailURL; // @synthesize thumbnailURL=_thumbnailURL;
@property(retain, nonatomic) NSString *contentURL; // @synthesize contentURL=_contentURL;
@property(copy, nonatomic) NSString *extraParams; // @synthesize extraParams=_extraParams;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) unsigned long long level; // @synthesize level=_level;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(nonatomic) long long index; // @synthesize index=_index;
- (void).cxx_destruct;
- (id)attributedString:(id)arg1 highlightedAttributes:(id)arg2;
- (id)newCode;
- (id)cellTitle;
- (id)description;
- (long long)typeForApplicationDirect;

@end

