//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (SSLCategory)
+ (id)encryptString:(id)arg1 withKey:(id)arg2;
+ (id)encryptString:(id)arg1;
+ (id)AES128EncryptWithKey:(id)arg1 Data:(id)arg2;
+ (id)HexValue:(id)arg1;
+ (id)SHA1:(id)arg1;
@end

