//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

@class NSMutableArray, UIView;

@interface OLEContainerScrollView : UIScrollView
{
    UIView *_contentView;
    NSMutableArray *_subviewsInLayoutOrder;
}

+ (void)initialize;
@property(readonly, nonatomic) NSMutableArray *subviewsInLayoutOrder; // @synthesize subviewsInLayoutOrder=_subviewsInLayoutOrder;
@property(readonly, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)willRemoveSubviewFromContainer:(id)arg1;
- (void)didAddSubviewToContainer:(id)arg1;
- (void)commonInitForOLEContainerScrollView;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

