//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseTableViewController.h"

#import "FDSeccurityPasscodeModificationViewControllerDelegate.h"
#import "FDSecurityPasscodeVerificationViewControllerDelegate.h"

@class MBSwitch, NSString, UINavigationController, UIView;

@interface PasscodeSettingController : BaseTableViewController <FDSecurityPasscodeVerificationViewControllerDelegate, FDSeccurityPasscodeModificationViewControllerDelegate>
{
    _Bool _isLogged;
    _Bool _isTurnPasscodeOff;
    MBSwitch *_switchCtl;
    NSString *_passCode;
    long long _passcodeOperation;
    UINavigationController *_passcodeNavigationController;
    UIView *_closeTableFooter;
    UIView *_openTableFooter;
    id <PasscodeSettingControllerDelegate> _delegate;
    MBSwitch *_passcodeSwitch;
    MBSwitch *_touchIDSwitch;
    MBSwitch *_secureInputSwitch;
}

@property(retain, nonatomic) MBSwitch *secureInputSwitch; // @synthesize secureInputSwitch=_secureInputSwitch;
@property(retain, nonatomic) MBSwitch *touchIDSwitch; // @synthesize touchIDSwitch=_touchIDSwitch;
@property(retain, nonatomic) MBSwitch *passcodeSwitch; // @synthesize passcodeSwitch=_passcodeSwitch;
@property(retain, nonatomic) UIView *closeTableFooter; // @synthesize closeTableFooter=_closeTableFooter;
@property(nonatomic) __weak id <PasscodeSettingControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIView *openTableFooter; // @synthesize openTableFooter=_openTableFooter;
@property(retain, nonatomic) NSString *passCode; // @synthesize passCode=_passCode;
@property(retain, nonatomic) UINavigationController *passcodeNavigationController; // @synthesize passcodeNavigationController=_passcodeNavigationController;
- (void).cxx_destruct;
- (void)notifyUserToSetEmail;
- (void)securityPasscodeModificationViewController:(id)arg1 didDimissedWithStatus:(unsigned long long)arg2;
- (void)securityPasscodeVerificationViewController:(id)arg1 didDismissedWithStatus:(unsigned long long)arg2;
- (void)switchAction:(id)arg1;
- (void)presentPasscodeVerificationViewController;
- (void)presentedPasscodeViewController;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)dismissPasscodeView;
- (void)reloadUI;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)didReceiveMemoryWarning;
- (void)turnOnPasscode;
- (void)turnOffPasscode;
- (void)loadView;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

