//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PermissionManager : NSObject
{
}

+ (_Bool)authorizedWithPermissionType:(long long)arg1 deniedTips:(id)arg2 deniedBlock:(CDUnknownBlockType)arg3;
+ (_Bool)authorizedWithPermissionType:(long long)arg1 deniedBlock:(CDUnknownBlockType)arg2;

@end

