//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "PhotoClipViewControllerDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSString, TemplateBgImgDataManager, UIImagePickerController, UITableView;

@interface PhotoSourceSelectionViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate, PhotoClipViewControllerDelegate>
{
    id <PhotoSourceSelectionViewControllerDelegate> _delegate;
    UITableView *_tableView;
    NSArray *_photoSourceArray;
    UIImagePickerController *_imagePickerController;
    TemplateBgImgDataManager *_imageDataManager;
}

@property(retain, nonatomic) TemplateBgImgDataManager *imageDataManager; // @synthesize imageDataManager=_imageDataManager;
@property(retain, nonatomic) UIImagePickerController *imagePickerController; // @synthesize imagePickerController=_imagePickerController;
@property(retain, nonatomic) NSArray *photoSourceArray; // @synthesize photoSourceArray=_photoSourceArray;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak id <PhotoSourceSelectionViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (struct CGSize)screenScaleTargetSizeWithImage:(id)arg1;
- (id)scaleImage:(id)arg1;
- (void)photoClipViewController:(id)arg1 didFinishClipingPhoto:(id)arg2;
- (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)navigationController:(id)arg1 segueToClipsImageViewControllerWithImage:(id)arg2 dismissWhenFinished:(_Bool)arg3;
- (void)segueToImagePickerControllerWithSourceType:(long long)arg1;
- (id)titleForPhotoSourceType:(unsigned long long)arg1;
- (void)setupUI;
- (void)setupPhotoSources;
- (void)refreshImgDownloadCell;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

