//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol PieChartDelegate <NSObject>
- (void)circleAnimationDidStop;
- (void)clickBackButton;
- (void)clickDetailButtonAt:(long long)arg1;
- (void)didSelectedSector:(long long)arg1;
- (void)animationDidStop;
@end

