//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PreBaseReimburseDisburseViewController.h"

@interface PreDisburseViewController : PreBaseReimburseDisburseViewController
{
}

- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithCreditor:(id)arg1;

@end

