//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PreBaseInputViewController.h"

#import "UIPickerViewDataSource.h"
#import "UIPickerViewDelegate.h"

@class NSArray, NSMutableArray, NSString, UIPickerView;

@interface PreMemberInputViewController : PreBaseInputViewController <UIPickerViewDelegate, UIPickerViewDataSource>
{
    UIPickerView *_memberPickerView;
    NSArray *_members;
    NSMutableArray *_recentMembers;
    long long _selectedRowInComponentAtMemberPicker;
}

@property(nonatomic) long long selectedRowInComponentAtMemberPicker; // @synthesize selectedRowInComponentAtMemberPicker=_selectedRowInComponentAtMemberPicker;
@property(retain, nonatomic) NSMutableArray *recentMembers; // @synthesize recentMembers=_recentMembers;
@property(retain, nonatomic) NSArray *members; // @synthesize members=_members;
@property(retain, nonatomic) UIPickerView *memberPickerView; // @synthesize memberPickerView=_memberPickerView;
- (void).cxx_destruct;
- (double)pickerView:(id)arg1 rowHeightForComponent:(long long)arg2;
- (double)pickerView:(id)arg1 widthForComponent:(long long)arg2;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (id)pickerView:(id)arg1 viewForRow:(long long)arg2 forComponent:(long long)arg3 reusingView:(id)arg4;
- (void)pickerView:(id)arg1 didSelectRow:(long long)arg2 inComponent:(long long)arg3;
- (void)loadMembersAndRecentMembers;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

