//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PreBaseInputViewController.h"

#import "CurrencyValueInputKeyboardViewDelegate.h"

@class CurrencyValueInputKeyboardView, NSString;

@interface PreMoneyInputViewController : PreBaseInputViewController <CurrencyValueInputKeyboardViewDelegate>
{
    CurrencyValueInputKeyboardView *_keyboardView;
    long long _switchType;
}

@property(nonatomic) long long switchType; // @synthesize switchType=_switchType;
@property(retain, nonatomic) CurrencyValueInputKeyboardView *keyboardView; // @synthesize keyboardView=_keyboardView;
- (void).cxx_destruct;
- (void)pressOkAtKeyboard:(id)arg1;
- (void)pressKeyAtKeyboard:(id)arg1;
- (void)switchToInput:(long long)arg1;
- (id)initWithStyle:(int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

