//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel;

@interface ProjectToMemberTableViewCell : UITableViewCell
{
    UILabel *_projectLabel;
    UILabel *_memberLabel;
    UILabel *_projectNameLabel;
    UILabel *_memberNameLabel;
    UIImageView *_arrowImageView;
}

@property(retain, nonatomic) UIImageView *arrowImageView; // @synthesize arrowImageView=_arrowImageView;
@property(retain, nonatomic) UILabel *memberNambeLabel; // @synthesize memberNambeLabel=_memberNameLabel;
@property(retain, nonatomic) UILabel *projectNameLabel; // @synthesize projectNameLabel=_projectNameLabel;
@property(retain, nonatomic) UILabel *memberLabel; // @synthesize memberLabel=_memberLabel;
@property(retain, nonatomic) UILabel *projectLabel; // @synthesize projectLabel=_projectLabel;
- (void).cxx_destruct;
- (id)createLabelControl;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

