//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PropertyService.h"

@class NSString;

@interface PropertyServiceImpl : NSObject <PropertyService>
{
}

- (_Bool)deletePropertyRowByKey:(id)arg1;
- (_Bool)updatePropertyRowValueByKey:(id)arg1 andValue:(id)arg2;
- (id)propertyRowValueByKey:(id)arg1;
- (_Bool)addRowToPropertyTableIfNotExistWithKey:(id)arg1 andValue:(id)arg2;
- (_Bool)addRowToPropertyTableWithKey:(id)arg1 andValue:(id)arg2;
- (_Bool)existRowInPropertyTable:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

