//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, RecordTableViewCell;

@protocol RecordTableViewCellOperateButtonsProtocol <NSObject>
- (NSArray *)recordTableViewCellRightButtons:(RecordTableViewCell *)arg1;
- (void)recordTableViewCell:(RecordTableViewCell *)arg1 tapOnRightButtons:(NSArray *)arg2 atIndex:(long long)arg3;
- (void)tapOnRecordTableViewCell:(RecordTableViewCell *)arg1;
- (_Bool)recordTableViewCellCanShowLeftButtons:(RecordTableViewCell *)arg1;
- (_Bool)recordTableViewCellCanShowRightButtons:(RecordTableViewCell *)arg1;
@end

