//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RefreshBaseView.h"

@class UIScrollView;

@interface RefreshHeaderView : RefreshBaseView
{
    long long _activityIndicatorViewStyle;
    UIScrollView *_scrollView;
    long long _state;
    double _pullingPercent;
}

+ (id)headerWithRefreshingBlock:(CDUnknownBlockType)arg1;
@property(nonatomic) double pullingPercent; // @synthesize pullingPercent=_pullingPercent;
- (long long)state;
- (id)scrollView;
- (long long)activityIndicatorViewStyle;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (void)executeRefreshingCallback;
- (void)setState:(long long)arg1;
- (_Bool)isRefreshing;
- (void)beginRefreshing;
- (void)dealloc;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)scrollViewContentOffsetDidChange:(id)arg1;
- (void)layoutSubviews;
- (void)willMoveToSuperview:(id)arg1;
- (void)updateSubviews;
- (void)setActivityIndicatorViewStyle:(long long)arg1;

@end

