//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ReportChartConfigDataManager : NSObject
{
}

+ (long long)mappingOldDisplayTypeToNewConfig:(long long)arg1;
+ (long long)mappingOldSecondLevelSortingTypeToNewConfig:(long long)arg1;
+ (long long)mappingOldFilterTypeToNewConfig:(long long)arg1;
+ (id)jsonDicWithJsonString:(id)arg1;
+ (id)convertToStringWithJsonObject:(id)arg1;
+ (id)defaultReportChartConfigDic;
+ (long long)loadChartSecondLevelChartSortingTypeFromUserDefault;
+ (_Bool)loadChartCountInvestmentAccountFromUserDefault;
+ (long long)loadChartDisplayTypeFromUserDefault;
+ (long long)loadChartFilterTypeFromUserDefault;
+ (id)loadAllChartConfigFromUserDefault;
+ (_Bool)updateReportChartConfigValue:(id)arg1 forKey:(id)arg2;
+ (id)loadReportChartConfigs;

@end

