//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@protocol ResourceDao <NSObject>
- (NSDictionary *)accountBookThumbnailDict;
- (NSDictionary *)accountBookCoverDict;
- (_Bool)insertResourceWithExternalPOID:(long long)arg1 externalType:(NSString *)arg2 resourceURL:(NSString *)arg3 errorMessage:(id *)arg4;
- (_Bool)insertTransactionPhotoResourceWithTransactionPOID:(long long)arg1 andResourceURL:(NSString *)arg2 errorMessage:(id *)arg3;
- (_Bool)deleteAll;
- (long long)transactionContainPhoto:(NSString *)arg1;
- (NSDictionary *)transactionPhotoDictionary;
@end

