//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "ScrollBarDrawableCellDelegate.h"
#import "ScrollBarDrawableHeaderReusableViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class NSArray, NSString, ScrollBarDrawableCell, UICollectionView, UILongPressGestureRecognizer, UIPanGestureRecognizer;

@interface ScrollBarDrawableViewController : UIViewController <ScrollBarDrawableCellDelegate, ScrollBarDrawableHeaderReusableViewDelegate, UIGestureRecognizerDelegate>
{
    UICollectionView *_collectionView;
    id <ScrollBarDrawableViewControllerDelegate> _delegate;
    NSArray *_selectedStrings;
    NSString *_currentTitle;
    UILongPressGestureRecognizer *_longPressGestureRecognizer;
    UIPanGestureRecognizer *_panGestureRecognizer;
    ScrollBarDrawableCell *_selectedMoveCell;
    long long _selectedCellItem;
    long long _cellToItem;
    NSArray *_cellPositions;
}

@property(retain, nonatomic) NSArray *cellPositions; // @synthesize cellPositions=_cellPositions;
@property(nonatomic) long long cellToItem; // @synthesize cellToItem=_cellToItem;
@property(nonatomic) long long selectedCellItem; // @synthesize selectedCellItem=_selectedCellItem;
@property(nonatomic) __weak ScrollBarDrawableCell *selectedMoveCell; // @synthesize selectedMoveCell=_selectedMoveCell;
@property(retain, nonatomic) UIPanGestureRecognizer *panGestureRecognizer; // @synthesize panGestureRecognizer=_panGestureRecognizer;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPressGestureRecognizer; // @synthesize longPressGestureRecognizer=_longPressGestureRecognizer;
@property(retain, nonatomic) NSString *currentTitle; // @synthesize currentTitle=_currentTitle;
@property(retain, nonatomic) NSArray *selectedStrings; // @synthesize selectedStrings=_selectedStrings;
@property(nonatomic) __weak id <ScrollBarDrawableViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (void).cxx_destruct;
- (void)scrollBarDrawableCellDidTapContentButton:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 moveItemAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (_Bool)collectionView:(id)arg1 canMoveItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)updateCollectionView:(_Bool)arg1;
- (id)createSectionZeroCellPositions;
- (long long)checkHasOverlapCellWithCell:(id)arg1;
- (void)animationSelectedCellToIndex:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)animationForOtherCellsMoveItemAtIndex:(long long)arg1 toIndex:(long long)arg2;
- (void)notificateDelegateDataSourceChanged;
- (void)collectionViewMoveItemAtIndex:(long long)arg1 toIndexPath:(long long)arg2;
- (void)deselectedTheSelectedMoveCell;
- (void)selectedCellAtIndex:(id)arg1;
- (void)handleGestureRecognizer:(id)arg1;
- (void)handleLongPressGestureRecognizer:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

