//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SettingService.h"

@class NSString;

@interface SettingServiceImpl : NSObject <SettingService>
{
}

- (_Bool)setDefaultExchange;
- (_Bool)updateExchangeWith:(id)arg1;
- (_Bool)updateExchangeRateLastUpdateTime:(double)arg1;
- (_Bool)addSyncLog:(id)arg1;
- (id)lastSyncDate;
- (_Bool)clearRedirectUrl;
- (_Bool)setProfileDefaultIncomeAccount:(long long)arg1;
- (_Bool)setProfileDefaultAccount:(long long)arg1;
- (_Bool)setProfileDefaultCorporationCategory:(long long)arg1;
- (_Bool)setProfileDefaultIncomeMember:(long long)arg1;
- (_Bool)setProfileDefaultMember:(long long)arg1;
- (_Bool)setProfileDefaultIncomeProjectCategory:(long long)arg1;
- (_Bool)setProfileDefaultProjectCategory:(long long)arg1;
- (_Bool)setProfileDefaultIncomeCategory:(long long)arg1;
- (_Bool)setProfileDefaultPayouCategory:(long long)arg1;
- (id)syncAccountBind;
- (_Bool)deleteAllSyncLog;
- (id)syncLogs;
- (id)redirectUrl;
- (_Bool)setDefaultCurrencyCode:(id)arg1;
- (id)defaultCurrencyCode;
- (void)setCalendarStartSetting:(id)arg1;
- (id)calendarStartSetting;
- (id)accountBookInDB;
- (id)getSyncAccount;
- (_Bool)setSyncAccountName:(id)arg1 redirectURL:(id)arg2 password:(id)arg3 syncAccountBookId:(long long)arg4;
- (_Bool)changeAccountBookWithName:(id)arg1 cover:(unsigned long long)arg2;
- (id)accountBookInfoWhenBackup;
- (_Bool)setAccountBookInfoWhenBackupWithName:(id)arg1 cover:(unsigned long long)arg2;
- (_Bool)setSyncAccountWithName:(id)arg1 password:(id)arg2 syncAccountBookId:(long long)arg3;
- (_Bool)emptyDatabase;
- (_Bool)setDefaultCorporationByCorporationId:(long long)arg1;
- (_Bool)setDefaultIncomeAccountByAccountId:(long long)arg1;
- (_Bool)setDefaultAccountByAccountId:(long long)arg1;
- (id)reportSetting;
- (_Bool)setProfileWithIncomeDefaultCategoryId:(long long)arg1 accountId:(long long)arg2 memberId:(long long)arg3 projectId:(long long)arg4;
- (_Bool)setProfileWithExpenseDefaultCategoryId:(long long)arg1 accountId:(long long)arg2 memberId:(long long)arg3 projectId:(long long)arg4 corporationId:(long long)arg5;
- (_Bool)setProfileWithExpenseCategoryId:(long long)arg1 incomeCategoryId:(long long)arg2 projectId:(long long)arg3 memberId:(long long)arg4 accountId:(long long)arg5 corporationId:(long long)arg6;
- (id)currentUserProfile;
- (id)defaultCorporation;
- (id)firstTransactionalCreditAccount;
- (id)firstCreditAccount;
- (id)defaultAccount;
- (id)defaultIncomeAccountWithoutHidden;
- (id)defaultAccountWithoutHidden;
- (_Bool)setDefaultProjectCategoryByCategoryId:(long long)arg1;
- (_Bool)setDefaultIncomeCategoryByCategoryId:(long long)arg1;
- (_Bool)setDefaultPayoutCategoryByCategoryId:(long long)arg1;
- (id)defaultIncomeMember;
- (id)defaultMember;
- (id)defaultIncomeProject;
- (id)defaultProject;
- (id)defaultIncomeCategory;
- (id)defaultPayoutCategory;
- (void)changeLocalSecurityPassword:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

