//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel, UIView;

@interface SettingTableCell : UITableViewCell
{
    UILabel *_nameLabel;
    UILabel *_valueLabel;
    UILabel *_memoLabel;
    UIImageView *_iconImageView;
    UIView *_cellSeperatorLine;
    UIView *_sectionSeperatorLine;
    UIView *_lastSeperatorLine;
    double _maxNameTextWidth;
    _Bool _isSecondLevelCell;
    _Bool _isCheckBox;
    id _customObject;
    UIImageView *_rightArrowImageView;
    UIImageView *_foldIconImageView;
    CDUnknownBlockType _iconTapActionBlock;
    long long _cellIndex;
    UIImageView *_checkFrameImageView;
    struct CGSize _iconImagePreferredSize;
}

@property(nonatomic) _Bool isCheckBox; // @synthesize isCheckBox=_isCheckBox;
@property(retain, nonatomic) UIImageView *checkFrameImageView; // @synthesize checkFrameImageView=_checkFrameImageView;
@property(nonatomic) _Bool isSecondLevelCell; // @synthesize isSecondLevelCell=_isSecondLevelCell;
@property(nonatomic) long long cellIndex; // @synthesize cellIndex=_cellIndex;
@property(copy, nonatomic) CDUnknownBlockType iconTapActionBlock; // @synthesize iconTapActionBlock=_iconTapActionBlock;
@property(retain, nonatomic) UIImageView *foldIconImageView; // @synthesize foldIconImageView=_foldIconImageView;
@property(retain, nonatomic) UIImageView *rightArrowImageView; // @synthesize rightArrowImageView=_rightArrowImageView;
@property(retain, nonatomic) id customObject; // @synthesize customObject=_customObject;
@property(nonatomic) double maxNameTextWidth; // @synthesize maxNameTextWidth=_maxNameTextWidth;
@property(nonatomic) struct CGSize iconImagePreferredSize; // @synthesize iconImagePreferredSize=_iconImagePreferredSize;
@property(retain, nonatomic) UIView *lastSeperatorLine; // @synthesize lastSeperatorLine=_lastSeperatorLine;
@property(retain, nonatomic) UIView *sectionSeperatorLine; // @synthesize sectionSeperatorLine=_sectionSeperatorLine;
@property(retain, nonatomic) UIView *cellSeperatorLine; // @synthesize cellSeperatorLine=_cellSeperatorLine;
@property(retain, nonatomic) UILabel *valueLabel; // @synthesize valueLabel=_valueLabel;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) UILabel *memoLabel; // @synthesize memoLabel=_memoLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
- (void).cxx_destruct;
- (void)setFoldIconByFoldStatus:(_Bool)arg1;
- (void)setKDAccessoryView;
- (void)setHalfCheckMark;
- (void)privateSetCheckMark:(_Bool)arg1 withUnCheckMarkImage:(id)arg2;
- (void)privateSetSingleSelectionCheckMark:(_Bool)arg1 withUnCheckMarkImage:(id)arg2;
- (void)setSingleSelectionCheckMark:(_Bool)arg1;
- (void)setCheckMark:(_Bool)arg1;
- (void)showCheckMarkFrameForMultiSelection;
- (void)setIsFirstRowInSectionForStyle1:(_Bool)arg1;
- (void)setIsLastRow:(_Bool)arg1;
- (void)setIsFirstRowInSection:(_Bool)arg1;
- (void)showFoldIconImageView:(_Bool)arg1;
- (void)iconTapAction:(id)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

