//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FDSharedAccountBookImportURLOpenHandlerDelegate.h"

@class AccountBookVo, NSString;

@interface SharedAccountBookUpdater : NSObject <FDSharedAccountBookImportURLOpenHandlerDelegate>
{
    AccountBookVo *_accountBookToRemove;
}

@property(retain, nonatomic) AccountBookVo *accountBookToRemove; // @synthesize accountBookToRemove=_accountBookToRemove;
- (void).cxx_destruct;
- (void)sharedAccountBookImportURLOpenHandlerDidFinishDownload:(id)arg1;
- (void)updateSharedAccountBook:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

