//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseXmlPresentation.h"

@class NSArray, SyncAccountVo;

@interface ShareAccountPresentation : BaseXmlPresentation
{
    SyncAccountVo *_masterAccount;
    NSArray *_slaves;
}

@property(retain, nonatomic) NSArray *slaves; // @synthesize slaves=_slaves;
@property(retain, nonatomic) SyncAccountVo *masterAccount; // @synthesize masterAccount=_masterAccount;
- (void).cxx_destruct;
- (id)requestWithURL:(id)arg1;
- (id)dictForAccount:(id)arg1;
- (id)xmlString;
- (id)initWithMasterAccount:(id)arg1 slaves:(id)arg2;

@end

