//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString, UIColor;

@interface SplashConfigVo : NSObject
{
    _Bool _shouldShowTitles;
    long long _oid;
    NSString *_redirectUrl;
    double _showTime;
    NSDate *_startDate;
    NSDate *_endDate;
    long long _showScheme;
    NSString *_picUrl;
    long long _redirectURLType;
    NSString *_headTitle;
    UIColor *_headTitleColor;
    NSString *_subTitle;
    UIColor *_subTitleColor;
}

@property(nonatomic) _Bool shouldShowTitles; // @synthesize shouldShowTitles=_shouldShowTitles;
@property(retain, nonatomic) UIColor *subTitleColor; // @synthesize subTitleColor=_subTitleColor;
@property(retain, nonatomic) NSString *subTitle; // @synthesize subTitle=_subTitle;
@property(retain, nonatomic) UIColor *headTitleColor; // @synthesize headTitleColor=_headTitleColor;
@property(retain, nonatomic) NSString *headTitle; // @synthesize headTitle=_headTitle;
@property(nonatomic) long long redirectURLType; // @synthesize redirectURLType=_redirectURLType;
@property(retain, nonatomic) NSString *picUrl; // @synthesize picUrl=_picUrl;
@property(nonatomic) long long showScheme; // @synthesize showScheme=_showScheme;
@property(retain, nonatomic) NSDate *endDate; // @synthesize endDate=_endDate;
@property(retain, nonatomic) NSDate *startDate; // @synthesize startDate=_startDate;
@property(nonatomic) double showTime; // @synthesize showTime=_showTime;
@property(retain, nonatomic) NSString *redirectUrl; // @synthesize redirectUrl=_redirectUrl;
@property(nonatomic) long long oid; // @synthesize oid=_oid;
- (void).cxx_destruct;
- (id)splashImagePath;
- (id)colorFromHexString:(id)arg1;
- (id)beginDateOfDay:(id)arg1;
- (id)initWithDictionary:(id)arg1;

@end

