//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "StockHoldingService.h"

@class NSString;

@interface StockHoldingServiceImpl : NSObject <StockHoldingService>
{
}

- (id)holdingIdsByStockCodes:(id)arg1;
- (id)createStockHoldingVoWith:(id)arg1;
- (id)createStockHoldingWith:(id)arg1;
- (void)deleteHoldingWithID:(long long)arg1;
- (id)holdingWithId:(long long)arg1;
- (id)allHoldings;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

