//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface StockBasicInfoVo : NSObject
{
    int _stockType;
    NSString *_stockCode;
}

@property(nonatomic) int stockType; // @synthesize stockType=_stockType;
@property(retain, nonatomic) NSString *stockCode; // @synthesize stockCode=_stockCode;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;

@end

