//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSString, StockCenterViewController, UIButton, UILabel, UIView;

@interface StockReportTableCell : UITableViewCell
{
    NSString *stockCode;
    NSString *stockName;
    double currentStockPrice;
    double profitLossValue;
    double profitLossPercent;
    UILabel *stockNameLabel;
    UILabel *stockPriceValueLabel;
    UILabel *stockPriceTitleLabel;
    UIButton *profitLossButton;
    UIView *cellSeparatorLineView;
    _Bool hideProfitLossButton;
    int currentShowProfitType;
    StockCenterViewController *eventDelegateController;
}

- (void).cxx_destruct;
- (void)setFundProfitButtonInfo;
- (void)switchStockProfitType:(id)arg1;
- (void)setStock:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

