//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, StockTransaction;

@protocol StockTransactionDao <NSObject>
- (NSArray *)insertStockTransactions:(NSArray *)arg1;
- (NSDictionary *)getStockTransIDDictionary;
- (NSDictionary *)stockTransactionsByTransactionIds:(NSArray *)arg1;
- (StockTransaction *)transactionWithFID:(long long)arg1;
- (void)updateStockTransaction:(StockTransaction *)arg1;
- (_Bool)deleteStockWithID:(long long)arg1;
- (NSArray *)transactionsWithHoldingId:(long long)arg1;
- (long long)insertStockTransaction:(StockTransaction *)arg1;
@end

