//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SuperTzIteratorBasedTimeFilter.h"

@class NSDateFormatter;

@interface SuperTzMonthFilter : SuperTzIteratorBasedTimeFilter
{
    NSDateFormatter *_dateFormatter;
}

@property(retain, nonatomic) NSDateFormatter *dateFormatter; // @synthesize dateFormatter=_dateFormatter;
- (void).cxx_destruct;
- (id)secondLineAttributeString;
- (id)firstLineSubAttributeString;
- (id)monthNumAttributeString;
- (id)rangeInfoForCurrentTimespan;
- (id)timespanType;

@end

