//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SuperTzAdvancedModelDataManager : NSObject
{
}

+ (_Bool)isAmount:(id)arg1 inRangeOfSuperTzTemplate:(id)arg2;
+ (_Bool)isMemo:(id)arg1 belongToSuperTzTemplate:(id)arg2;
+ (_Bool)isTimeInterval:(double)arg1 inRangeOfSuperTzTemplate:(id)arg2;
+ (_Bool)isItemId:(long long)arg1 IncludedInItemIds:(id)arg2;
+ (_Bool)isProjectVo:(id)arg1 belongToSuperTzTemplate:(id)arg2;
+ (_Bool)isCoorporationVo:(id)arg1 belongToSuperTzTemplate:(id)arg2;
+ (_Bool)isMemberVo:(id)arg1 belongToSuperTzTemplate:(id)arg2;
+ (_Bool)isAccountVo:(id)arg1 andSubAccountVo:(id)arg2 belongToSuperTzTemplate:(id)arg3;
+ (_Bool)isCategoryVo:(id)arg1 belongToSuperTzTemplate:(id)arg2;
+ (_Bool)hasNoneFilterInSuperTzTemplate:(id)arg1;
+ (_Bool)isExpenseVo:(id)arg1 belongToSuperTzAdvancedModel:(id)arg2;
+ (void)quickRecalculateSuperTzTemplateAdvancedModel:(id)arg1 byExpenseVoDictionary:(id)arg2;
+ (_Bool)isTheItem:(id)arg1 belongToSuperTzAdvancedModel:(id)arg2;

@end

