//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SuperTzListCellLoader : NSObject
{
}

+ (void)loadCategoryHeaderView:(id)arg1 withData:(id)arg2;
+ (void)setSectionTitleNumberOfLinesForHeaderView:(id)arg1 bySuperTzListType:(long long)arg2;
+ (void)loadCommonSettingForHeaderView:(id)arg1 withData:(id)arg2;
+ (void)setIncomeExpenseTitleLabelForHeaderView:(id)arg1 withData:(id)arg2 withListType:(long long)arg3;
+ (void)setCommonTextForHeaderView:(id)arg1 withData:(id)arg2;
+ (void)setCommonRatioForHeaderView:(id)arg1 withData:(id)arg2;
+ (void)loadTimelineCell:(id)arg1 withData:(id)arg2;
+ (void)loadHeaderView:(id)arg1 withData:(id)arg2 withSuperTzListType:(long long)arg3;
+ (void)loadListCell:(id)arg1 withData:(id)arg2;

@end

