//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "KDAlertViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSString, UITableView;

@interface SuperTransactionBoardManageViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, KDAlertViewDelegate>
{
    _Bool _doNotReload;
    _Bool _reloadMainPage;
    _Bool _noneTemplate;
    UITableView *_boardManageTableView;
    CDUnknownBlockType _backToHomePageBlock;
    CDUnknownBlockType _reloadMainPageBlock;
    double _cellHeight;
    NSMutableArray *_boardTemplateArray;
}

@property(nonatomic) _Bool noneTemplate; // @synthesize noneTemplate=_noneTemplate;
@property(nonatomic) _Bool reloadMainPage; // @synthesize reloadMainPage=_reloadMainPage;
@property(nonatomic) _Bool doNotReload; // @synthesize doNotReload=_doNotReload;
@property(retain, nonatomic) NSMutableArray *boardTemplateArray; // @synthesize boardTemplateArray=_boardTemplateArray;
@property(nonatomic) double cellHeight; // @synthesize cellHeight=_cellHeight;
@property(copy, nonatomic) CDUnknownBlockType reloadMainPageBlock; // @synthesize reloadMainPageBlock=_reloadMainPageBlock;
@property(copy, nonatomic) CDUnknownBlockType backToHomePageBlock; // @synthesize backToHomePageBlock=_backToHomePageBlock;
@property(nonatomic) __weak UITableView *boardManageTableView; // @synthesize boardManageTableView=_boardManageTableView;
- (void).cxx_destruct;
- (void)postNotificationName:(id)arg1 withSuperTzTemplate:(id)arg2;
- (void)pushControllerWithController:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)alertShows;
- (void)loadBoardTemplate;
- (void)setupBoardTableView;
- (void)setupNavigationBar;
- (void)addNewBoardAction;
- (void)backAction;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (_Bool)isIos8Version;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

