//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "BaseInputDelegate.h"
#import "CalculatorViewControllerDelegate.h"
#import "UITextFieldDelegate.h"

@class BaseInputViewController, CalculatorViewController, NSLayoutConstraint, NSString, TimeSpan, UILabel, UITableViewCell, UITextField;

@interface SuperTransactionTemplateCellViewController : UIViewController <CalculatorViewControllerDelegate, UITextFieldDelegate, BaseInputDelegate>
{
    _Bool _isNewTemplate;
    _Bool _isAmountRangeController;
    BaseInputViewController *_inputController;
    BaseInputViewController *_titleInputViewController;
    BaseInputViewController *_memoInputViewController;
    CalculatorViewController *_lowerLimitedKeyboardViewController;
    CalculatorViewController *_upperLimiterKeyboardViewController;
    long long _keyboardType;
    UITableViewCell *_normalTextFieldCell;
    UILabel *_normalTitleLabel;
    UITextField *_normalTextField;
    UITableViewCell *_commonCell;
    UILabel *_commonCellTitleLabel;
    UILabel *_commonCellDetailInfoLabel;
    UITableViewCell *_amountTextFieldCell;
    UITextField *_lowerLimitedTextField;
    UITextField *_upperLimitedTextField;
    NSLayoutConstraint *_onePixLineLowerHeightConstraint1;
    NSLayoutConstraint *_onePixLineLowerHeightConstraint2;
    NSLayoutConstraint *_onePixLineLowerHeightConstraint3;
    long long _cellType;
    CDUnknownBlockType _textFieldDidEndEditingBlcok;
    CDUnknownBlockType _textFieldDidBeginEditingBlcok;
    TimeSpan *_filteredTimeSpan;
    CDUnknownBlockType _textFieldIsEditingBlcok;
}

@property(copy, nonatomic) CDUnknownBlockType textFieldIsEditingBlcok; // @synthesize textFieldIsEditingBlcok=_textFieldIsEditingBlcok;
@property(nonatomic) _Bool isAmountRangeController; // @synthesize isAmountRangeController=_isAmountRangeController;
@property(retain, nonatomic) TimeSpan *filteredTimeSpan; // @synthesize filteredTimeSpan=_filteredTimeSpan;
@property(copy, nonatomic) CDUnknownBlockType textFieldDidBeginEditingBlcok; // @synthesize textFieldDidBeginEditingBlcok=_textFieldDidBeginEditingBlcok;
@property(copy, nonatomic) CDUnknownBlockType textFieldDidEndEditingBlcok; // @synthesize textFieldDidEndEditingBlcok=_textFieldDidEndEditingBlcok;
@property(nonatomic) long long cellType; // @synthesize cellType=_cellType;
@property(nonatomic) _Bool isNewTemplate; // @synthesize isNewTemplate=_isNewTemplate;
@property(nonatomic) __weak NSLayoutConstraint *onePixLineLowerHeightConstraint3; // @synthesize onePixLineLowerHeightConstraint3=_onePixLineLowerHeightConstraint3;
@property(nonatomic) __weak NSLayoutConstraint *onePixLineLowerHeightConstraint2; // @synthesize onePixLineLowerHeightConstraint2=_onePixLineLowerHeightConstraint2;
@property(nonatomic) __weak NSLayoutConstraint *onePixLineLowerHeightConstraint1; // @synthesize onePixLineLowerHeightConstraint1=_onePixLineLowerHeightConstraint1;
@property(retain, nonatomic) UITextField *upperLimitedTextField; // @synthesize upperLimitedTextField=_upperLimitedTextField;
@property(retain, nonatomic) UITextField *lowerLimitedTextField; // @synthesize lowerLimitedTextField=_lowerLimitedTextField;
@property(retain, nonatomic) UITableViewCell *amountTextFieldCell; // @synthesize amountTextFieldCell=_amountTextFieldCell;
@property(nonatomic) __weak UILabel *commonCellDetailInfoLabel; // @synthesize commonCellDetailInfoLabel=_commonCellDetailInfoLabel;
@property(nonatomic) __weak UILabel *commonCellTitleLabel; // @synthesize commonCellTitleLabel=_commonCellTitleLabel;
@property(retain, nonatomic) UITableViewCell *commonCell; // @synthesize commonCell=_commonCell;
@property(retain, nonatomic) UITextField *normalTextField; // @synthesize normalTextField=_normalTextField;
@property(nonatomic) __weak UILabel *normalTitleLabel; // @synthesize normalTitleLabel=_normalTitleLabel;
@property(retain, nonatomic) UITableViewCell *normalTextFieldCell; // @synthesize normalTextFieldCell=_normalTextFieldCell;
@property(nonatomic) long long keyboardType; // @synthesize keyboardType=_keyboardType;
@property(retain, nonatomic) CalculatorViewController *upperLimiterKeyboardViewController; // @synthesize upperLimiterKeyboardViewController=_upperLimiterKeyboardViewController;
@property(retain, nonatomic) CalculatorViewController *lowerLimitedKeyboardViewController; // @synthesize lowerLimitedKeyboardViewController=_lowerLimitedKeyboardViewController;
@property(retain, nonatomic) BaseInputViewController *memoInputViewController; // @synthesize memoInputViewController=_memoInputViewController;
@property(retain, nonatomic) BaseInputViewController *titleInputViewController; // @synthesize titleInputViewController=_titleInputViewController;
@property(retain, nonatomic) BaseInputViewController *inputController; // @synthesize inputController=_inputController;
- (void).cxx_destruct;
- (void)textChange;
- (void)calculatorViewController:(id)arg1 valueChanged:(id)arg2;
- (void)calculatorViewController:(id)arg1 switchToType:(long long)arg2;
- (void)calculatorViewControllerDidTapOkButton:(id)arg1;
- (void)calculatorViewController:(id)arg1 tipsChanged:(id)arg2 isWarning:(_Bool)arg3;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)closeTapped;
- (id)getAmountRangeDic;
- (id)getTextFieldInfo;
- (id)getCellViewWithType:(id)arg1;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

