//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

@class NSArray, NSIndexPath;

@interface SuperTransactionCollectorTypeViewController : UITableViewController
{
    NSIndexPath *_selectedIndexPath;
    id <SuperTransactionCollectorTypeViewControllerDelegate> _delegate;
    id _observer;
    NSArray *_dataSource;
    long long _collectorType;
}

@property(nonatomic) long long collectorType; // @synthesize collectorType=_collectorType;
@property(retain, nonatomic) NSArray *dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak id observer; // @synthesize observer=_observer;
@property(nonatomic) __weak id <SuperTransactionCollectorTypeViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSIndexPath *selectedIndexPath; // @synthesize selectedIndexPath=_selectedIndexPath;
- (void).cxx_destruct;
- (id)convertCurrentIndexPathToSuperTzIndexPath:(id)arg1;
- (_Bool)isProjectIndexPath:(id)arg1;
- (_Bool)isMemberIndexPath:(id)arg1;
- (_Bool)isCorporationIndexPath:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithCollectorType:(long long)arg1 selectedIndexPath:(id)arg2;

@end

