//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class HMSegmentedControl, NSArray, NSDictionary, SuperTzContextMenuViewController, UITableView;

@interface SuperTzBottomMenuView : UIView
{
    _Bool _isMenuCollapsed;
    NSArray *_menus;
    NSDictionary *_subMenus;
    CDUnknownBlockType _selectionChanged;
    HMSegmentedControl *_bottomMenu;
    UIView *_separatorView;
    UITableView *_contextMenuView;
    SuperTzContextMenuViewController *_contextMenuController;
}

@property(nonatomic) _Bool isMenuCollapsed; // @synthesize isMenuCollapsed=_isMenuCollapsed;
@property(retain, nonatomic) SuperTzContextMenuViewController *contextMenuController; // @synthesize contextMenuController=_contextMenuController;
@property(retain, nonatomic) UITableView *contextMenuView; // @synthesize contextMenuView=_contextMenuView;
@property(retain, nonatomic) UIView *separatorView; // @synthesize separatorView=_separatorView;
@property(retain, nonatomic) HMSegmentedControl *bottomMenu; // @synthesize bottomMenu=_bottomMenu;
@property(copy, nonatomic) CDUnknownBlockType selectionChanged; // @synthesize selectionChanged=_selectionChanged;
@property(retain, nonatomic) NSDictionary *subMenus; // @synthesize subMenus=_subMenus;
@property(retain, nonatomic) NSArray *menus; // @synthesize menus=_menus;
- (void).cxx_destruct;
- (void)setDefaultMenusAndSubMenus;
- (void)statisticAction:(long long)arg1;
- (id)menuImage:(id)arg1 submenuIndex:(id)arg2 selected:(_Bool)arg3;
- (void)setSelectedIndex:(id)arg1;
- (unsigned long long)selectedIndex;
- (long long)submenuItemCountForIndex:(unsigned long long)arg1;
- (struct CGRect)convertToWindowRect:(struct CGRect)arg1;
- (void)createAndAnimateContextMenu:(unsigned long long)arg1;
- (void)reloadSubmenuAtIndex:(unsigned long long)arg1;
- (struct CGSize)refreshSize;
- (void)onSelectionChanged:(id)arg1;
- (void)removeContextMenu;
- (void)toggleContextMenu;
- (void)showContextMenuAtIndex:(unsigned long long)arg1;
- (void)collapseContextMenu;
- (void)createContextMenu;
- (id)initWithFrame:(struct CGRect)arg1;

@end

