//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FDRecordsSumInfo, NSString, SuperTransactionTemplate;

@interface SuperTransactionTemplateAdvancedModel : NSObject
{
    _Bool _isAccountBookSwitch;
    _Bool _hasSumInfoCalculatedOnce;
    _Bool _shouldCalculateSumInfo;
    _Bool _mustRecalculateTotally;
    _Bool _isCalculating;
    _Bool _shouldStopCalculate;
    long long _fid;
    NSString *_name;
    NSString *_time;
    SuperTransactionTemplate *_superTzTemplate;
    FDRecordsSumInfo *_sumInfo;
    id _extraInfo;
    CDUnknownBlockType _expenseBlock;
    CDUnknownBlockType _incomeBlock;
    CDUnknownBlockType _balanceBlock;
}

+ (id)listAllSupreTzTemplateAdvancedModelsWithDataManager:(id)arg1;
@property(nonatomic) _Bool shouldStopCalculate; // @synthesize shouldStopCalculate=_shouldStopCalculate;
@property(copy, nonatomic) CDUnknownBlockType balanceBlock; // @synthesize balanceBlock=_balanceBlock;
@property(copy, nonatomic) CDUnknownBlockType incomeBlock; // @synthesize incomeBlock=_incomeBlock;
@property(copy, nonatomic) CDUnknownBlockType expenseBlock; // @synthesize expenseBlock=_expenseBlock;
@property(nonatomic) _Bool isCalculating; // @synthesize isCalculating=_isCalculating;
@property(retain, nonatomic) id extraInfo; // @synthesize extraInfo=_extraInfo;
@property(nonatomic) _Bool mustRecalculateTotally; // @synthesize mustRecalculateTotally=_mustRecalculateTotally;
@property(nonatomic) _Bool shouldCalculateSumInfo; // @synthesize shouldCalculateSumInfo=_shouldCalculateSumInfo;
@property(nonatomic) _Bool hasSumInfoCalculatedOnce; // @synthesize hasSumInfoCalculatedOnce=_hasSumInfoCalculatedOnce;
@property(nonatomic) _Bool isAccountBookSwitch; // @synthesize isAccountBookSwitch=_isAccountBookSwitch;
@property(retain, nonatomic) FDRecordsSumInfo *sumInfo; // @synthesize sumInfo=_sumInfo;
@property(retain, nonatomic) SuperTransactionTemplate *superTzTemplate; // @synthesize superTzTemplate=_superTzTemplate;
@property(copy, nonatomic) NSString *time; // @synthesize time=_time;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) long long fid; // @synthesize fid=_fid;
- (void).cxx_destruct;
- (void)quickRecalculateMinusExpenseVo:(id)arg1;
- (void)quickRecalculatePlusExpenseVo:(id)arg1;
- (void)handleReceivedNotification:(id)arg1;
- (id)sumInfoBySuperTzTemplate:(id)arg1;
- (void)calculateSumInfoBySuperTzTemplate:(id)arg1 sumInfoBlock:(CDUnknownBlockType)arg2;
- (id)getExistValueWithSumInfoType:(long long)arg1;
- (void)calculateSumInfoAndCalculateFinishedBlock:(CDUnknownBlockType)arg1;
- (id)getValueWithSumInfoValueType:(long long)arg1;
- (id)getBalanceAndCalculateFinishedBlock:(CDUnknownBlockType)arg1;
- (id)getIncomeAndCalculateFinishedBlock:(CDUnknownBlockType)arg1;
- (id)getExpenseAndCalculateFinishedBlock:(CDUnknownBlockType)arg1;
- (id)getTimeStrWithTimeBlock:(CDUnknownBlockType)arg1;
- (void)accountBookSwitchAction;
- (void)dealloc;
- (void)addSelfToNotificationCenter;
- (id)initWithFid:(long long)arg1;
- (id)initWithoutSumInfoWithFid:(long long)arg1;
- (id)initWithoutSumInfoWithSuperTzTemplate:(id)arg1;

@end

