//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface SuperTzFilterGroup : NSObject
{
    NSString *_groupName;
    NSArray *_filters;
}

+ (id)groupWithName:(id)arg1 filters:(id)arg2;
@property(retain, nonatomic) NSArray *filters; // @synthesize filters=_filters;
@property(retain, nonatomic) NSString *groupName; // @synthesize groupName=_groupName;
- (void).cxx_destruct;
- (id)initWithName:(id)arg1 filters:(id)arg2;

@end

