//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DataSetSyncConnectionHandler, NSArray, NSData, NSString, NSTimer, PhotoSyncConnectionHandler;

@interface SyncXmlService : NSObject
{
    id <SyncXmlServiceDelegate> _delegate;
    NSString *_sessionKey;
    NSString *_localSyncLabel;
    NSTimer *_heartbeatTimer;
    long long _loopCount;
    NSData *_gzipHeaderData;
    DataSetSyncConnectionHandler *_dataSetHandler;
    PhotoSyncConnectionHandler *_photoHandler;
    NSString *_abortErrDesc;
    NSString *_redirectUrl;
    _Bool isHaveRelogin;
    NSString *_username;
    NSString *_password;
    NSString *_syncAccountBookID;
    double _heartBeatStageBegin;
    NSArray *_cookies;
}

@property(retain, nonatomic) NSArray *cookies; // @synthesize cookies=_cookies;
@property(retain, nonatomic) NSString *syncAccountBookID; // @synthesize syncAccountBookID=_syncAccountBookID;
@property(retain, nonatomic) NSString *password; // @synthesize password=_password;
@property(retain, nonatomic) NSString *username; // @synthesize username=_username;
@property(retain, nonatomic) NSString *redirectUrl; // @synthesize redirectUrl=_redirectUrl;
@property(retain, nonatomic) NSString *abortErrDesc; // @synthesize abortErrDesc=_abortErrDesc;
@property(retain, nonatomic) PhotoSyncConnectionHandler *photoHandler; // @synthesize photoHandler=_photoHandler;
@property(retain, nonatomic) DataSetSyncConnectionHandler *dataSetHandler; // @synthesize dataSetHandler=_dataSetHandler;
@property long long loopCount; // @synthesize loopCount=_loopCount;
@property(retain, nonatomic) NSTimer *heartbeatTimer; // @synthesize heartbeatTimer=_heartbeatTimer;
@property(retain, nonatomic) NSString *sessionKey; // @synthesize sessionKey=_sessionKey;
@property(retain, nonatomic) NSString *localSyncLabel; // @synthesize localSyncLabel=_localSyncLabel;
@property(retain, nonatomic) NSData *gzipHeaderData; // @synthesize gzipHeaderData=_gzipHeaderData;
@property(nonatomic) __weak id <SyncXmlServiceDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)stopHeartbeat;
- (void)rollbackWhenOccurError:(id)arg1;
- (void)requestRegisterWithUsername:(id)arg1 andPassword:(id)arg2;
- (void)requestPhoto;
- (void)requestAbortCauseBy:(int)arg1;
- (void)successCommitWithPresentation:(id)arg1;
- (void)requestCommit;
- (void)receivedHeartbeatResponse:(id)arg1 headerInfo:(id)arg2;
- (void)requestHeartbeat;
- (void)successUploadDatabaseWithResponse:(id)arg1;
- (void)requestUpload;
- (void)failureLoginWithError:(id)arg1;
- (void)handleLoginResponseInfo:(id)arg1;
- (void)successLoginWithPresentation:(id)arg1;
- (void)requestLogin;
- (void)syncWithUsername:(id)arg1 password:(id)arg2 syncAccuntBookID:(id)arg3;
- (void)dealloc;
- (_Bool)deleteSyncDirectory;
- (_Bool)verifyDatabaseFromServer;
- (_Bool)ungzipDatabaseFrom:(id)arg1 to:(id)arg2;
- (_Bool)gzipDatabaseFrom:(id)arg1 to:(id)arg2;
- (_Bool)rollbackDatabase;
- (_Bool)replaceDatabase;
- (_Bool)archiveDatabase:(_Bool)arg1;

@end

