//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SyncAction : NSObject
{
    NSString *_message;
    double _percent;
    long long _type;
}

+ (id)actionWithMessage:(id)arg1 percent:(double)arg2 type:(long long)arg3;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic) double percent; // @synthesize percent=_percent;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
- (void).cxx_destruct;
- (id)initWithMessage:(id)arg1 percent:(double)arg2 type:(long long)arg3;

@end

