//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate;

@interface SyncAccelerationTimeVo : NSObject
{
    NSDate *_syncAccelerationDate;
}

@property(retain, nonatomic) NSDate *syncAccelerationDate; // @synthesize syncAccelerationDate=_syncAccelerationDate;
- (void).cxx_destruct;
- (id)formatSyncAccelerationDateForDB;
- (id)formatSyncAccelerationDateForDisplay;
- (id)initWithSyncAccelerationDateForDB:(id)arg1;
- (id)initWithSyncAccelerationDate:(id)arg1;
- (id)init;

@end

