//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString, SyncXmlService;

@protocol SyncXmlServiceDelegate

@optional
- (void)service:(SyncXmlService *)arg1 didSyncPhotosSuccessfully:(_Bool)arg2 withMessage:(NSString *)arg3;
- (void)service:(SyncXmlService *)arg1 didRegisterSuccessfully:(_Bool)arg2 withMessage:(NSString *)arg3;
- (void)service:(SyncXmlService *)arg1 didAbortCauseBy:(int)arg2 withMessage:(NSString *)arg3;
- (void)service:(SyncXmlService *)arg1 didCommitPushSuccessfully:(_Bool)arg2 withMessage:(NSString *)arg3;
- (void)service:(SyncXmlService *)arg1 didRollbackSuccessfully:(_Bool)arg2 withMessage:(NSString *)arg3;
- (void)service:(SyncXmlService *)arg1 didHeartbeatSuccessfully:(_Bool)arg2 withMessage:(NSString *)arg3;
- (void)service:(SyncXmlService *)arg1 didUploadSuccessfully:(_Bool)arg2 withMessage:(NSString *)arg3;
- (void)service:(SyncXmlService *)arg1 didCommitSuccessfully:(_Bool)arg2 withMessage:(NSString *)arg3;
- (void)service:(SyncXmlService *)arg1 didLoginSuccessfully:(_Bool)arg2 withMessage:(NSString *)arg3;
@end

