//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UIImageView, UILabel;

@interface TextSplashViewController : UIViewController
{
    UIImageView *_launchImageView;
    UILabel *_sloganLabel;
    UILabel *_dateLabel;
    UIImageView *_iconImageView;
    UIImageView *_iconBackgroundView;
}

@property(retain, nonatomic) UIImageView *iconBackgroundView; // @synthesize iconBackgroundView=_iconBackgroundView;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) UILabel *dateLabel; // @synthesize dateLabel=_dateLabel;
@property(retain, nonatomic) UILabel *sloganLabel; // @synthesize sloganLabel=_sloganLabel;
@property(retain, nonatomic) UIImageView *launchImageView; // @synthesize launchImageView=_launchImageView;
- (void).cxx_destruct;
- (void)initSloganLabel;
- (id)backgroundImage;
- (void)initLaunchImageView;
- (void)initDateLabel;
- (id)randomCategoryImage;
- (id)iconImage;
- (void)initIconImageView;
- (void)initSubviews;
- (void)updateViewConstraints;
- (void)viewDidLoad;

@end

