//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface TimeSpan : NSObject <NSCopying>
{
    double _startTimeInterval;
    double _endTimeInterval;
    NSString *_formattedMonthString;
}

@property(retain, nonatomic) NSString *formattedMonthString; // @synthesize formattedMonthString=_formattedMonthString;
@property double endTimeInterval; // @synthesize endTimeInterval=_endTimeInterval;
@property double startTimeInterval; // @synthesize startTimeInterval=_startTimeInterval;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)initWithStartTimeInterval:(double)arg1 endTimeInterval:(double)arg2 formattedMonthString:(id)arg3;

@end

