//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TransactionMultipleEditControllerViewModel.h"

@class NSArray;

@interface TransactionMultipleChangeToIncomeExpenseViewModel : TransactionMultipleEditControllerViewModel
{
    NSArray *_originTransfers;
}

@property(retain, nonatomic) NSArray *originTransfers; // @synthesize originTransfers=_originTransfers;
- (void).cxx_destruct;

@end

