//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TransactionByAccountViewController.h"

#import "CompositedAccountEditViewControllerDelegate.h"
#import "FloatBackgroundHeaderViewDelegate.h"
#import "HorizontalTableViewDataSource.h"
#import "HorizontalTableViewDelegate.h"

@class CompositedAccountNavHeaderVIew, HorizontalTableView, NSMutableArray, NSString;

@interface TransactionByCompositedAccountViewController : TransactionByAccountViewController <HorizontalTableViewDataSource, HorizontalTableViewDelegate, FloatBackgroundHeaderViewDelegate, CompositedAccountEditViewControllerDelegate>
{
    long long _lastSelectedColumn;
    NSMutableArray *_accountsArr;
    HorizontalTableView *_horizontalTableView;
    CompositedAccountNavHeaderVIew *_compositedAccountNavHeaderVIew;
}

@property(retain, nonatomic) CompositedAccountNavHeaderVIew *compositedAccountNavHeaderVIew; // @synthesize compositedAccountNavHeaderVIew=_compositedAccountNavHeaderVIew;
@property(retain, nonatomic) HorizontalTableView *horizontalTableView; // @synthesize horizontalTableView=_horizontalTableView;
@property(retain, nonatomic) NSMutableArray *accountsArr; // @synthesize accountsArr=_accountsArr;
- (void).cxx_destruct;
- (void)allowCropSubViewAlphaAnimate:(double)arg1;
- (void)accountDidDeleteOrHide;
- (void)editAccountAction;
- (void)editRecordAction;
- (id)transactionsWithTimeSpan:(id)arg1;
- (void)calculateMainAccountPercent;
- (void)loadMainAccountTimeSpans;
- (_Bool)existRecordWithTimeSpan:(id)arg1;
- (id)lastestTransactionDate;
- (id)oldestTransactionDate;
- (void)tableView:(id)arg1 didSelectColumn:(long long)arg2;
- (id)tableView:(id)arg1 cellForColumn:(long long)arg2;
- (long long)numberOfColumnInHorizontalTableView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (id)mainAccountPayoutInTimeSpan:(id)arg1;
- (id)mainAccountIncomeInTimeSpan:(id)arg1;
- (id)mainAccountBalance;
- (void)refreshCompositedAccountNavHeaderViewValue;
- (void)refreshTableHeader;
- (void)loadSubAccountData;
- (void)calculatePercent;
- (void)loadMainAccountData;
- (void)refreshData;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)reloadAccountsInfoWithMainAccountVo:(id)arg1;
- (id)initWithAccountVo:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

