//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TransactionFormatterUtil : NSObject
{
}

+ (id)tradeHourMinuteStringWithTransaction:(id)arg1;
+ (id)accountNameWithTransaction:(id)arg1;
+ (id)infoElementsWithTransaction:(id)arg1;
+ (id)rawPhotoImageWithTransaction:(id)arg1;
+ (struct CGSize)photoImageViewSizeWithRawPhotoImage:(id)arg1;
+ (id)photoImageWithRawPhotoImage:(id)arg1;
+ (id)moneyTextColorWithTransaction:(id)arg1;
+ (id)moneyStringWithTransaction:(id)arg1;
+ (id)transferToNameWithTransaction:(id)arg1;
+ (id)transactionNameWithTransaction:(id)arg1;
+ (id)categoryImageWithTransaction:(id)arg1;
+ (id)categoryImageWithTransactionType:(long long)arg1;

@end

