//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AccountVo, CategoryVo, CorporationVo, MemberVo, ProjectVo, TransactionMultipleEditControllerViewModel, TransactionMultipleEditIncomeExpenseViewController;

@protocol TransactionMultipleEditIncomeExpenseControllerOutput <NSObject>
- (void)reloadProjectInViewModel:(TransactionMultipleEditControllerViewModel *)arg1;
- (void)reloadCorporationInViewModel:(TransactionMultipleEditControllerViewModel *)arg1;
- (void)reloadMemberInViewModel:(TransactionMultipleEditControllerViewModel *)arg1;
- (void)reloadAccountInViewModel:(TransactionMultipleEditControllerViewModel *)arg1;
- (void)reloadCategoryInViewModel:(TransactionMultipleEditControllerViewModel *)arg1;
- (void)saveEditedTransactions:(TransactionMultipleEditIncomeExpenseViewController *)arg1;
- (void)changeViewModel:(TransactionMultipleEditControllerViewModel *)arg1 corporationTo:(CorporationVo *)arg2;
- (void)changeViewModel:(TransactionMultipleEditControllerViewModel *)arg1 memberTo:(MemberVo *)arg2;
- (void)changeViewModel:(TransactionMultipleEditControllerViewModel *)arg1 accountTo:(AccountVo *)arg2;
- (void)changeViewModel:(TransactionMultipleEditControllerViewModel *)arg1 projectTo:(ProjectVo *)arg2;
- (void)changeViewModel:(TransactionMultipleEditControllerViewModel *)arg1 categoryTo:(CategoryVo *)arg2;
- (void)editProject:(TransactionMultipleEditControllerViewModel *)arg1;
- (void)editCorporation:(TransactionMultipleEditControllerViewModel *)arg1;
- (void)editMember:(TransactionMultipleEditControllerViewModel *)arg1;
- (void)editAccount:(TransactionMultipleEditControllerViewModel *)arg1 accountType:(long long)arg2;
- (void)editCategory:(TransactionMultipleEditControllerViewModel *)arg1;
- (void)initViewModelWithController:(TransactionMultipleEditIncomeExpenseViewController *)arg1;
@end

