//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UILabel, WrapperView;

@interface TransactionMultipleSelectionToolBar : UIView
{
    _Bool _enableEdit;
    _Bool _enableCopy;
    _Bool _enableTransfer;
    _Bool _enableDelete;
    id <TransactionMultipleSelectionToolBarProtocol> _delegate;
    UIView *_topSeparator;
    UIButton *_editButton;
    WrapperView *_editWrapperView;
    UILabel *_editLabel;
    UIButton *_transferButton;
    WrapperView *_transferWrapperView;
    UILabel *_transferLabel;
    UIButton *_deleteButton;
    WrapperView *_deleteWrapperView;
    UILabel *_deleteLabel;
    UIButton *_duplicateButton;
    WrapperView *_duplicateWrapperView;
    UILabel *_duplicateLabel;
}

@property(retain, nonatomic) UILabel *duplicateLabel; // @synthesize duplicateLabel=_duplicateLabel;
@property(retain, nonatomic) WrapperView *duplicateWrapperView; // @synthesize duplicateWrapperView=_duplicateWrapperView;
@property(retain, nonatomic) UIButton *duplicateButton; // @synthesize duplicateButton=_duplicateButton;
@property(retain, nonatomic) UILabel *deleteLabel; // @synthesize deleteLabel=_deleteLabel;
@property(retain, nonatomic) WrapperView *deleteWrapperView; // @synthesize deleteWrapperView=_deleteWrapperView;
@property(retain, nonatomic) UIButton *deleteButton; // @synthesize deleteButton=_deleteButton;
@property(retain, nonatomic) UILabel *transferLabel; // @synthesize transferLabel=_transferLabel;
@property(retain, nonatomic) WrapperView *transferWrapperView; // @synthesize transferWrapperView=_transferWrapperView;
@property(retain, nonatomic) UIButton *transferButton; // @synthesize transferButton=_transferButton;
@property(retain, nonatomic) UILabel *editLabel; // @synthesize editLabel=_editLabel;
@property(retain, nonatomic) WrapperView *editWrapperView; // @synthesize editWrapperView=_editWrapperView;
@property(retain, nonatomic) UIButton *editButton; // @synthesize editButton=_editButton;
@property(retain, nonatomic) UIView *topSeparator; // @synthesize topSeparator=_topSeparator;
@property(nonatomic) __weak id <TransactionMultipleSelectionToolBarProtocol> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool enableDelete; // @synthesize enableDelete=_enableDelete;
@property(nonatomic) _Bool enableTransfer; // @synthesize enableTransfer=_enableTransfer;
@property(nonatomic) _Bool enableCopy; // @synthesize enableCopy=_enableCopy;
@property(nonatomic) _Bool enableEdit; // @synthesize enableEdit=_enableEdit;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)unhookKVO;
- (void)hookKVO;
- (id)bgColorWithHighlighted:(_Bool)arg1;
- (id)borderColorWithEnable:(_Bool)arg1;
- (id)textColorWithEnable:(_Bool)arg1;
- (id)iconColorWithEnable:(_Bool)arg1;
- (id)duplicateIconWithEnable:(_Bool)arg1;
- (id)deleteIconWithEnable:(_Bool)arg1;
- (id)transferIconWithEnable:(_Bool)arg1;
- (id)editIconWithEnable:(_Bool)arg1;
- (void)deleteAction;
- (void)transferAction;
- (void)editAction;
- (void)duplicateAction;
- (id)labelWithTitle:(id)arg1;
- (void)updateConstraints;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

