//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VoListViewController.h"

#import "AddingAccountViewControllerDelegate.h"
#import "CompositeTableViewDelegate.h"
#import "FloatBackgroundWallViewDelegate.h"
#import "PopupMenuViewDelegate.h"

@class AccountVo, FDAccountHeaderScrollView, FloatBackgroundHeaderView, FloatBackgroundWallView, NSString, PopupMenuView, UIButton, UIView;

@interface TransactionByAccountViewController : VoListViewController <PopupMenuViewDelegate, FloatBackgroundWallViewDelegate, CompositeTableViewDelegate, AddingAccountViewControllerDelegate>
{
    AccountVo *_accountVo;
    _Bool _isFromAssetsOrLiabilityReport;
    FloatBackgroundWallView *_wallView;
    FloatBackgroundHeaderView *_tableHeaderView;
    UIView *_rightBarView;
    UIButton *_editBarButton;
    UIView *_maskView;
    NSString *_initialEditingAccountName;
    PopupMenuView *_popupMenuView;
    FDAccountHeaderScrollView *_scrollHeader;
}

@property(retain, nonatomic) FDAccountHeaderScrollView *scrollHeader; // @synthesize scrollHeader=_scrollHeader;
@property(retain, nonatomic) PopupMenuView *popupMenuView; // @synthesize popupMenuView=_popupMenuView;
@property(retain, nonatomic) NSString *initialEditingAccountName; // @synthesize initialEditingAccountName=_initialEditingAccountName;
@property(retain, nonatomic) UIView *maskView; // @synthesize maskView=_maskView;
@property(retain, nonatomic) UIButton *editBarButton; // @synthesize editBarButton=_editBarButton;
@property(nonatomic) _Bool isFromAssetsOrLiabilityReport; // @synthesize isFromAssetsOrLiabilityReport=_isFromAssetsOrLiabilityReport;
@property(retain, nonatomic) UIView *rightBarView; // @synthesize rightBarView=_rightBarView;
@property(retain, nonatomic) FloatBackgroundHeaderView *tableHeaderView; // @synthesize tableHeaderView=_tableHeaderView;
@property(retain, nonatomic) FloatBackgroundWallView *wallView; // @synthesize wallView=_wallView;
@property(retain, nonatomic) AccountVo *accountVo; // @synthesize accountVo=_accountVo;
- (void).cxx_destruct;
- (void)needSetNavigationBarBackground:(id)arg1;
- (void)rightScrollViewDidScroll:(id)arg1;
- (void)fillMonthNavHeader:(id)arg1 inSection:(long long)arg2;
- (void)popupMenuView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)updateIncomeAndExpenseStatisticsValues;
- (_Bool)needSpeedUpWhenHasMoreData;
- (id)transactionsWithTimeSpan:(id)arg1;
- (id)accountAmount;
- (void)refreshTableHeader;
- (id)service:(id)arg1 calculateExpenseAmountBetween:(double)arg2 and:(double)arg3;
- (id)service:(id)arg1 calculateIncomeAmountBetween:(double)arg2 and:(double)arg3;
- (void)reloadVo;
- (_Bool)existVoByService:(id)arg1 between:(double)arg2 and:(double)arg3;
- (id)latestTradeTime;
- (id)oldestTradeTime;
- (void)didReceiveMemoryWarning;
- (void)editingAccountViewController:(id)arg1 didFinishWithSave:(_Bool)arg2;
- (void)editAccountAction;
- (void)editRecordAction;
- (void)handleNotification:(id)arg1;
- (void)removeNotificationObserver;
- (void)addNotificationObserver;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)addAction:(id)arg1;
- (void)setNormalNavigationRightItem;
- (void)setEditingNavigationRightItem;
- (void)setNormalNavigationLeftItem;
- (void)setEditingNavigationLeftItem;
- (void)refreshRightBarButton;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithAccountVo:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

