//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CategoryVo, NSArray, NSDate, NSDecimalNumber, NSDictionary, NSString, RecordInCellVo, Transaction;

@protocol TransactionDao <NSObject>
- (void)updatePhotoToNeedUploadByTransactionIds:(NSArray *)arg1;
- (NSDictionary *)transactionIdsWithPhotoNames:(NSArray *)arg1;
- (NSArray *)listAllTransactionsAfterGivenTime:(NSArray *)arg1 startTime:(double)arg2;
- (NSArray *)listRecordInCellByTransTypeForSuperTransactions:(NSArray *)arg1 localCurrencyCode:(NSString *)arg2 categoryIds:(NSArray *)arg3 accountIds:(NSArray *)arg4 projectIds:(NSArray *)arg5 corporationIds:(NSArray *)arg6 members:(NSArray *)arg7 memo:(NSString *)arg8 beginTime:(double)arg9 endTime:(double)arg10 minAmount:(double)arg11 maxAmount:(double)arg12;
- (NSArray *)listRecordInCellByTransTypeForSuperTransaction:(int)arg1 localCurrencyCode:(NSString *)arg2 categoryIds:(NSArray *)arg3 accountIds:(NSArray *)arg4 projectIds:(NSArray *)arg5 corporationIds:(NSArray *)arg6 members:(NSArray *)arg7 memo:(NSString *)arg8 beginTime:(double)arg9 endTime:(double)arg10 minAmount:(double)arg11 maxAmount:(double)arg12;
- (NSArray *)dumpTransactionForTodayWidgetWithStartTime:(double)arg1 andEndTime:(double)arg2 andCurrencyCode:(NSString *)arg3;
- (_Bool)hasNegativeTransactionPOIDInExtraTable;
- (_Bool)modifyTransactoinPhotoName:(NSString *)arg1 toNewName:(NSString *)arg2;
- (_Bool)replaceTransactions:(NSArray *)arg1 errorMessage:(id *)arg2;
- (_Bool)updateTransactionPOIDWithPOIDMap:(NSDictionary *)arg1 errorMessage:(id *)arg2;
- (long long)countOfAllTransactions;
- (long long)countOfTransactionsByMailbillImport;
- (_Bool)deleteExpenseByCreatedTime:(double)arg1 source:(NSString *)arg2;
- (NSArray *)transactionsByCreateTime:(double)arg1 source:(NSString *)arg2;
- (NSArray *)listTimeGroupbyCreateTimeForMailbillImport;
- (NSArray *)duplicateTransactionBetweenAccount:(long long)arg1 andAnotherAccount:(long long)arg2;
- (NSArray *)secondLevelListTransactionsByTransType:(int)arg1 localCurrencyCode:(NSString *)arg2 accountIds:(NSArray *)arg3 categoryIds:(NSArray *)arg4 projectIds:(NSArray *)arg5 corporationIds:(NSArray *)arg6 memberIds:(NSArray *)arg7 memo:(NSString *)arg8 beginTime:(long long)arg9 endTime:(long long)arg10 minAmount:(double)arg11 maxAmount:(double)arg12;
- (NSArray *)secondLevelListTransactionsByTransType:(int)arg1 localCurrencyCode:(NSString *)arg2 accountIds:(NSArray *)arg3 categoryIds:(NSArray *)arg4 projectIds:(NSArray *)arg5 corporationIds:(NSArray *)arg6 memo:(NSString *)arg7 beginTime:(long long)arg8 endTime:(long long)arg9 minAmount:(double)arg10 maxAmount:(double)arg11;
- (NSDate *)firstTransactionTimeWithPhotoNotUpdate;
- (NSDate *)lastTransactionTimeBetween:(long long)arg1 and:(long long)arg2;
- (NSDate *)lastTransactionTime;
- (NSDate *)firstTransactionTimeBetween:(long long)arg1 and:(long long)arg2;
- (NSDate *)firstTransactionTime;
- (Transaction *)lastCreatedTransaction;
- (NSDate *)lastCreatedTime;
- (NSArray *)listTransactionDatasByTransType:(int)arg1 localCurrencyCode:(NSString *)arg2 accountIds:(NSArray *)arg3 categoryIds:(NSArray *)arg4 projectIds:(NSArray *)arg5 corporationIds:(NSArray *)arg6 memberIds:(NSArray *)arg7 memo:(NSString *)arg8 beginTime:(long long)arg9 endTime:(long long)arg10 minAmount:(double)arg11 maxAmount:(double)arg12;
- (NSArray *)listTransactionsByTransType:(int)arg1 localCurrencyCode:(NSString *)arg2 accountIds:(NSArray *)arg3 categoryIds:(NSArray *)arg4 projectIds:(NSArray *)arg5 corporationIds:(NSArray *)arg6 memberIds:(NSArray *)arg7 memo:(NSString *)arg8 beginTime:(long long)arg9 endTime:(long long)arg10 minAmount:(double)arg11 maxAmount:(double)arg12 unSelectedSecondCategoryIds:(NSArray *)arg13;
- (NSArray *)listTransactionsByTransType:(int)arg1 localCurrencyCode:(NSString *)arg2 accountIds:(NSArray *)arg3 categoryIds:(NSArray *)arg4 projectIds:(NSArray *)arg5 corporationIds:(NSArray *)arg6 memo:(NSString *)arg7 beginTime:(long long)arg8 endTime:(long long)arg9 minAmount:(double)arg10 maxAmount:(double)arg11;
- (NSArray *)listRecordInCellBylocalCurrencyCode:(NSString *)arg1 category:(CategoryVo *)arg2;
- (NSArray *)listNotJCTRecordInCellByTransType:(int)arg1 localCurrencyCode:(NSString *)arg2 categoryIds:(NSArray *)arg3 accountIds:(NSArray *)arg4 projectIds:(NSArray *)arg5 corporationIds:(NSArray *)arg6 members:(NSArray *)arg7 memo:(NSString *)arg8 beginTime:(double)arg9 endTime:(double)arg10 minAmount:(double)arg11 maxAmount:(double)arg12;
- (NSArray *)listRecordInCellByTransType:(int)arg1 localCurrencyCode:(NSString *)arg2 categoryIds:(NSArray *)arg3 accountIds:(NSArray *)arg4 projectIds:(NSArray *)arg5 corporationIds:(NSArray *)arg6 members:(NSArray *)arg7 memo:(NSString *)arg8 beginTime:(double)arg9 endTime:(double)arg10 minAmount:(double)arg11 maxAmount:(double)arg12 unSelectedSecondCategoryIds:(NSArray *)arg13;
- (NSArray *)listRecordInCellByTransType:(int)arg1 localCurrencyCode:(NSString *)arg2 categoryIds:(NSArray *)arg3 accountIds:(NSArray *)arg4 projectIds:(NSArray *)arg5 corporationIds:(NSArray *)arg6 memo:(NSString *)arg7 beginTime:(double)arg8 endTime:(double)arg9 minAmount:(double)arg10 maxAmount:(double)arg11;
- (long long)transactionIdWithPhotoName:(NSString *)arg1;
- (_Bool)updatePhotoNeedUpload:(_Bool)arg1 transactionId:(long long)arg2;
- (NSArray *)listImageInTransactionFromSyncTableByStartTime:(double)arg1;
- (NSString *)getRelationByID:(long long)arg1;
- (NSArray *)transactionsByMemberId:(long long)arg1;
- (NSArray *)transactionsByProjectId:(long long)arg1;
- (NSArray *)transactionsByType:(long long)arg1;
- (NSArray *)transactionsByTradeTime:(double)arg1;
- (Transaction *)transferOutTransactionByRelation:(NSString *)arg1;
- (Transaction *)transferInTransactionByRelation:(NSString *)arg1;
- (NSArray *)listTransactionByRelation:(NSString *)arg1;
- (NSDecimalNumber *)sumTransactionAmounWithoutHiddenAccountWithTransactionType:(long long)arg1 startTime:(double)arg2 endTime:(double)arg3 currencyCode:(NSString *)arg4;
- (NSDecimalNumber *)sumTransactionAmountWithAccount:(long long)arg1 transactionType:(long long)arg2 startTime:(double)arg3 endTime:(double)arg4 currencyCode:(NSString *)arg5;
- (NSDecimalNumber *)sumTransactionAmountWithTransactionType:(long long)arg1 corporationId:(long long)arg2 startTime:(double)arg3 endTime:(double)arg4 currencyCode:(NSString *)arg5;
- (NSDecimalNumber *)sumTransactionAmountWithTransactionType:(long long)arg1 tagId:(long long)arg2 startTime:(double)arg3 endTime:(double)arg4 currencyCode:(NSString *)arg5;
- (NSDecimalNumber *)sumTransactionAmounWithTransactionType:(long long)arg1 startTime:(double)arg2 endTime:(double)arg3 currencyCode:(NSString *)arg4;
- (NSDecimalNumber *)sumTransactionAmounWithCategory:(long long)arg1 transactionType:(long long)arg2 startTime:(double)arg3 endTime:(double)arg4 currencyCode:(NSString *)arg5;
- (NSArray *)recordsFromTransactionByCreditorId:(long long)arg1 withCurrencyCode:(NSString *)arg2 accountGroupType:(long long)arg3;
- (_Bool)existRecordWithCategoryPOID:(long long)arg1 between:(double)arg2 and:(double)arg3;
- (_Bool)existRecordWithCorporationId:(long long)arg1 between:(double)arg2 and:(double)arg3;
- (NSArray *)recordsByCorporationId:(long long)arg1 between:(double)arg2 and:(double)arg3;
- (_Bool)existRecordWithProjectId:(long long)arg1 between:(double)arg2 and:(double)arg3;
- (NSArray *)recordsByProjectId:(long long)arg1 between:(double)arg2 and:(double)arg3;
- (_Bool)existRecordWithAccountId:(long long)arg1 between:(double)arg2 and:(double)arg3;
- (NSArray *)recordsFromTransactionByAccountId:(long long)arg1 between:(double)arg2 and:(double)arg3;
- (RecordInCellVo *)recordById:(long long)arg1;
- (_Bool)existRecordBetween:(double)arg1 and:(double)arg2;
- (NSArray *)transactionsSinceUpdateTime:(double)arg1;
- (NSArray *)recordsBetween:(double)arg1 And:(double)arg2;
- (unsigned long long)countOfTransactionsRelatedToAcountId:(long long)arg1 andBetweenStartTime:(double)arg2 andEndTime:(double)arg3 andTypes:(NSArray *)arg4;
- (unsigned long long)countOfTransactionsRelatedToAcountId:(long long)arg1 andBetweenStartTime:(double)arg2 andEndTime:(double)arg3;
- (unsigned long long)countOfTransactionsBetweenStartTime:(double)arg1 andEndTime:(double)arg2 andTypes:(NSArray *)arg3;
- (unsigned long long)countOfTransactionsBetweenStartTime:(double)arg1 andEndTime:(double)arg2;
- (NSArray *)listAllTransactionsByTradeTimeDescreaseOrderedStartTime:(double)arg1 endTime:(double)arg2;
- (NSArray *)listAllTransactionsByTradeTimeDescreaseOrderedWithTypes:(NSArray *)arg1 startTime:(double)arg2 endTime:(double)arg3;
- (NSArray *)listAllTransactionsByTradeTimeDescreaseOrderedWithTypes:(NSArray *)arg1 andOffset:(unsigned long long)arg2 andLimit:(unsigned long long)arg3;
- (NSArray *)listAllTransactionsByTradeTimeDescreaseOrderWithOffset:(unsigned long long)arg1 andLimit:(unsigned long long)arg2;
- (NSArray *)listAllTransactionsSinceDay:(double)arg1 byTradeTimeDescreaseOrderedWithTypes:(NSArray *)arg2 andOffset:(unsigned long long)arg3 andLimit:(unsigned long long)arg4;
- (NSArray *)listAllTransactionsSinceDay:(double)arg1 byTradeTimeDescreaseOrderedWithOffset:(unsigned long long)arg2 andLimit:(unsigned long long)arg3;
- (NSArray *)listTransaction;
- (NSArray *)transactionsWithIdsSpecialForChart:(NSArray *)arg1;
- (NSArray *)transactionWithRelationTranByIds:(NSArray *)arg1;
- (NSString *)logOfOperationById:(long long)arg1;
- (NSDictionary *)transactionsByIds:(NSArray *)arg1;
- (Transaction *)transactionById:(long long)arg1;
- (_Bool)updateTransaction:(Transaction *)arg1 log:(NSString *)arg2;
- (_Bool)updateTransaction:(Transaction *)arg1;
- (_Bool)deleteTransactionById:(long long)arg1;
- (long long)transactionWithSourceKey:(NSString *)arg1;
- (long long)addTransactionFromAccountBookImport:(Transaction *)arg1;
- (long long)addTransactionFromMyCardImort:(Transaction *)arg1;
- (long long)addTransaction:(Transaction *)arg1 isMailImport:(_Bool)arg2;
- (long long)addTransaction:(Transaction *)arg1 log:(NSString *)arg2;
- (long long)addTransaction:(Transaction *)arg1;
- (NSArray *)addTransactions:(NSArray *)arg1 withLog:(NSString *)arg2;
@end

