//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIDevice.h"

@interface UIDevice (HardwareVersion)
+ (_Bool)isIPhoneDevice;
+ (_Bool)isArchARM64_OR_X86_64;
+ (id)deviceModel;
- (double)screenScale;
- (id)screenAspectByPixel;
- (struct CGSize)splashSizeByPixelForSplashRequest;
- (id)splashAspectByPixelForSplashRequest;
- (struct CGSize)splashSizeByPixel;
- (id)splashAspectByPixel;
- (_Bool)isScreenAspect16_9;
- (_Bool)isScreenAspect3_2;
- (_Bool)isIPhone6Plus;
- (_Bool)isIPhone6;
- (_Bool)isIPhone5;
- (id)platformShortString;
- (id)platformString;
@end

