//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@interface UIImageView (FDImageCache)
- (id)downloader;
- (void)setDownloader:(id)arg1;
- (void)mm_setImageWithURL:(id)arg1 placeholder:(id)arg2 animated:(_Bool)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)mm_setImageWithURL:(id)arg1 placeholder:(id)arg2 animated:(_Bool)arg3;
- (void)mm_setImageWithURL:(id)arg1;
@end

