//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSString, UIButton, UILabel;

@interface UpgradeToProController : UIViewController
{
    UILabel *_headerLabel;
    UIButton *_actionButton;
    UILabel *_footerLabel;
    NSString *_headerString;
}

@property(retain, nonatomic) NSString *headerString; // @synthesize headerString=_headerString;
@property(retain, nonatomic) UILabel *footerLabel; // @synthesize footerLabel=_footerLabel;
@property(retain, nonatomic) UIButton *actionButton; // @synthesize actionButton=_actionButton;
@property(retain, nonatomic) UILabel *headerLabel; // @synthesize headerLabel=_headerLabel;
- (void).cxx_destruct;
- (void)actionBtn_Click:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)onBackButtonClicked;
- (void)viewDidLoad;

@end

