//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TradingEntity.h"

@interface User : TradingEntity
{
    double _lastUpdateTime;
}

@property double lastUpdateTime; // @synthesize lastUpdateTime=_lastUpdateTime;
- (id)initWithId:(long long)arg1 name:(id)arg2;
- (id)init;

@end

