//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, User;

@protocol UserDao <NSObject>
- (User *)getUserByUsername:(NSString *)arg1 password:(NSString *)arg2;
- (long long)userIdSetByServer;
- (long long)addUser:(User *)arg1;
@end

