//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSString, UIImage;

@interface UserAccountVo : NSObject <NSCoding>
{
    _Bool _isOwner;
    NSString *_account;
    NSString *_avatarURL;
    NSString *_nickname;
    NSString *_inviteCode;
}

@property(nonatomic) _Bool isOwner; // @synthesize isOwner=_isOwner;
@property(retain, nonatomic) NSString *inviteCode; // @synthesize inviteCode=_inviteCode;
@property(retain, nonatomic) NSString *nickname; // @synthesize nickname=_nickname;
@property(retain, nonatomic) NSString *avatarURL; // @synthesize avatarURL=_avatarURL;
@property(retain, nonatomic) NSString *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithAccount:(id)arg1 avatarURL:(id)arg2;
@property(retain, nonatomic) UIImage *image;

@end

