//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class NSArray;

@interface VerticalTitleButton : UIButton
{
    NSArray *_titleLabels;
}

@property(retain, nonatomic) NSArray *titleLabels; // @synthesize titleLabels=_titleLabels;
- (void).cxx_destruct;
- (void)setHighlighted:(_Bool)arg1;
- (void)setSelected:(_Bool)arg1;
- (void)updateTitleLabelsTextColor:(id)arg1;

@end

