//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HorizonSlideMenu.h"

@interface VerticalSlideMenu : HorizonSlideMenu
{
}

- (void)slide;
- (void)_expand;
- (id)_blowupAnimationAtPoint:(struct CGPoint)arg1;
- (void)setExpanding:(_Bool)arg1;
- (void)setMenusArray:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 menus:(id)arg2 index:(long long)arg3;
- (id)initWithFrame:(struct CGRect)arg1 withOffsetX:(double)arg2;

@end

